import type { EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

import { BoundedJsonValueEntity } from '../../../helpers/entities/BoundedJsonValueEntity.js';

/** The `fetch.loop.spec.ts` scenario case shape: one branch per `outcome`. */
export namespace FetchScenarioCaseEntity {
  const jsonObjectSchema = { 'additionalProperties': BoundedJsonValueEntity.Schema, 'properties': {}, 'required': [], 'type': 'object' } as const;
  const requestSignalSchema = { 'oneOf': [{ 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' }, 'shape': { 'const': 'abort-after-ms' } }, 'required': ['delayMs', 'shape'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'shape': { 'const': 'already-aborted' } }, 'required': ['shape'], 'type': 'object' }] } as const;
  const requestSchema = { 'additionalProperties': false, 'properties': { 'argumentList': { 'items': BoundedJsonValueEntity.Schema, 'type': 'array' }, 'client': { 'additionalProperties': false, 'properties': { 'baseURL': { 'type': 'string' }, 'dispatcher': { 'additionalProperties': false, 'properties': { 'connections': { 'type': 'integer' }, 'enabled': { 'type': 'boolean' } }, 'required': [], 'type': 'object' }, 'parameters': jsonObjectSchema }, 'required': [], 'type': 'object' }, 'invoke': { 'enum': ['apply-get', 'get'] }, 'options': { 'additionalProperties': false, 'properties': { 'headers': { 'additionalProperties': { 'type': 'string' }, 'properties': {}, 'required': [], 'type': 'object' }, 'method': { 'const': 'GET' }, 'requestId': { 'type': 'string' }, 'signal': requestSignalSchema, 'timeout': BoundedJsonValueEntity.Schema }, 'required': [], 'type': 'object' }, 'path': { 'type': 'string' }, 'signal': requestSignalSchema, 'timeout': BoundedJsonValueEntity.Schema, 'url': { 'type': 'string' } }, 'required': [], 'type': 'object' } as const;

  export const Schema = { 'oneOf': [{ 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'error': { 'enum': ['AbortError', 'ConnectTimeoutError', 'Error', 'TimeoutError'] }, 'messageIncludes': { 'items': { 'type': 'string' }, 'type': 'array' }, 'messagePattern': { 'type': 'string' }, 'timeoutMs': { 'type': 'integer' } }, 'required': ['error'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'request': requestSchema }, 'required': ['request'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'outcome': { 'const': 'reject' } }, 'required': ['description', 'expected', 'input', 'name', 'outcome'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'status': { 'type': 'integer' }, 'text': { 'type': 'string' }, 'url': { 'type': 'string' } }, 'required': ['status'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'request': requestSchema }, 'required': ['request'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'outcome': { 'const': 'ok' } }, 'required': ['description', 'expected', 'input', 'name', 'outcome'], 'type': 'object' }] } as const;

  const JsonObjectNode = SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': BoundedJsonValueEntity.Node, 'patternProperties': {} });
  const RequestSignalNode = SchemaNode.defineOneOf({}, [SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'shape': SchemaNode.defineConst({}, 'abort-after-ms' as const) }, ['delayMs', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'shape': SchemaNode.defineConst({}, 'already-aborted' as const) }, ['shape'] as const, { 'additionalProperties': false, 'patternProperties': {} })] as const);
  const RequestNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'argumentList': SchemaNode.defineArray({ 'type': 'array' } as const, BoundedJsonValueEntity.Node, undefined), 'client': SchemaNode.defineObject({ 'type': 'object' } as const, { 'baseURL': SchemaNode.defineString({ 'type': 'string' } as const), 'dispatcher': SchemaNode.defineObject({ 'type': 'object' } as const, { 'connections': SchemaNode.defineNumber({ 'type': 'integer' } as const), 'enabled': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'parameters': JsonObjectNode }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'invoke': SchemaNode.defineEnum({}, ['apply-get', 'get'] as const), 'options': SchemaNode.defineObject({ 'type': 'object' } as const, { 'headers': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': SchemaNode.defineString({ 'type': 'string' } as const), 'patternProperties': {} }), 'method': SchemaNode.defineConst({}, 'GET' as const), 'requestId': SchemaNode.defineString({ 'type': 'string' } as const), 'signal': RequestSignalNode, 'timeout': BoundedJsonValueEntity.Node }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'path': SchemaNode.defineString({ 'type': 'string' } as const), 'signal': RequestSignalNode, 'timeout': BoundedJsonValueEntity.Node, 'url': SchemaNode.defineString({ 'type': 'string' } as const) }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });

  export const Node = SchemaNode.defineOneOf({}, [SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'error': SchemaNode.defineEnum({}, ['AbortError', 'ConnectTimeoutError', 'Error', 'TimeoutError'] as const), 'messageIncludes': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'messagePattern': SchemaNode.defineString({ 'type': 'string' } as const), 'timeoutMs': SchemaNode.defineNumber({ 'type': 'integer' } as const) }, ['error'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'request': RequestNode }, ['request'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'outcome': SchemaNode.defineConst({}, 'reject' as const) }, ['description', 'expected', 'input', 'name', 'outcome'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'status': SchemaNode.defineNumber({ 'type': 'integer' } as const), 'text': SchemaNode.defineString({ 'type': 'string' } as const), 'url': SchemaNode.defineString({ 'type': 'string' } as const) }, ['status'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'request': RequestNode }, ['request'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'outcome': SchemaNode.defineConst({}, 'ok' as const) }, ['description', 'expected', 'input', 'name', 'outcome'] as const, { 'additionalProperties': false, 'patternProperties': {} })] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
}
