import type { EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

/** The 14 scenario shapes `filter-engine-characterization.loop.spec.ts` exercises. */
export namespace FilterEngineCharacterizationScenarioCaseEntity {
  const arrayEqualsDeepSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' }, 'validFail': { 'type': 'boolean' } }, 'required': ['valid', 'validFail'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'entries': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['entries'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'array-equals-deep' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const arrayEqualsDeepNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'validFail': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid', 'validFail'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'entries': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['entries'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'array-equals-deep' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const customPluginOperatorSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' }, 'validFail': { 'type': 'boolean' } }, 'required': ['valid', 'validFail'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'failValue': { 'type': 'string' }, 'matchValue': { 'type': 'string' } }, 'required': ['failValue', 'matchValue'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'custom-plugin-operator' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const customPluginOperatorNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'validFail': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid', 'validFail'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failValue': SchemaNode.defineString({ 'type': 'string' } as const), 'matchValue': SchemaNode.defineString({ 'type': 'string' } as const) }, ['failValue', 'matchValue'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'custom-plugin-operator' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const dateBetweenInRangeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'dateValue': { 'type': 'string' }, 'rangeMaximum': { 'type': 'string' }, 'rangeMinimum': { 'type': 'string' } }, 'required': ['dateValue', 'rangeMaximum', 'rangeMinimum'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'date-between-in-range' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const dateBetweenInRangeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'dateValue': SchemaNode.defineString({ 'type': 'string' } as const), 'rangeMaximum': SchemaNode.defineString({ 'type': 'string' } as const), 'rangeMinimum': SchemaNode.defineString({ 'type': 'string' } as const) }, ['dateValue', 'rangeMaximum', 'rangeMinimum'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'date-between-in-range' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const dateBetweenOutOfRangeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'dateValue': { 'type': 'string' }, 'rangeMaximum': { 'type': 'string' }, 'rangeMinimum': { 'type': 'string' } }, 'required': ['dateValue', 'rangeMaximum', 'rangeMinimum'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'date-between-out-of-range' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const dateBetweenOutOfRangeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'dateValue': SchemaNode.defineString({ 'type': 'string' } as const), 'rangeMaximum': SchemaNode.defineString({ 'type': 'string' } as const), 'rangeMinimum': SchemaNode.defineString({ 'type': 'string' } as const) }, ['dateValue', 'rangeMaximum', 'rangeMinimum'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'date-between-out-of-range' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const dateEqualsMatchSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'dateValue': { 'type': 'string' } }, 'required': ['dateValue'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'date-equals-match' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const dateEqualsMatchNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'dateValue': SchemaNode.defineString({ 'type': 'string' } as const) }, ['dateValue'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'date-equals-match' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const enumReachabilitySanitySchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'enum-reachability-sanity' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const enumReachabilitySanityNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'enum-reachability-sanity' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const mapHasDirectSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'entries': { 'items': { 'items': { 'oneOf': [{ 'type': 'string' }, { 'type': 'boolean' }] }, 'type': 'array' }, 'type': 'array' }, 'matchValue': { 'type': 'string' } }, 'required': ['entries', 'matchValue'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'map-has-direct' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const mapHasDirectNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'entries': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineOneOf({}, [SchemaNode.defineString({ 'type': 'string' } as const), SchemaNode.defineBoolean({ 'type': 'boolean' } as const)] as const), undefined), undefined), 'matchValue': SchemaNode.defineString({ 'type': 'string' } as const) }, ['entries', 'matchValue'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'map-has-direct' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const mapSizeWildcardSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'items': { 'items': { 'items': { 'items': { 'oneOf': [{ 'type': 'string' }, { 'type': 'number' }] }, 'type': 'array' }, 'type': 'array' }, 'type': 'array' }, 'size': { 'type': 'number' } }, 'required': ['items', 'size'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'map-size-wildcard' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const mapSizeWildcardNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineOneOf({}, [SchemaNode.defineString({ 'type': 'string' } as const), SchemaNode.defineNumber({ 'type': 'number' } as const)] as const), undefined), undefined), undefined), 'size': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['items', 'size'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'map-size-wildcard' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const nestedOrGroupSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' }, 'validFail': { 'type': 'boolean' } }, 'required': ['valid', 'validFail'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'failData': { 'additionalProperties': false, 'properties': { 'priority': { 'type': 'number' }, 'status': { 'type': 'string' } }, 'required': ['priority', 'status'], 'type': 'object' }, 'matchData': { 'additionalProperties': false, 'properties': { 'priority': { 'type': 'number' }, 'status': { 'type': 'string' } }, 'required': ['priority', 'status'], 'type': 'object' } }, 'required': ['failData', 'matchData'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'nested-or-group' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const nestedOrGroupNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'validFail': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid', 'validFail'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failData': SchemaNode.defineObject({ 'type': 'object' } as const, { 'priority': SchemaNode.defineNumber({ 'type': 'number' } as const), 'status': SchemaNode.defineString({ 'type': 'string' } as const) }, ['priority', 'status'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'matchData': SchemaNode.defineObject({ 'type': 'object' } as const, { 'priority': SchemaNode.defineNumber({ 'type': 'number' } as const), 'status': SchemaNode.defineString({ 'type': 'string' } as const) }, ['priority', 'status'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['failData', 'matchData'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'nested-or-group' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const registeredCustomGateOperatorSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'data': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' } }, 'required': ['data'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'registered-custom-gate-operator' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const registeredCustomGateOperatorNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'data': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['data'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'registered-custom-gate-operator' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const setHasDirectSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'entries': { 'items': { 'type': 'string' }, 'type': 'array' }, 'matchValue': { 'type': 'string' } }, 'required': ['entries', 'matchValue'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'set-has-direct' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const setHasDirectNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'entries': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'matchValue': SchemaNode.defineString({ 'type': 'string' } as const) }, ['entries', 'matchValue'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'set-has-direct' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const setSizeWildcardSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'items': { 'items': { 'items': { 'type': 'string' }, 'type': 'array' }, 'type': 'array' }, 'size': { 'type': 'number' } }, 'required': ['items', 'size'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'set-size-wildcard' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const setSizeWildcardNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), undefined), 'size': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['items', 'size'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'set-size-wildcard' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const stringGateFailSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'data': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' } }, 'required': ['data'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'string-gate-fail' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const stringGateFailNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'data': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['data'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'string-gate-fail' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const stringGatePassSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'data': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' } }, 'required': ['data'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'string-gate-pass' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const stringGatePassNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'data': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['data'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'string-gate-pass' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  export const Schema = {
    'oneOf': [
      arrayEqualsDeepSchema, customPluginOperatorSchema, dateBetweenInRangeSchema, dateBetweenOutOfRangeSchema,
      dateEqualsMatchSchema, enumReachabilitySanitySchema, mapHasDirectSchema, mapSizeWildcardSchema,
      nestedOrGroupSchema, registeredCustomGateOperatorSchema, setHasDirectSchema, setSizeWildcardSchema,
      stringGateFailSchema, stringGatePassSchema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    arrayEqualsDeepNode, customPluginOperatorNode, dateBetweenInRangeNode, dateBetweenOutOfRangeNode,
    dateEqualsMatchNode, enumReachabilitySanityNode, mapHasDirectNode, mapSizeWildcardNode,
    nestedOrGroupNode, registeredCustomGateOperatorNode, setHasDirectNode, setSizeWildcardNode,
    stringGateFailNode, stringGatePassNode
  ] as const);

  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
}
