import type { FromSchema, JSONSchema } from 'json-schema-to-ts';

import { EntityCompiler } from '@studnicky/entity/node';

import {
  PROBLEM_STATUS_MAXIMUM,
  PROBLEM_STATUS_MINIMUM,
  PROBLEM_TYPE_BLANK
} from '../constants/ProblemConstants.js';
import { CauseNodeEntity } from './CauseNodeEntity.js';
import { ValidationViolationEntity } from './ValidationViolationEntity.js';

/**
 * RFC 9457 Problem Details — the canonical serialized form of every error in this workspace.
 *
 * Two RFC requirements drive this shape and are easy to get wrong:
 *
 * 1. §3.1 — EVERY member is optional, and `type` defaults to `about:blank`. A conformant
 *    producer may emit `{}`. Requiring members would reject valid Problem Details.
 * 2. §3.2 — a problem type definition MAY extend the object, and consumers MUST ignore
 *    members they do not recognise. The object is therefore open, never sealed.
 *
 * The members below `instance` are this workspace's extension members. They are declared
 * rather than left to the open bag so they carry real types, while `additionalProperties`
 * stays true so a foreign extension still validates.
 */
export namespace ProblemDetailsEntity {
  export const Schema = {
    '$id': 'https://studnicky.github.io/substrate/schemas/ProblemDetails',
    '$schema': 'https://json-schema.org/draft/2020-12/schema',
    'additionalProperties': true,
    'properties': {
      'causes': {
        'description': 'Extension: bounded, cycle-safe projection of the cause chain, nearest first.',
        'items': CauseNodeEntity.Schema,
        'type': 'array'
      },
      'code': {
        'description': 'Extension: registered dotted error code, e.g. `errors.validationFailed`.',
        'type': 'string'
      },
      'context': {
        'description': 'Extension: structured metadata captured at construction.',
        'type': 'object'
      },
      'correlationId': {
        'description': 'Extension: correlation ID for distributed tracing.',
        'type': 'string'
      },
      'detail': {
        'description': 'Human-readable explanation specific to THIS occurrence of the problem.',
        'type': 'string'
      },

      'errors': {
        'description': 'Extension: individual validation violations behind this problem.',
        'items': ValidationViolationEntity.Schema,
        'type': 'array'
      },
      'instance': {
        'description': 'URI reference identifying this specific occurrence.',
        'type': 'string'
      },
      'retryable': {
        'description': 'Extension: whether the failed operation may succeed on retry.',
        'type': 'boolean'
      },
      'stack': {
        'description': 'Extension: stack trace of the head error. Omitted for cause nodes.',
        'type': 'string'
      },
      'status': {
        'description': 'HTTP status code generated by the origin server for this occurrence.',
        'maximum': PROBLEM_STATUS_MAXIMUM,
        'minimum': PROBLEM_STATUS_MINIMUM,
        'type': 'number'
      },
      'timestamp': {
        'description': 'Extension: Unix millisecond timestamp at construction.',
        'type': 'number'
      },
      'title': {
        'description': 'Short, human-readable summary of the problem TYPE. Stable across occurrences.',
        'type': 'string'
      },
      'type': {
        'description': `URI reference identifying the problem type. This is the discriminant. An absent type means '${PROBLEM_TYPE_BLANK}' per RFC 9457 4.2.1; it is not defaulted into the schema, because a member with a default is no longer optional and 3.1 makes every member optional.`,
        'type': 'string'
      }
    },
    'title': 'ProblemDetails',
    'type': 'object'
  } as const satisfies JSONSchema;

  export type Type = FromSchema<typeof Schema>;

  export const validate = EntityCompiler.compile<Type>(Schema);
  export const intake = EntityCompiler.compileIntake<Type>(Schema);
  export const create = EntityCompiler.compileCreate<Type>(Schema);
}
