import type { FromSchema, JSONSchema } from 'json-schema-to-ts';

import { Predicates } from '@studnicky/types';

import type { EntityCreateFunctionInterface } from '../interfaces/EntityCreateFunctionInterface.js';
import type { EntityIntakeFunctionInterface } from '../interfaces/EntityIntakeFunctionInterface.js';
import type { EntityValidateFunctionInterface } from '../interfaces/EntityValidateFunctionInterface.js';

import {
  PROBLEM_STATUS_MAXIMUM,
  PROBLEM_STATUS_MINIMUM,
  PROBLEM_TYPE_BLANK
} from '../constants/ProblemConstants.js';
import { RuntimeError } from '../errors/RuntimeError.js';
import { CauseNodeEntity } from './CauseNodeEntity.js';
import { ValidationViolationEntity } from './ValidationViolationEntity.js';

/**
 * RFC 9457 Problem Details — the canonical serialized form of every error in this workspace.
 *
 * Two RFC requirements drive this shape and are easy to get wrong:
 *
 * 1. §3.1 — EVERY member is optional, and `type` defaults to `about:blank`. A conformant
 *    producer may emit `{}`. Requiring members would reject valid Problem Details.
 * 2. §3.2 — a problem type definition MAY extend the object, and consumers MUST ignore
 *    members they do not recognise. The object is therefore open, never sealed.
 *
 * The members below `instance` are this workspace's extension members. They are declared
 * rather than left to the open bag so they carry real types, while `additionalProperties`
 * stays true so a foreign extension still validates.
 */
export namespace ProblemDetailsEntity {
  export const Schema = {
    '$id': 'https://studnicky.github.io/substrate/schemas/ProblemDetails',
    '$schema': 'https://json-schema.org/draft/2020-12/schema',
    'additionalProperties': true,
    'properties': {
      'causes': {
        'description': 'Extension: bounded, cycle-safe projection of the cause chain, nearest first.',
        'items': CauseNodeEntity.Schema,
        'type': 'array'
      },
      'code': {
        'description': 'Extension: registered dotted error code, e.g. `errors.validationFailed`.',
        'type': 'string'
      },
      'context': {
        'description': 'Extension: structured metadata captured at construction.',
        'type': 'object'
      },
      'correlationId': {
        'description': 'Extension: correlation ID for distributed tracing.',
        'type': 'string'
      },
      'detail': {
        'description': 'Human-readable explanation specific to THIS occurrence of the problem.',
        'type': 'string'
      },

      'errors': {
        'description': 'Extension: individual validation violations behind this problem.',
        'items': ValidationViolationEntity.Schema,
        'type': 'array'
      },
      'instance': {
        'description': 'URI reference identifying this specific occurrence.',
        'type': 'string'
      },
      'retryable': {
        'description': 'Extension: whether the failed operation may succeed on retry.',
        'type': 'boolean'
      },
      'stack': {
        'description': 'Extension: stack trace of the head error. Omitted for cause nodes.',
        'type': 'string'
      },
      'status': {
        'description': 'HTTP status code generated by the origin server for this occurrence.',
        'maximum': PROBLEM_STATUS_MAXIMUM,
        'minimum': PROBLEM_STATUS_MINIMUM,
        'type': 'number'
      },
      'timestamp': {
        'description': 'Extension: Unix millisecond timestamp at construction.',
        'type': 'number'
      },
      'title': {
        'description': 'Short, human-readable summary of the problem TYPE. Stable across occurrences.',
        'type': 'string'
      },
      'type': {
        'description': `URI reference identifying the problem type. This is the discriminant. An absent type means '${PROBLEM_TYPE_BLANK}' per RFC 9457 4.2.1; it is not defaulted into the schema, because a member with a default is no longer optional and 3.1 makes every member optional.`,
        'type': 'string'
      }
    },
    'title': 'ProblemDetails',
    'type': 'object'
  } as const satisfies JSONSchema;

  export type Type = FromSchema<typeof Schema>;

  /**
   * Structural validator. Hand-written (not `SchemaValidator.compile`) because this
   * package is a dependency of `@studnicky/json`; depending on it here would form a
   * circular workspace reference.
   *
   * Every member is optional, so this checks the type of each member that IS present and
   * accepts unrecognised members untouched, per §3.1 and §3.2.
   */
  export const validate: EntityValidateFunctionInterface<Type> = (candidate): candidate is Type => {
    if (!Predicates.isObject(candidate)) { return false; }

    const strings = ['code', 'correlationId', 'detail', 'instance', 'stack', 'title', 'type'];
    for (let index = 0; index < strings.length; index += 1) {
      const key = strings[index] ?? '';
      const value: unknown = Reflect.get(candidate, key);
      if (value !== undefined && !Predicates.isString(value)) { return false; }
    }

    const status: unknown = candidate.status;
    if (status !== undefined) {
      if (!Predicates.isNumber(status)) { return false; }
      if (status < PROBLEM_STATUS_MINIMUM || status > PROBLEM_STATUS_MAXIMUM) { return false; }
    }

    const timestamp: unknown = candidate.timestamp;
    if (timestamp !== undefined && !Predicates.isNumber(timestamp)) { return false; }

    const retryable: unknown = candidate.retryable;
    if (retryable !== undefined && !Predicates.isBoolean(retryable)) { return false; }

    const context: unknown = candidate.context;
    if (context !== undefined && !Predicates.isObject(context)) { return false; }

    const causes: unknown = candidate.causes;
    if (causes !== undefined) {
      if (!Predicates.isArray(causes)) { return false; }
      const causesValid = causes.every((item) => {
        const itemResult = CauseNodeEntity.validate(item);
        return itemResult;
      });
      if (!causesValid) { return false; }
    }

    const errors: unknown = candidate.errors;
    if (errors === undefined) { return true; }
    if (!Predicates.isArray(errors)) { return false; }

    const result = errors.every((item) => {
      const itemResult = ValidationViolationEntity.validate(item);
      return itemResult;
    });
    return result;
  };

  class Boundary {
    /**
     * Copies the candidate through rather than rebuilding it from known members: RFC 9457 3.2
     * requires extension members to survive, so rebuilding from the declared set would silently
     * drop exactly the data a problem type definition adds.
     */
    public static intake(input: unknown): Type {
      if (!Boundary.isValid(input)) {
        throw RuntimeError.create('ProblemDetailsEntity.intake: candidate does not match the declared schema');
      }
      const result = { ...input };

      return result;
    }

    /** Locally-produced data: every member optional, so an empty problem is a valid problem. */
    public static create(partial: Partial<Type> = {}): Type {
      const result = { ...partial };

      return result;
    }

    private static isValid(candidate: unknown): candidate is Type {
      const result = validate(candidate);

      return result;
    }
  }

  export const intake: EntityIntakeFunctionInterface<Type> = Boundary.intake;
  export const create: EntityCreateFunctionInterface<Type> = Boundary.create;
}
