import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface, SchemaNodeInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

const expectedSchemas = {
  'activeLocksCount': { 'type': 'number' },
  'complete': { 'type': 'boolean' },
  'completeAfterRelease': { 'type': 'boolean' },
  'completed': { 'oneOf': [{ 'type': 'number' }, { 'items': { 'type': 'number' }, 'type': 'array' }] },
  'created': { 'type': 'boolean' },
  'drainOrder': { 'items': { 'type': 'number' }, 'type': 'array' },
  'enableCoalescing': { 'type': 'boolean' },
  'exclusive': { 'type': 'boolean' },
  'externalMutationIgnored': { 'type': 'boolean' },
  'first': { 'type': 'boolean' },
  'hasActiveLocksCount': { 'type': 'boolean' },
  'hasQueuedCount': { 'type': 'boolean' },
  'hasTotalExecuted': { 'type': 'boolean' },
  'independent': { 'type': 'boolean' },
  'locked': { 'type': 'boolean' },
  'lockedAfterClear': { 'type': 'boolean' },
  'lockedAfterRelease': { 'type': 'boolean' },
  'lockedKeys': { 'items': { 'type': 'string' }, 'type': 'array' },
  'maximumQueueSize': { 'type': 'number' },
  'observersNotified': { 'type': 'number' },
  'queuedCount': { 'type': 'number' },
  'queuedCountExcluded': { 'type': 'boolean' },
  'queuedRejected': { 'type': 'number' },
  'queueSize': { 'oneOf': [{ 'type': 'number' }, { 'items': { 'type': 'number' }, 'type': 'array' }] },
  'queueSizeAfterClear': { 'type': 'number' },
  'queueSizeAfterRelease': { 'type': 'number' },
  'queueSizeAfterTimeout': { 'type': 'number' },
  'rejected': { 'type': 'boolean' },
  'rejects': { 'type': 'number' },
  'released': { 'type': 'boolean' },
  'releaseOrder': { 'items': { 'type': 'number' }, 'type': 'array' },
  'releaseWorks': { 'type': 'boolean' },
  'resolvedImmediately': { 'type': 'boolean' },
  'result': { 'oneOf': [{ 'type': 'string' }, { 'type': 'number' }] },
  'results': { 'items': { 'type': 'string' }, 'type': 'array' },
  'runExclusive': { 'type': 'string' },
  'sameReference': { 'type': 'boolean' },
  'sameValue': { 'type': 'boolean' },
  'second': { 'type': 'boolean' },
  'size': { 'type': 'number' },
  'sizeAfterClear': { 'type': 'number' },
  'throws': { 'type': 'boolean' },
  'timeout': { 'type': 'number' },
  'totalExecuted': { 'type': 'number' },
  'waitedForAll': { 'type': 'boolean' },
  'waitedForQueue': { 'type': 'boolean' },
  'waitedForRelease': { 'type': 'boolean' }
} as const;

const inputSchemas = {
  'batch': {
    'additionalProperties': false,
    'properties': {
      'acquireCount': { 'type': 'number' },
      'observerCount': { 'type': 'number' },
      'operationCount': { 'type': 'number' },
      'overflowCount': { 'type': 'number' },
      'queuedCount': { 'type': 'number' },
      'queuedPerKey': { 'additionalProperties': { 'type': 'number' }, 'properties': {}, 'required': [], 'type': 'object' }
    },
    'required': [],
    'type': 'object'
  },
  'delayMs': { 'type': 'number' },
  'delaysMs': { 'items': { 'type': 'number' }, 'type': 'array' },
  'errorMessage': { 'type': 'string' },
  'key': {},
  'keys': { 'items': { 'type': 'string' }, 'type': 'array' },
  'mutex': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' },
  'operations': { 'items': { 'type': 'string' }, 'type': 'array' },
  'result': { 'type': 'string' },
  'value': { 'oneOf': [{ 'type': 'string' }, { 'type': 'number' }] }
} as const;

const expectedNodes = {
  'activeLocksCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'complete': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'completeAfterRelease': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'completed': SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined)]),
  'created': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'drainOrder': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined),
  'enableCoalescing': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'exclusive': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'externalMutationIgnored': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'first': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'hasActiveLocksCount': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'hasQueuedCount': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'hasTotalExecuted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'independent': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'locked': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'lockedAfterClear': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'lockedAfterRelease': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'lockedKeys': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined),
  'maximumQueueSize': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'observersNotified': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'queuedCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'queuedCountExcluded': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'queuedRejected': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'queueSize': SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined)]),
  'queueSizeAfterClear': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'queueSizeAfterRelease': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'queueSizeAfterTimeout': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'rejected': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'rejects': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'released': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'releaseOrder': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined),
  'releaseWorks': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'resolvedImmediately': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'result': SchemaNode.defineOneOf({}, [SchemaNode.defineString({ 'type': 'string' } as const), SchemaNode.defineNumber({ 'type': 'number' } as const)]),
  'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined),
  'runExclusive': SchemaNode.defineString({ 'type': 'string' } as const),
  'sameReference': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'sameValue': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'second': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'size': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'sizeAfterClear': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'throws': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'timeout': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'totalExecuted': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'waitedForAll': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'waitedForQueue': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
  'waitedForRelease': SchemaNode.defineBoolean({ 'type': 'boolean' } as const)
} as const;

const inputNodes = {
  'batch': SchemaNode.defineObject({ 'type': 'object' } as const, {
    'acquireCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
    'observerCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
    'operationCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
    'overflowCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
    'queuedCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
    'queuedPerKey': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': SchemaNode.defineNumber({ 'type': 'number' } as const), 'patternProperties': {} })
  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }),
  'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const),
  'delaysMs': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined),
  'errorMessage': SchemaNode.defineString({ 'type': 'string' } as const),
  'key': SchemaNode.defineUnknown({} as const),
  'keys': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined),
  'mutex': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }),
  'operations': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined),
  'result': SchemaNode.defineString({ 'type': 'string' } as const),
  'value': SchemaNode.defineOneOf({}, [SchemaNode.defineString({ 'type': 'string' } as const), SchemaNode.defineNumber({ 'type': 'number' } as const)])
} as const;

/** Builds one branch per `shape`: the shared `{ description, expected, input, name, shape }` envelope around a shape-specific `input` and `expected`. */
class MutexCoreBranches {
  static scenarioSchema<
    const TShape extends string,
    TInputSchema extends Record<string, unknown>,
    TExpectedSchema extends Record<string, unknown>
  >(shape: TShape, inputSchema: TInputSchema, expectedSchema: TExpectedSchema) {
    const result = {
      'additionalProperties': false,
      'properties': {
        'description': { 'minLength': 1, 'type': 'string' },
        'expected': expectedSchema,
        'input': inputSchema,
        'name': { 'minLength': 1, 'type': 'string' },
        'shape': { 'const': shape }
      },
      'required': ['description', 'expected', 'input', 'name', 'shape'],
      'type': 'object'
    } as const;
    return result;
  }

  static scenarioNode<
    const TShape extends string,
    TInputNode extends SchemaNodeInterface<unknown, unknown>,
    TExpectedNode extends SchemaNodeInterface<unknown, unknown>
  >(shape: TShape, inputNode: TInputNode, expectedNode: TExpectedNode) {
    const result = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'expected': expectedNode,
      'input': inputNode,
      'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'shape': SchemaNode.defineConst({}, shape)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
    return result;
  }
}

/**
 * The scenario case shapes `mutex-core.loop.spec.ts` exercises across 71 core Mutex behaviors, one branch per `shape`.
 * Each branch declares exactly the `input` and `expected` fields its shape uses. `mutex` allows unknown properties
 * on purpose: `config-unknown-key` feeds an unrecognized config field through to prove `Mutex.create` rejects it.
 */
export namespace MutexCoreScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      MutexCoreBranches.scenarioSchema('config-defaults', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'enableCoalescing': expectedSchemas.enableCoalescing, 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['enableCoalescing', 'maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-empty', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-no-limits', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key, 'mutex': inputSchemas.mutex, 'result': inputSchemas.result }, 'required': ['key', 'mutex', 'result'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'runExclusive': expectedSchemas.runExclusive }, 'required': ['runExclusive'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-full', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-partial-maxQueue-5', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-partial-maxQueue-50', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-partial-timeout', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-enable-coalescing', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'enableCoalescing': expectedSchemas.enableCoalescing }, 'required': ['enableCoalescing'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-invalid-maxQueue-negative', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'throws': expectedSchemas.throws }, 'required': ['throws'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-invalid-timeout-negative', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'throws': expectedSchemas.throws }, 'required': ['throws'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-invalid-maxQueue-float', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'throws': expectedSchemas.throws }, 'required': ['throws'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-invalid-timeout-float', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'throws': expectedSchemas.throws }, 'required': ['throws'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-invalid-enableCoalescing', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'throws': expectedSchemas.throws }, 'required': ['throws'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-unknown-key', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'throws': expectedSchemas.throws }, 'required': ['throws'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('validateConfig-valid', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('validateConfig-invalid', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'throws': expectedSchemas.throws }, 'required': ['throws'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-return-copy', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'sameReference': expectedSchemas.sameReference, 'sameValue': expectedSchemas.sameValue }, 'required': ['sameReference', 'sameValue'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('config-external-modification', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'externalMutationIgnored': expectedSchemas.externalMutationIgnored, 'maximumQueueSize': expectedSchemas.maximumQueueSize }, 'required': ['externalMutationIgnored', 'maximumQueueSize'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('create-no-config', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'created': expectedSchemas.created }, 'required': ['created'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('create-partial-config', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'created': expectedSchemas.created, 'maximumQueueSize': expectedSchemas.maximumQueueSize }, 'required': ['created', 'maximumQueueSize'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('create-functional', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'locked': expectedSchemas.locked, 'releaseWorks': expectedSchemas.releaseWorks }, 'required': ['locked', 'releaseWorks'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('create-string-key', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'result': expectedSchemas.result }, 'required': ['result'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('create-number-key', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'result': expectedSchemas.result }, 'required': ['result'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('create-composite-key', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'result': expectedSchemas.result }, 'required': ['result'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('acquire-disposable', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('acquire-release', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'locked': expectedSchemas.locked, 'released': expectedSchemas.released }, 'required': ['locked', 'released'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('sequential-acquisitions', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key }, 'required': ['batch', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'locked': expectedSchemas.locked, 'releaseOrder': expectedSchemas.releaseOrder }, 'required': ['locked', 'releaseOrder'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('different-keys', { 'additionalProperties': false, 'properties': { 'keys': inputSchemas.keys }, 'required': ['keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'independent': expectedSchemas.independent, 'lockedKeys': expectedSchemas.lockedKeys }, 'required': ['independent', 'lockedKeys'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('sync-return-string', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key, 'value': inputSchemas.value }, 'required': ['key', 'value'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'result': expectedSchemas.result }, 'required': ['result'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('sync-return-number', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key, 'value': inputSchemas.value }, 'required': ['key', 'value'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'result': expectedSchemas.result }, 'required': ['result'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('result-validator-rejects', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'rejected': expectedSchemas.rejected }, 'required': ['rejected'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('async-exclusive', { 'additionalProperties': false, 'properties': { 'delayMs': inputSchemas.delayMs, 'key': inputSchemas.key }, 'required': ['delayMs', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'exclusive': expectedSchemas.exclusive }, 'required': ['exclusive'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('async-return-value', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key, 'result': inputSchemas.result }, 'required': ['key', 'result'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'result': expectedSchemas.result }, 'required': ['result'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('releases-on-throw', { 'additionalProperties': false, 'properties': { 'errorMessage': inputSchemas.errorMessage, 'key': inputSchemas.key }, 'required': ['errorMessage', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'released': expectedSchemas.released, 'throws': expectedSchemas.throws }, 'required': ['released', 'throws'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('multiple-operations', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key, 'operations': inputSchemas.operations }, 'required': ['batch', 'key', 'operations'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'results': expectedSchemas.results, 'totalExecuted': expectedSchemas.totalExecuted }, 'required': ['results', 'totalExecuted'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('burst-timeout-drains-queue', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key, 'mutex': inputSchemas.mutex }, 'required': ['batch', 'key', 'mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'drainOrder': expectedSchemas.drainOrder, 'rejects': expectedSchemas.rejects }, 'required': ['drainOrder', 'rejects'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('queued-timeout-unlinks-middle-node', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key, 'mutex': inputSchemas.mutex }, 'required': ['batch', 'key', 'mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'queueSizeAfterRelease': expectedSchemas.queueSizeAfterRelease, 'queueSizeAfterTimeout': expectedSchemas.queueSizeAfterTimeout }, 'required': ['queueSizeAfterRelease', 'queueSizeAfterTimeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isLocked-initial-false', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'locked': expectedSchemas.locked }, 'required': ['locked'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('queue-size-exceeded', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key, 'mutex': inputSchemas.mutex }, 'required': ['batch', 'key', 'mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isLocked-true', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'locked': expectedSchemas.locked }, 'required': ['locked'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isLocked-after-release', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'lockedAfterRelease': expectedSchemas.lockedAfterRelease }, 'required': ['lockedAfterRelease'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isLocked-multiple-keys', { 'additionalProperties': false, 'properties': { 'keys': inputSchemas.keys }, 'required': ['keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'first': expectedSchemas.first, 'second': expectedSchemas.second }, 'required': ['first', 'second'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('queueSize-initial-zero', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'queueSize': expectedSchemas.queueSize }, 'required': ['queueSize'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('queueSize-held-empty', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'queueSize': expectedSchemas.queueSize }, 'required': ['queueSize'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('queueSize-tracks-queued', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key }, 'required': ['batch', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'queueSize': expectedSchemas.queueSize }, 'required': ['queueSize'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('queueSize-decrements', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key, 'mutex': inputSchemas.mutex }, 'required': ['batch', 'key', 'mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'queueSize': expectedSchemas.queueSize }, 'required': ['queueSize'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('size-initial-zero', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'size': expectedSchemas.size }, 'required': ['size'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('size-active-locks', { 'additionalProperties': false, 'properties': { 'keys': inputSchemas.keys }, 'required': ['keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'size': expectedSchemas.size }, 'required': ['size'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('size-no-queued', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key }, 'required': ['batch', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'queuedCountExcluded': expectedSchemas.queuedCountExcluded, 'size': expectedSchemas.size }, 'required': ['queuedCountExcluded', 'size'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('clear-clears-all', { 'additionalProperties': false, 'properties': { 'keys': inputSchemas.keys }, 'required': ['keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'sizeAfterClear': expectedSchemas.sizeAfterClear }, 'required': ['sizeAfterClear'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('clear-empty', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'sizeAfterClear': expectedSchemas.sizeAfterClear }, 'required': ['sizeAfterClear'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('clear-rejects-queued-acquisitions', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key, 'mutex': inputSchemas.mutex }, 'required': ['batch', 'key', 'mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'lockedAfterClear': expectedSchemas.lockedAfterClear, 'queuedRejected': expectedSchemas.queuedRejected, 'queueSizeAfterClear': expectedSchemas.queueSizeAfterClear }, 'required': ['lockedAfterClear', 'queuedRejected', 'queueSizeAfterClear'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('getConfig-current', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('getConfig-default', { 'additionalProperties': false, 'properties': { 'mutex': inputSchemas.mutex }, 'required': ['mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'timeout': expectedSchemas.timeout }, 'required': ['maximumQueueSize', 'timeout'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('stats-initial', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key, 'mutex': inputSchemas.mutex }, 'required': ['key', 'mutex'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'activeLocksCount': expectedSchemas.activeLocksCount, 'maximumQueueSize': expectedSchemas.maximumQueueSize, 'queuedCount': expectedSchemas.queuedCount, 'timeout': expectedSchemas.timeout, 'totalExecuted': expectedSchemas.totalExecuted }, 'required': ['activeLocksCount', 'maximumQueueSize', 'queuedCount', 'timeout', 'totalExecuted'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('stats-api-shape', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'hasActiveLocksCount': expectedSchemas.hasActiveLocksCount, 'hasQueuedCount': expectedSchemas.hasQueuedCount, 'hasTotalExecuted': expectedSchemas.hasTotalExecuted }, 'required': ['hasActiveLocksCount', 'hasQueuedCount', 'hasTotalExecuted'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('stats-active-locks', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'activeLocksCount': expectedSchemas.activeLocksCount }, 'required': ['activeLocksCount'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('stats-multiple-active', { 'additionalProperties': false, 'properties': { 'keys': inputSchemas.keys }, 'required': ['keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'activeLocksCount': expectedSchemas.activeLocksCount }, 'required': ['activeLocksCount'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('stats-queued', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key }, 'required': ['batch', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'queuedCount': expectedSchemas.queuedCount }, 'required': ['queuedCount'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('stats-queued-multi-key', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'keys': inputSchemas.keys }, 'required': ['batch', 'keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'activeLocksCount': expectedSchemas.activeLocksCount, 'queuedCount': expectedSchemas.queuedCount, 'totalExecuted': expectedSchemas.totalExecuted }, 'required': ['activeLocksCount', 'queuedCount', 'totalExecuted'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('stats-total-executed', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'keys': inputSchemas.keys }, 'required': ['batch', 'keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'activeLocksCount': expectedSchemas.activeLocksCount, 'queuedCount': expectedSchemas.queuedCount, 'totalExecuted': expectedSchemas.totalExecuted }, 'required': ['activeLocksCount', 'queuedCount', 'totalExecuted'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isComplete-initial-true', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'complete': expectedSchemas.complete }, 'required': ['complete'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isComplete-held-false', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'complete': expectedSchemas.complete }, 'required': ['complete'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isComplete-after-release-true', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'completeAfterRelease': expectedSchemas.completeAfterRelease }, 'required': ['completeAfterRelease'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isComplete-queued-false', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key }, 'required': ['batch', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'complete': expectedSchemas.complete }, 'required': ['complete'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('isComplete-multi-active-false', { 'additionalProperties': false, 'properties': { 'keys': inputSchemas.keys }, 'required': ['keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'complete': expectedSchemas.complete }, 'required': ['complete'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('completeQueue-immediate', { 'additionalProperties': false, 'properties': { 'key': inputSchemas.key }, 'required': ['key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'resolvedImmediately': expectedSchemas.resolvedImmediately }, 'required': ['resolvedImmediately'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('completeQueue-waits-active', { 'additionalProperties': false, 'properties': { 'delayMs': inputSchemas.delayMs, 'key': inputSchemas.key }, 'required': ['delayMs', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'waitedForRelease': expectedSchemas.waitedForRelease }, 'required': ['waitedForRelease'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('completeQueue-waits-queued', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'delayMs': inputSchemas.delayMs, 'key': inputSchemas.key }, 'required': ['batch', 'delayMs', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'completed': expectedSchemas.completed, 'waitedForQueue': expectedSchemas.waitedForQueue }, 'required': ['completed', 'waitedForQueue'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('completeQueue-waits-multi-key', { 'additionalProperties': false, 'properties': { 'delaysMs': inputSchemas.delaysMs, 'keys': inputSchemas.keys }, 'required': ['delaysMs', 'keys'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'completed': expectedSchemas.completed, 'waitedForAll': expectedSchemas.waitedForAll }, 'required': ['completed', 'waitedForAll'], 'type': 'object' } as const),
      MutexCoreBranches.scenarioSchema('completeQueue-multiple-observers', { 'additionalProperties': false, 'properties': { 'batch': inputSchemas.batch, 'key': inputSchemas.key }, 'required': ['batch', 'key'], 'type': 'object' } as const, { 'additionalProperties': false, 'properties': { 'complete': expectedSchemas.complete, 'observersNotified': expectedSchemas.observersNotified }, 'required': ['complete', 'observersNotified'], 'type': 'object' } as const)
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    MutexCoreBranches.scenarioNode('config-defaults', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'enableCoalescing': expectedNodes.enableCoalescing, 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['enableCoalescing', 'maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-empty', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-no-limits', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key, 'mutex': inputNodes.mutex, 'result': inputNodes.result }, ['key', 'mutex', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'runExclusive': expectedNodes.runExclusive }, ['runExclusive'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-full', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-partial-maxQueue-5', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-partial-maxQueue-50', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-partial-timeout', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-enable-coalescing', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'enableCoalescing': expectedNodes.enableCoalescing }, ['enableCoalescing'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-invalid-maxQueue-negative', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': expectedNodes.throws }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-invalid-timeout-negative', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': expectedNodes.throws }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-invalid-maxQueue-float', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': expectedNodes.throws }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-invalid-timeout-float', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': expectedNodes.throws }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-invalid-enableCoalescing', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': expectedNodes.throws }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-unknown-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': expectedNodes.throws }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('validateConfig-valid', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('validateConfig-invalid', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': expectedNodes.throws }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-return-copy', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'sameReference': expectedNodes.sameReference, 'sameValue': expectedNodes.sameValue }, ['sameReference', 'sameValue'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('config-external-modification', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'externalMutationIgnored': expectedNodes.externalMutationIgnored, 'maximumQueueSize': expectedNodes.maximumQueueSize }, ['externalMutationIgnored', 'maximumQueueSize'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('create-no-config', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'created': expectedNodes.created }, ['created'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('create-partial-config', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'created': expectedNodes.created, 'maximumQueueSize': expectedNodes.maximumQueueSize }, ['created', 'maximumQueueSize'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('create-functional', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'locked': expectedNodes.locked, 'releaseWorks': expectedNodes.releaseWorks }, ['locked', 'releaseWorks'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('create-string-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': expectedNodes.result }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('create-number-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': expectedNodes.result }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('create-composite-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': expectedNodes.result }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('acquire-disposable', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('acquire-release', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'locked': expectedNodes.locked, 'released': expectedNodes.released }, ['locked', 'released'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('sequential-acquisitions', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key }, ['batch', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'locked': expectedNodes.locked, 'releaseOrder': expectedNodes.releaseOrder }, ['locked', 'releaseOrder'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('different-keys', SchemaNode.defineObject({ 'type': 'object' } as const, { 'keys': inputNodes.keys }, ['keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'independent': expectedNodes.independent, 'lockedKeys': expectedNodes.lockedKeys }, ['independent', 'lockedKeys'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('sync-return-string', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key, 'value': inputNodes.value }, ['key', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': expectedNodes.result }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('sync-return-number', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key, 'value': inputNodes.value }, ['key', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': expectedNodes.result }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('result-validator-rejects', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'rejected': expectedNodes.rejected }, ['rejected'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('async-exclusive', SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': inputNodes.delayMs, 'key': inputNodes.key }, ['delayMs', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'exclusive': expectedNodes.exclusive }, ['exclusive'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('async-return-value', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key, 'result': inputNodes.result }, ['key', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': expectedNodes.result }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('releases-on-throw', SchemaNode.defineObject({ 'type': 'object' } as const, { 'errorMessage': inputNodes.errorMessage, 'key': inputNodes.key }, ['errorMessage', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'released': expectedNodes.released, 'throws': expectedNodes.throws }, ['released', 'throws'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('multiple-operations', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key, 'operations': inputNodes.operations }, ['batch', 'key', 'operations'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'results': expectedNodes.results, 'totalExecuted': expectedNodes.totalExecuted }, ['results', 'totalExecuted'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('burst-timeout-drains-queue', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key, 'mutex': inputNodes.mutex }, ['batch', 'key', 'mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'drainOrder': expectedNodes.drainOrder, 'rejects': expectedNodes.rejects }, ['drainOrder', 'rejects'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('queued-timeout-unlinks-middle-node', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key, 'mutex': inputNodes.mutex }, ['batch', 'key', 'mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'queueSizeAfterRelease': expectedNodes.queueSizeAfterRelease, 'queueSizeAfterTimeout': expectedNodes.queueSizeAfterTimeout }, ['queueSizeAfterRelease', 'queueSizeAfterTimeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isLocked-initial-false', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'locked': expectedNodes.locked }, ['locked'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('queue-size-exceeded', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key, 'mutex': inputNodes.mutex }, ['batch', 'key', 'mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isLocked-true', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'locked': expectedNodes.locked }, ['locked'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isLocked-after-release', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'lockedAfterRelease': expectedNodes.lockedAfterRelease }, ['lockedAfterRelease'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isLocked-multiple-keys', SchemaNode.defineObject({ 'type': 'object' } as const, { 'keys': inputNodes.keys }, ['keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'first': expectedNodes.first, 'second': expectedNodes.second }, ['first', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('queueSize-initial-zero', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'queueSize': expectedNodes.queueSize }, ['queueSize'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('queueSize-held-empty', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'queueSize': expectedNodes.queueSize }, ['queueSize'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('queueSize-tracks-queued', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key }, ['batch', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'queueSize': expectedNodes.queueSize }, ['queueSize'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('queueSize-decrements', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key, 'mutex': inputNodes.mutex }, ['batch', 'key', 'mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'queueSize': expectedNodes.queueSize }, ['queueSize'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('size-initial-zero', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'size': expectedNodes.size }, ['size'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('size-active-locks', SchemaNode.defineObject({ 'type': 'object' } as const, { 'keys': inputNodes.keys }, ['keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'size': expectedNodes.size }, ['size'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('size-no-queued', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key }, ['batch', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'queuedCountExcluded': expectedNodes.queuedCountExcluded, 'size': expectedNodes.size }, ['queuedCountExcluded', 'size'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('clear-clears-all', SchemaNode.defineObject({ 'type': 'object' } as const, { 'keys': inputNodes.keys }, ['keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'sizeAfterClear': expectedNodes.sizeAfterClear }, ['sizeAfterClear'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('clear-empty', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'sizeAfterClear': expectedNodes.sizeAfterClear }, ['sizeAfterClear'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('clear-rejects-queued-acquisitions', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key, 'mutex': inputNodes.mutex }, ['batch', 'key', 'mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'lockedAfterClear': expectedNodes.lockedAfterClear, 'queuedRejected': expectedNodes.queuedRejected, 'queueSizeAfterClear': expectedNodes.queueSizeAfterClear }, ['lockedAfterClear', 'queuedRejected', 'queueSizeAfterClear'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('getConfig-current', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('getConfig-default', SchemaNode.defineObject({ 'type': 'object' } as const, { 'mutex': inputNodes.mutex }, ['mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumQueueSize': expectedNodes.maximumQueueSize, 'timeout': expectedNodes.timeout }, ['maximumQueueSize', 'timeout'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('stats-initial', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key, 'mutex': inputNodes.mutex }, ['key', 'mutex'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'activeLocksCount': expectedNodes.activeLocksCount, 'maximumQueueSize': expectedNodes.maximumQueueSize, 'queuedCount': expectedNodes.queuedCount, 'timeout': expectedNodes.timeout, 'totalExecuted': expectedNodes.totalExecuted }, ['activeLocksCount', 'maximumQueueSize', 'queuedCount', 'timeout', 'totalExecuted'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('stats-api-shape', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'hasActiveLocksCount': expectedNodes.hasActiveLocksCount, 'hasQueuedCount': expectedNodes.hasQueuedCount, 'hasTotalExecuted': expectedNodes.hasTotalExecuted }, ['hasActiveLocksCount', 'hasQueuedCount', 'hasTotalExecuted'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('stats-active-locks', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'activeLocksCount': expectedNodes.activeLocksCount }, ['activeLocksCount'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('stats-multiple-active', SchemaNode.defineObject({ 'type': 'object' } as const, { 'keys': inputNodes.keys }, ['keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'activeLocksCount': expectedNodes.activeLocksCount }, ['activeLocksCount'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('stats-queued', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key }, ['batch', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'queuedCount': expectedNodes.queuedCount }, ['queuedCount'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('stats-queued-multi-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'keys': inputNodes.keys }, ['batch', 'keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'activeLocksCount': expectedNodes.activeLocksCount, 'queuedCount': expectedNodes.queuedCount, 'totalExecuted': expectedNodes.totalExecuted }, ['activeLocksCount', 'queuedCount', 'totalExecuted'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('stats-total-executed', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'keys': inputNodes.keys }, ['batch', 'keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'activeLocksCount': expectedNodes.activeLocksCount, 'queuedCount': expectedNodes.queuedCount, 'totalExecuted': expectedNodes.totalExecuted }, ['activeLocksCount', 'queuedCount', 'totalExecuted'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isComplete-initial-true', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'complete': expectedNodes.complete }, ['complete'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isComplete-held-false', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'complete': expectedNodes.complete }, ['complete'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isComplete-after-release-true', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'completeAfterRelease': expectedNodes.completeAfterRelease }, ['completeAfterRelease'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isComplete-queued-false', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key }, ['batch', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'complete': expectedNodes.complete }, ['complete'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('isComplete-multi-active-false', SchemaNode.defineObject({ 'type': 'object' } as const, { 'keys': inputNodes.keys }, ['keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'complete': expectedNodes.complete }, ['complete'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('completeQueue-immediate', SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': inputNodes.key }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'resolvedImmediately': expectedNodes.resolvedImmediately }, ['resolvedImmediately'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('completeQueue-waits-active', SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': inputNodes.delayMs, 'key': inputNodes.key }, ['delayMs', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'waitedForRelease': expectedNodes.waitedForRelease }, ['waitedForRelease'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('completeQueue-waits-queued', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'delayMs': inputNodes.delayMs, 'key': inputNodes.key }, ['batch', 'delayMs', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'completed': expectedNodes.completed, 'waitedForQueue': expectedNodes.waitedForQueue }, ['completed', 'waitedForQueue'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('completeQueue-waits-multi-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'delaysMs': inputNodes.delaysMs, 'keys': inputNodes.keys }, ['delaysMs', 'keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'completed': expectedNodes.completed, 'waitedForAll': expectedNodes.waitedForAll }, ['completed', 'waitedForAll'] as const, { 'additionalProperties': false, 'patternProperties': {} })),
    MutexCoreBranches.scenarioNode('completeQueue-multiple-observers', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': inputNodes.batch, 'key': inputNodes.key }, ['batch', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'complete': expectedNodes.complete, 'observersNotified': expectedNodes.observersNotified }, ['complete', 'observersNotified'] as const, { 'additionalProperties': false, 'patternProperties': {} }))
  ] as const);

  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
