import type { NodeStaticType } from '@studnicky/entity/types';

import { SchemaNode } from '@studnicky/entity/types';

const SCENARIO_SHAPES = [
  'acquire-disposable',
  'acquire-release',
  'async-exclusive',
  'async-return-value',
  'burst-timeout-drains-queue',
  'clear-clears-all',
  'clear-empty',
  'clear-rejects-queued-acquisitions',
  'completeQueue-immediate',
  'completeQueue-multiple-observers',
  'completeQueue-waits-active',
  'completeQueue-waits-multi-key',
  'completeQueue-waits-queued',
  'config-defaults',
  'config-empty',
  'config-enable-coalescing',
  'config-external-modification',
  'config-full',
  'config-invalid-enableCoalescing',
  'config-invalid-maxQueue-float',
  'config-invalid-maxQueue-negative',
  'config-invalid-timeout-float',
  'config-invalid-timeout-negative',
  'config-no-limits',
  'config-partial-maxQueue-5',
  'config-partial-maxQueue-50',
  'config-partial-timeout',
  'config-return-copy',
  'config-unknown-key',
  'create-composite-key',
  'create-functional',
  'create-no-config',
  'create-number-key',
  'create-partial-config',
  'create-string-key',
  'different-keys',
  'getConfig-current',
  'getConfig-default',
  'isComplete-after-release-true',
  'isComplete-held-false',
  'isComplete-initial-true',
  'isComplete-multi-active-false',
  'isComplete-queued-false',
  'isLocked-after-release',
  'isLocked-initial-false',
  'isLocked-multiple-keys',
  'isLocked-true',
  'multiple-operations',
  'queue-size-exceeded',
  'queueSize-decrements',
  'queueSize-held-empty',
  'queueSize-initial-zero',
  'queueSize-tracks-queued',
  'queued-timeout-unlinks-middle-node',
  'releases-on-throw',
  'result-validator-rejects',
  'sequential-acquisitions',
  'size-active-locks',
  'size-initial-zero',
  'size-no-queued',
  'stats-active-locks',
  'stats-api-shape',
  'stats-initial',
  'stats-multiple-active',
  'stats-queued',
  'stats-queued-multi-key',
  'stats-total-executed',
  'sync-return-number',
  'sync-return-string',
  'validateConfig-invalid',
  'validateConfig-valid'
] as const;

/**
 * The scenario case shape `mutex-core.loop.spec.ts` exercises across 71 core Mutex behaviors.
 * Every field is optional — the spec's own `read*` helpers (readNumber, readString,
 * readStringArray, readBatchCount, readQueuedPerKey, ...) do the per-shape narrowing and throw a
 * clear error when a shape's scenario is missing a field it actually needs, exactly as they did
 * before this conversion. `mutex` allows unknown properties on purpose: `config-unknown-key`
 * feeds an unrecognized config field through to prove `Mutex.create` rejects it.
 */
export namespace MutexCoreScenarioCaseEntity {
  export const Schema = {
    'additionalProperties': false,
    'properties': {
      'description': { 'minLength': 1, 'type': 'string' },
      'expected': {
        'additionalProperties': false,
        'properties': {
          'activeLocksCount': { 'type': 'number' },
          'complete': { 'type': 'boolean' },
          'completeAfterRelease': { 'type': 'boolean' },
          'completed': { 'oneOf': [{ 'type': 'number' }, { 'items': { 'type': 'number' }, 'type': 'array' }] },
          'created': { 'type': 'boolean' },
          'drainOrder': { 'items': { 'type': 'number' }, 'type': 'array' },
          'enableCoalescing': { 'type': 'boolean' },
          'exclusive': { 'type': 'boolean' },
          'externalMutationIgnored': { 'type': 'boolean' },
          'first': { 'type': 'boolean' },
          'hasActiveLocksCount': { 'type': 'boolean' },
          'hasQueuedCount': { 'type': 'boolean' },
          'hasTotalExecuted': { 'type': 'boolean' },
          'independent': { 'type': 'boolean' },
          'locked': { 'type': 'boolean' },
          'lockedAfterClear': { 'type': 'boolean' },
          'lockedAfterRelease': { 'type': 'boolean' },
          'lockedKeys': { 'items': { 'type': 'string' }, 'type': 'array' },
          'maximumQueueSize': { 'type': 'number' },
          'observersNotified': { 'type': 'number' },
          'queueSize': { 'oneOf': [{ 'type': 'number' }, { 'items': { 'type': 'number' }, 'type': 'array' }] },
          'queueSizeAfterClear': { 'type': 'number' },
          'queueSizeAfterRelease': { 'type': 'number' },
          'queueSizeAfterTimeout': { 'type': 'number' },
          'queuedCount': { 'type': 'number' },
          'queuedCountExcluded': { 'type': 'boolean' },
          'queuedRejected': { 'type': 'number' },
          'rejected': { 'type': 'boolean' },
          'rejects': { 'type': 'number' },
          'releaseOrder': { 'items': { 'type': 'number' }, 'type': 'array' },
          'releaseWorks': { 'type': 'boolean' },
          'released': { 'type': 'boolean' },
          'resolvedImmediately': { 'type': 'boolean' },
          'result': { 'oneOf': [{ 'type': 'string' }, { 'type': 'number' }] },
          'results': { 'items': { 'type': 'string' }, 'type': 'array' },
          'runExclusive': { 'type': 'string' },
          'sameRef': { 'type': 'boolean' },
          'sameValue': { 'type': 'boolean' },
          'second': { 'type': 'boolean' },
          'size': { 'type': 'number' },
          'sizeAfterClear': { 'type': 'number' },
          'throws': { 'type': 'boolean' },
          'timeout': { 'type': 'number' },
          'totalExecuted': { 'type': 'number' },
          'waitedForAll': { 'type': 'boolean' },
          'waitedForQueue': { 'type': 'boolean' },
          'waitedForRelease': { 'type': 'boolean' }
        },
        'required': [],
        'type': 'object'
      },
      'input': {
        'additionalProperties': false,
        'properties': {
          'batch': {
            'additionalProperties': false,
            'properties': {
              'acquireCount': { 'type': 'number' },
              'observerCount': { 'type': 'number' },
              'operationCount': { 'type': 'number' },
              'overflowCount': { 'type': 'number' },
              'queuedCount': { 'type': 'number' },
              'queuedPerKey': { 'additionalProperties': { 'type': 'number' }, 'properties': {}, 'required': [], 'type': 'object' }
            },
            'required': [],
            'type': 'object'
          },
          'delayMs': { 'type': 'number' },
          'delaysMs': { 'items': { 'type': 'number' }, 'type': 'array' },
          'errorMessage': { 'type': 'string' },
          'key': {},
          'keys': { 'items': { 'type': 'string' }, 'type': 'array' },
          'mutex': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' },
          'operations': { 'items': { 'type': 'string' }, 'type': 'array' },
          'result': { 'type': 'string' },
          'value': { 'oneOf': [{ 'type': 'string' }, { 'type': 'number' }] }
        },
        'required': [],
        'type': 'object'
      },
      'name': { 'minLength': 1, 'type': 'string' },
      'shape': { 'enum': SCENARIO_SHAPES }
    },
    'required': ['description', 'expected', 'input', 'name', 'shape'],
    'type': 'object'
  } as const;

  export const Node = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'expected': SchemaNode.defineObject({ 'type': 'object' } as const, {
          'activeLocksCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'complete': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'completeAfterRelease': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'completed': SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined)]),
          'created': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'drainOrder': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined),
          'enableCoalescing': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'exclusive': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'externalMutationIgnored': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'first': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'hasActiveLocksCount': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'hasQueuedCount': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'hasTotalExecuted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'independent': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'locked': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'lockedAfterClear': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'lockedAfterRelease': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'lockedKeys': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined),
          'maximumQueueSize': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'observersNotified': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'queueSize': SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined)]),
          'queueSizeAfterClear': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'queueSizeAfterRelease': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'queueSizeAfterTimeout': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'queuedCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'queuedCountExcluded': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'queuedRejected': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'rejected': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'rejects': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'releaseOrder': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined),
          'releaseWorks': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'released': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'resolvedImmediately': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'result': SchemaNode.defineOneOf({}, [SchemaNode.defineString({ 'type': 'string' } as const), SchemaNode.defineNumber({ 'type': 'number' } as const)]),
          'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined),
          'runExclusive': SchemaNode.defineString({ 'type': 'string' } as const),
          'sameRef': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'sameValue': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'second': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'size': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'sizeAfterClear': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'throws': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'timeout': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'totalExecuted': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'waitedForAll': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'waitedForQueue': SchemaNode.defineBoolean({ 'type': 'boolean' } as const),
          'waitedForRelease': SchemaNode.defineBoolean({ 'type': 'boolean' } as const)
        }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }),
      'input': SchemaNode.defineObject({ 'type': 'object' } as const, {
          'batch': SchemaNode.defineObject({ 'type': 'object' } as const, {
              'acquireCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
              'observerCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
              'operationCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
              'overflowCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
              'queuedCount': SchemaNode.defineNumber({ 'type': 'number' } as const),
              'queuedPerKey': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': SchemaNode.defineNumber({ 'type': 'number' } as const), 'patternProperties': {} })
            }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }),
          'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const),
          'delaysMs': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined),
          'errorMessage': SchemaNode.defineString({ 'type': 'string' } as const),
          'key': SchemaNode.defineUnknown({} as const),
          'keys': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined),
          'mutex': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }),
          'operations': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined),
          'result': SchemaNode.defineString({ 'type': 'string' } as const),
          'value': SchemaNode.defineOneOf({}, [SchemaNode.defineString({ 'type': 'string' } as const), SchemaNode.defineNumber({ 'type': 'number' } as const)])
        }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }),
      'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'shape': SchemaNode.defineEnum({}, SCENARIO_SHAPES)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
  export type Type = NodeStaticType<typeof Node>;
}
