import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

// create-default-identity
const createDefaultIdentitySchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' } }, 'required': ['event'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'create-default-identity' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const createDefaultIdentityNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'create-default-identity' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// create-empty-machine-id
const createEmptyMachineIdSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' } }, 'required': ['machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'create-empty-machine-id' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const createEmptyMachineIdNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'create-empty-machine-id' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// create-non-integer-mailbox-capacity
const createNonIntegerMailboxCapacitySchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' }, 'mailboxCapacity': { 'type': 'number' } }, 'required': ['machineId', 'mailboxCapacity'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'create-non-integer-mailbox-capacity' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const createNonIntegerMailboxCapacityNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const), 'mailboxCapacity': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['machineId', 'mailboxCapacity'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'create-non-integer-mailbox-capacity' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// create-non-positive-mailbox-capacity
const createNonPositiveMailboxCapacitySchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' }, 'mailboxCapacity': { 'type': 'number' } }, 'required': ['machineId', 'mailboxCapacity'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'create-non-positive-mailbox-capacity' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const createNonPositiveMailboxCapacityNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const), 'mailboxCapacity': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['machineId', 'mailboxCapacity'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'create-non-positive-mailbox-capacity' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// effect-handler-called-after-transition
const effectHandlerCalledAfterTransitionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'logged': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['logged'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'machineId': { 'type': 'string' } }, 'required': ['event', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'effect-handler-called-after-transition' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const effectHandlerCalledAfterTransitionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'logged': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['logged'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'effect-handler-called-after-transition' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// effect-handler-omitted
const effectHandlerOmittedSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'notificationCount': { 'type': 'number' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['notificationCount', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'machineId': { 'type': 'string' } }, 'required': ['event', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'effect-handler-omitted' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const effectHandlerOmittedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'notificationCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['notificationCount', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'effect-handler-omitted' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// get-state-before-start
const getStateBeforeStartSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' } }, 'required': ['machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'get-state-before-start' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const getStateBeforeStartNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'get-state-before-start' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// handler-dispatches-within-send
const handlerDispatchesWithinSendSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'machineId': { 'type': 'string' } }, 'required': ['event', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'handler-dispatches-within-send' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const handlerDispatchesWithinSendNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'handler-dispatches-within-send' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// mailbox-capacity-bounds-mailbox
const mailboxCapacityBoundsMailboxSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'rejectionType': { 'type': 'string' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['rejectionType', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'type': 'array' }, 'machineId': { 'type': 'string' }, 'mailboxCapacity': { 'type': 'number' } }, 'required': ['events', 'machineId', 'mailboxCapacity'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'mailbox-capacity-bounds-mailbox' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const mailboxCapacityBoundsMailboxNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rejectionType': SchemaNode.defineString({ 'type': 'string' } as const), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['rejectionType', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const), 'mailboxCapacity': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['events', 'machineId', 'mailboxCapacity'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'mailbox-capacity-bounds-mailbox' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// processes-events-fifo
const processesEventsFifoSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'type': 'array' }, 'machineId': { 'type': 'string' } }, 'required': ['events', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'processes-events-fifo' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const processesEventsFifoNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['events', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'processes-events-fifo' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// queued-send-resolves-after-own-transition
const queuedSendResolvesAfterOwnTransitionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' }, 'recoveryEvent': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'rejectedEvent': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' } }, 'required': ['machineId', 'recoveryEvent', 'rejectedEvent'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'queued-send-resolves-after-own-transition' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const queuedSendResolvesAfterOwnTransitionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const), 'recoveryEvent': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'rejectedEvent': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['machineId', 'recoveryEvent', 'rejectedEvent'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'queued-send-resolves-after-own-transition' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// rejected-transition-does-not-wedge
const rejectedTransitionDoesNotWedgeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' }, 'recoveryEvent': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'rejectedEvent': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' } }, 'required': ['machineId', 'recoveryEvent', 'rejectedEvent'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'rejected-transition-does-not-wedge' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const rejectedTransitionDoesNotWedgeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const), 'recoveryEvent': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'rejectedEvent': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['machineId', 'recoveryEvent', 'rejectedEvent'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'rejected-transition-does-not-wedge' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// send-before-start
const sendBeforeStartSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'machineId': { 'type': 'string' } }, 'required': ['event', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'send-before-start' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const sendBeforeStartNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'send-before-start' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// send-transitions-state
const sendTransitionsStateSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'notificationCount': { 'type': 'number' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['notificationCount', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'machineId': { 'type': 'string' } }, 'required': ['event', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'send-transitions-state' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const sendTransitionsStateNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'notificationCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['notificationCount', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'send-transitions-state' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// snapshot-isolation
const snapshotIsolationSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'observedCounts': { 'items': { 'type': 'number' }, 'type': 'array' }, 'state': { 'additionalProperties': false, 'properties': { 'details': { 'additionalProperties': false, 'properties': { 'count': { 'type': 'number' } }, 'required': ['count'], 'type': 'object' }, 'variant': { 'type': 'string' } }, 'required': ['details', 'variant'], 'type': 'object' } }, 'required': ['observedCounts', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'activeCount': { 'type': 'number' }, 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'initialCount': { 'type': 'number' }, 'machineId': { 'type': 'string' }, 'mutatedCount': { 'type': 'number' }, 'postMutationCount': { 'type': 'number' }, 'postTransitionMutationCount': { 'type': 'number' } }, 'required': ['activeCount', 'event', 'initialCount', 'machineId', 'mutatedCount', 'postMutationCount', 'postTransitionMutationCount'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'snapshot-isolation' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const snapshotIsolationNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'observedCounts': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'details': SchemaNode.defineObject({ 'type': 'object' } as const, { 'count': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['count'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['details', 'variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['observedCounts', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'activeCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'initialCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const), 'mutatedCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'postMutationCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'postTransitionMutationCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['activeCount', 'event', 'initialCount', 'machineId', 'mutatedCount', 'postMutationCount', 'postTransitionMutationCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'snapshot-isolation' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// start-is-idempotent
const startIsIdempotentSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'notificationCount': { 'type': 'number' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['notificationCount', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' } }, 'required': ['machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'start-is-idempotent' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const startIsIdempotentNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'notificationCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['notificationCount', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'start-is-idempotent' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// start-sets-initial-state
const startSetsInitialStateSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'notificationCount': { 'type': 'number' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['notificationCount', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' } }, 'required': ['machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'start-sets-initial-state' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const startSetsInitialStateNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'notificationCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['notificationCount', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'start-sets-initial-state' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// stop-after-start
const stopAfterStartSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' } }, 'required': ['machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'stop-after-start' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const stopAfterStartNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'stop-after-start' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// stop-before-start
const stopBeforeStartSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' } }, 'required': ['machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'stop-before-start' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const stopBeforeStartNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'stop-before-start' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// stop-hook-throws
const stopHookThrowsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'machineId': { 'type': 'string' } }, 'required': ['machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'stop-hook-throws' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const stopHookThrowsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'stop-hook-throws' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// stop-while-handler-in-flight
const stopWhileHandlerInFlightSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'rejectionMessage': { 'type': 'string' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['rejectionMessage', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'activateEvent': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'deactivateEvent': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'machineId': { 'type': 'string' } }, 'required': ['activateEvent', 'deactivateEvent', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'stop-while-handler-in-flight' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const stopWhileHandlerInFlightNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rejectionMessage': SchemaNode.defineString({ 'type': 'string' } as const), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['rejectionMessage', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'activateEvent': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'deactivateEvent': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['activateEvent', 'deactivateEvent', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'stop-while-handler-in-flight' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-observer-does-not-block-send
const throwingObserverDoesNotBlockSendSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'machineId': { 'type': 'string' } }, 'required': ['event', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-observer-does-not-block-send' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingObserverDoesNotBlockSendNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-observer-does-not-block-send' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// unsubscribe-stops-notifications
const unsubscribeStopsNotificationsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'notificationCount': { 'type': 'number' } }, 'required': ['notificationCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'enum': ['activate', 'deactivate'] } }, 'required': ['type'], 'type': 'object' }, 'machineId': { 'type': 'string' } }, 'required': ['event', 'machineId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'unsubscribe-stops-notifications' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const unsubscribeStopsNotificationsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'notificationCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['notificationCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineEnum({}, ['activate', 'deactivate'] as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'machineId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'machineId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'unsubscribe-stops-notifications' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** Every distinct `shape` value the spec exercises, discriminated by the `shape` const field. */
export namespace EffectInterpreterScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      createDefaultIdentitySchema,
      createEmptyMachineIdSchema,
      createNonIntegerMailboxCapacitySchema,
      createNonPositiveMailboxCapacitySchema,
      effectHandlerCalledAfterTransitionSchema,
      effectHandlerOmittedSchema,
      getStateBeforeStartSchema,
      handlerDispatchesWithinSendSchema,
      mailboxCapacityBoundsMailboxSchema,
      processesEventsFifoSchema,
      queuedSendResolvesAfterOwnTransitionSchema,
      rejectedTransitionDoesNotWedgeSchema,
      sendBeforeStartSchema,
      sendTransitionsStateSchema,
      snapshotIsolationSchema,
      startIsIdempotentSchema,
      startSetsInitialStateSchema,
      stopAfterStartSchema,
      stopBeforeStartSchema,
      stopHookThrowsSchema,
      stopWhileHandlerInFlightSchema,
      throwingObserverDoesNotBlockSendSchema,
      unsubscribeStopsNotificationsSchema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    createDefaultIdentityNode,
    createEmptyMachineIdNode,
    createNonIntegerMailboxCapacityNode,
    createNonPositiveMailboxCapacityNode,
    effectHandlerCalledAfterTransitionNode,
    effectHandlerOmittedNode,
    getStateBeforeStartNode,
    handlerDispatchesWithinSendNode,
    mailboxCapacityBoundsMailboxNode,
    processesEventsFifoNode,
    queuedSendResolvesAfterOwnTransitionNode,
    rejectedTransitionDoesNotWedgeNode,
    sendBeforeStartNode,
    sendTransitionsStateNode,
    snapshotIsolationNode,
    startIsIdempotentNode,
    startSetsInitialStateNode,
    stopAfterStartNode,
    stopBeforeStartNode,
    stopHookThrowsNode,
    stopWhileHandlerInFlightNode,
    throwingObserverDoesNotBlockSendNode,
    unsubscribeStopsNotificationsNode
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
