import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

// async-rejecting-register
const asyncRejectingRegisterSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'rejectionEvents': { 'type': 'number' }, 'valuePreserved': { 'type': 'boolean' } }, 'required': ['hookErrorCount', 'rejectionEvents', 'valuePreserved'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'async-rejecting-register' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const asyncRejectingRegisterNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'rejectionEvents': SchemaNode.defineNumber({ 'type': 'number' } as const), 'valuePreserved': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookErrorCount', 'rejectionEvents', 'valuePreserved'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'async-rejecting-register' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// duplicate-no-register-hook
const duplicateNoRegisterHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'registerCalls': { 'items': {}, 'type': 'array' } }, 'required': ['hookErrorCount', 'registerCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'duplicateId': { 'type': 'string' }, 'id': { 'type': 'string' } }, 'required': ['duplicateId', 'id'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'duplicate-no-register-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const duplicateNoRegisterHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'registerCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({} as const), undefined) }, ['hookErrorCount', 'registerCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'duplicateId': SchemaNode.defineString({ 'type': 'string' } as const), 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['duplicateId', 'id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'duplicate-no-register-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// hook-order
const hookOrderSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'order': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['hookErrorCount', 'order'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' }, 'missingId': { 'type': 'string' } }, 'required': ['id', 'missingId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'hook-order' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const hookOrderNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'order': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['hookErrorCount', 'order'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const), 'missingId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id', 'missingId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hook-order' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// on-register
const onRegisterSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'registerCalls': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['hookErrorCount', 'registerCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'on-register' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onRegisterNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'registerCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['hookErrorCount', 'registerCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'on-register' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// on-resolve-hit-no-hook
const onResolveHitNoHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'missCalls': { 'items': {}, 'type': 'array' } }, 'required': ['hookErrorCount', 'missCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'on-resolve-hit-no-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onResolveHitNoHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'missCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({} as const), undefined) }, ['hookErrorCount', 'missCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'on-resolve-hit-no-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// on-resolve-miss
const onResolveMissSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'missCalls': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['hookErrorCount', 'missCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'missingId': { 'type': 'string' } }, 'required': ['missingId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'on-resolve-miss' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onResolveMissNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'missCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['hookErrorCount', 'missCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'missingId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['missingId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'on-resolve-miss' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// on-unregister
const onUnregisterSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'unregisterCalls': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['hookErrorCount', 'unregisterCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'on-unregister' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onUnregisterNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'unregisterCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['hookErrorCount', 'unregisterCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'on-unregister' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// on-unregister-missing
const onUnregisterMissingSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'unregisterCalls': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['hookErrorCount', 'unregisterCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'missingId': { 'type': 'string' } }, 'required': ['missingId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'on-unregister-missing' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onUnregisterMissingNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'unregisterCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['hookErrorCount', 'unregisterCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'missingId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['missingId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'on-unregister-missing' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-on-register
const throwingOnRegisterSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'valuePreserved': { 'type': 'boolean' } }, 'required': ['hookErrorCount', 'valuePreserved'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-on-register' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingOnRegisterNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'valuePreserved': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookErrorCount', 'valuePreserved'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-on-register' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-on-resolve-miss
const throwingOnResolveMissSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'valueUndefined': { 'type': 'boolean' } }, 'required': ['hookErrorCount', 'valueUndefined'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'missingId': { 'type': 'string' } }, 'required': ['missingId'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-on-resolve-miss' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingOnResolveMissNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'valueUndefined': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookErrorCount', 'valueUndefined'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'missingId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['missingId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-on-resolve-miss' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-on-unregister
const throwingOnUnregisterSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'removed': { 'type': 'boolean' } }, 'required': ['hookErrorCount', 'removed'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-on-unregister' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingOnUnregisterNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'removed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookErrorCount', 'removed'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-on-unregister' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** Every distinct `shape` value the spec exercises, discriminated by the `shape` const field. */
export namespace MachineRegistryHooksScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      asyncRejectingRegisterSchema,
      duplicateNoRegisterHookSchema,
      hookOrderSchema,
      onRegisterSchema,
      onResolveHitNoHookSchema,
      onResolveMissSchema,
      onUnregisterSchema,
      onUnregisterMissingSchema,
      throwingOnRegisterSchema,
      throwingOnResolveMissSchema,
      throwingOnUnregisterSchema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    asyncRejectingRegisterNode,
    duplicateNoRegisterHookNode,
    hookOrderNode,
    onRegisterNode,
    onResolveHitNoHookNode,
    onResolveMissNode,
    onUnregisterNode,
    onUnregisterMissingNode,
    throwingOnRegisterNode,
    throwingOnResolveMissNode,
    throwingOnUnregisterNode
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
