import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

// async-rejection
const asyncRejectionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookCount': { 'type': 'number' }, 'rejectionEvents': { 'type': 'number' }, 'state': { 'type': 'string' } }, 'required': ['hookCount', 'rejectionEvents', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'async-rejection' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const asyncRejectionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'rejectionEvents': SchemaNode.defineNumber({ 'type': 'number' } as const), 'state': SchemaNode.defineString({ 'type': 'string' } as const) }, ['hookCount', 'rejectionEvents', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'async-rejection' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// enter-hook
const enterHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'enter-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const enterHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'enter-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// exit-hook
const exitHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'exit-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const exitHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'exit-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// hook-order
const hookOrderSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'order': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['order'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'hook-order' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const hookOrderNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'order': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['order'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hook-order' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// multiple-transitions
const multipleTransitionsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'enters': { 'items': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' }, 'type': 'array' }, 'exits': { 'items': { 'additionalProperties': false, 'properties': { 'variant': { 'type': 'string' } }, 'required': ['variant'], 'type': 'object' }, 'type': 'array' }, 'transitions': { 'items': { 'additionalProperties': false, 'properties': { 'event': { 'type': 'string' }, 'from': { 'type': 'string' }, 'to': { 'type': 'string' } }, 'required': ['event', 'from', 'to'], 'type': 'object' }, 'type': 'array' } }, 'required': ['enters', 'exits', 'transitions'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'states': { 'items': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' }, 'type': 'array' } }, 'required': ['event', 'states'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'multiple-transitions' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const multipleTransitionsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'enters': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined), 'exits': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineString({ 'type': 'string' } as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined), 'transitions': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineString({ 'type': 'string' } as const), 'from': SchemaNode.defineString({ 'type': 'string' } as const), 'to': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'from', 'to'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['enters', 'exits', 'transitions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'states': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['event', 'states'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'multiple-transitions' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// successful-transition-no-rejection
const successfulTransitionNoRejectionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'rejectionCount': { 'type': 'number' } }, 'required': ['rejectionCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'successful-transition-no-rejection' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const successfulTransitionNoRejectionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rejectionCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['rejectionCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'successful-transition-no-rejection' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-rejection-hook
const throwingRejectionHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookCount': { 'type': 'number' } }, 'required': ['hookCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-rejection-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingRejectionHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['hookCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-rejection-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-transition-hook
const throwingTransitionHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookCount': { 'type': 'number' }, 'state': { 'type': 'string' }, 'toEffects': { 'items': {}, 'type': 'array' } }, 'required': ['hookCount', 'state', 'toEffects'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-transition-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingTransitionHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'state': SchemaNode.defineString({ 'type': 'string' } as const), 'toEffects': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({} as const), undefined) }, ['hookCount', 'state', 'toEffects'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-transition-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// transition-hook
const transitionHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'transition': { 'additionalProperties': false, 'properties': { 'event': { 'type': 'string' }, 'from': { 'type': 'string' }, 'to': { 'type': 'string' } }, 'required': ['event', 'from', 'to'], 'type': 'object' } }, 'required': ['transition'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'transition-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const transitionHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'transition': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineString({ 'type': 'string' } as const), 'from': SchemaNode.defineString({ 'type': 'string' } as const), 'to': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'from', 'to'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['transition'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'transition-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// transition-rejected-hook
const transitionRejectedHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'event': { 'type': 'string' }, 'hookCount': { 'type': 'number' }, 'reasonIncludes': { 'type': 'string' }, 'state': { 'type': 'string' } }, 'required': ['event', 'hookCount', 'reasonIncludes', 'state'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'transition-rejected-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const transitionRejectedHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineString({ 'type': 'string' } as const), 'hookCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'reasonIncludes': SchemaNode.defineString({ 'type': 'string' } as const), 'state': SchemaNode.defineString({ 'type': 'string' } as const) }, ['event', 'hookCount', 'reasonIncludes', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'transition-rejected-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// unchanged-no-hooks
const unchangedNoHooksSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookCount': { 'type': 'number' } }, 'required': ['hookCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'event': { 'additionalProperties': false, 'properties': { 'type': { 'const': 'advance' } }, 'required': ['type'], 'type': 'object' }, 'state': { 'additionalProperties': false, 'properties': { 'variant': { 'enum': ['red', 'green', 'amber'] } }, 'required': ['variant'], 'type': 'object' } }, 'required': ['event', 'state'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'unchanged-no-hooks' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const unchangedNoHooksNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['hookCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'event': SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineConst({}, 'advance' as const) }, ['type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'state': SchemaNode.defineObject({ 'type': 'object' } as const, { 'variant': SchemaNode.defineEnum({}, ['red', 'green', 'amber'] as const) }, ['variant'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['event', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'unchanged-no-hooks' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** Every distinct `shape` value the spec exercises, discriminated by the `shape` const field. */
export namespace StateMachineHooksScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      asyncRejectionSchema,
      enterHookSchema,
      exitHookSchema,
      hookOrderSchema,
      multipleTransitionsSchema,
      successfulTransitionNoRejectionSchema,
      throwingRejectionHookSchema,
      throwingTransitionHookSchema,
      transitionHookSchema,
      transitionRejectedHookSchema,
      unchangedNoHooksSchema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    asyncRejectionNode,
    enterHookNode,
    exitHookNode,
    hookOrderNode,
    multipleTransitionsNode,
    successfulTransitionNoRejectionNode,
    throwingRejectionHookNode,
    throwingTransitionHookNode,
    transitionHookNode,
    transitionRejectedHookNode,
    unchangedNoHooksNode
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
