/**
 * Error codes for consistent error handling
 */

import { DeepFreeze } from '../utils/deepFreeze.js';

export const ErrorCodes = DeepFreeze.deepFreeze({
  'CORE': {
    'BUILTIN_OVERRIDE_DENIED': 'CORE.BUILTIN_OVERRIDE_DENIED',
    'BUILTIN_REMOVAL_DENIED': 'CORE.BUILTIN_REMOVAL_DENIED',
    'FILTER_COMPILATION_ERROR': 'CORE.FILTER_COMPILATION_ERROR',
    'FILTER_EVALUATION_ERROR': 'CORE.FILTER_EVALUATION_ERROR',
    'INVALID_FILTER_CONFIG': 'CORE.INVALID_FILTER_CONFIG',
    'INVALID_FUNCTION': 'CORE.INVALID_FUNCTION',
    'INVALID_LOGICAL_GATE': 'CORE.INVALID_LOGICAL_GATE',
    'INVALID_REGISTRY_CONFIG': 'CORE.INVALID_REGISTRY_CONFIG',
    'PLUGIN_NAMESPACE_CONFLICT': 'CORE.PLUGIN_NAMESPACE_CONFLICT',
    'PLUGIN_VALIDATION_ERROR': 'CORE.PLUGIN_VALIDATION_ERROR',
    'REDOS_VULNERABILITY': 'CORE.REDOS_VULNERABILITY',
    'REGEX_ERROR': 'CORE.REGEX_ERROR',
    'UNKNOWN_ARRAY_LOGIC': 'CORE.UNKNOWN_ARRAY_LOGIC',
    'UNKNOWN_BATCH_OPERATION': 'CORE.UNKNOWN_BATCH_OPERATION',
    'UNKNOWN_COMPARATOR': 'CORE.UNKNOWN_COMPARATOR',
    'UNKNOWN_CONVERTER': 'CORE.UNKNOWN_CONVERTER',
    'UNKNOWN_GATE': 'CORE.UNKNOWN_GATE',
    'UNKNOWN_OPERATOR': 'CORE.UNKNOWN_OPERATOR'
  }
});
