import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface, SchemaNodeInterface } from '@studnicky/entity/interfaces';
import type { NodeInputType, NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/node';
import { SchemaNode } from '@studnicky/entity/types';

const descriptionSchema = { 'minLength': 1, 'type': 'string' } as const;
const descriptionNode = SchemaNode.defineString(descriptionSchema);

/** Builds the `{ description, expected, input, name, shape }` envelope every branch shares, varying only the discriminant and the two payloads. */
class ScenarioBranchBuilders {
  static branchSchema<
    const TShape extends string,
    const TInputSchema extends Record<string, unknown>,
    const TExpectedSchema extends Record<string, unknown>
  >(shape: TShape, inputSchema: TInputSchema, expectedSchema: TExpectedSchema) {
    const result = {
      'additionalProperties': false,
      'properties': {
        'description': descriptionSchema,
        'expected': expectedSchema,
        'input': inputSchema,
        'name': descriptionSchema,
        'shape': { 'const': shape }
      },
      'required': ['description', 'expected', 'input', 'name', 'shape'],
      'type': 'object'
    } as const;
    return result;
  }

  static branchNode<
    const TShape extends string,
    TInputNode extends SchemaNodeInterface<unknown, unknown>,
    TExpectedNode extends SchemaNodeInterface<unknown, unknown>
  >(shape: TShape, inputNode: TInputNode, expectedNode: TExpectedNode) {
    const result = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': descriptionNode,
      'expected': expectedNode,
      'input': inputNode,
      'name': descriptionNode,
      'shape': SchemaNode.defineConst({}, shape)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
    return result;
  }
}

// coalesce-shares-one-execution
const branch1Schema = ScenarioBranchBuilders.branchSchema('coalesce-shares-one-execution', { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'factoryResult': { 'type': 'string' } }, 'required': ['calls', 'factoryResult'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['batch', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'result': { 'type': 'string' } }, 'required': ['calls', 'result'], 'type': 'object' });
const branch1Node = ScenarioBranchBuilders.branchNode('coalesce-shares-one-execution', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'factoryResult': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'factoryResult'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// conflict-exposes-key
const branch2Schema = ScenarioBranchBuilders.branchSchema('conflict-exposes-key', { 'additionalProperties': false, 'properties': { 'conflictingPayload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['conflictingPayload', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'code': { 'type': 'string' }, 'key': { 'type': 'string' }, 'result': { 'type': 'string' } }, 'required': ['code', 'key', 'result'], 'type': 'object' });
const branch2Node = ScenarioBranchBuilders.branchNode('conflict-exposes-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'conflictingPayload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['conflictingPayload', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'code': SchemaNode.defineString({ 'type': 'string' } as const), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['code', 'key', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// conflict-same-key-different-payload
const branch3Schema = ScenarioBranchBuilders.branchSchema('conflict-same-key-different-payload', { 'additionalProperties': false, 'properties': { 'conflictingPayload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['conflictingPayload', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' } }, 'required': ['calls'], 'type': 'object' });
const branch3Node = ScenarioBranchBuilders.branchNode('conflict-same-key-different-payload', SchemaNode.defineObject({ 'type': 'object' } as const, { 'conflictingPayload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['conflictingPayload', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['calls'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-async-overrides-safe
const branch4Schema = ScenarioBranchBuilders.branchSchema('hooks-async-overrides-safe', { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'factoryResult': { 'type': 'string' } }, 'required': ['calls', 'factoryResult'], 'type': 'object' }, 'conflictingPayload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['batch', 'conflictingPayload', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' }, 'rejections': { 'type': 'number' }, 'result': { 'type': 'string' } }, 'required': ['events', 'rejections', 'result'], 'type': 'object' });
const branch4Node = ScenarioBranchBuilders.branchNode('hooks-async-overrides-safe', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'factoryResult': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'factoryResult'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'conflictingPayload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'conflictingPayload', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'rejections': SchemaNode.defineNumber({ 'type': 'number' } as const), 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['events', 'rejections', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-async-replay-safe
const branch5Schema = ScenarioBranchBuilders.branchSchema('hooks-async-replay-safe', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'rejections': { 'type': 'number' }, 'result': { 'type': 'string' } }, 'required': ['rejections', 'result'], 'type': 'object' });
const branch5Node = ScenarioBranchBuilders.branchNode('hooks-async-replay-safe', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'rejections': SchemaNode.defineNumber({ 'type': 'number' } as const), 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['rejections', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-coalesce-follower
const branch6Schema = ScenarioBranchBuilders.branchSchema('hooks-coalesce-follower', { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'factoryResult': { 'type': 'string' } }, 'required': ['calls', 'factoryResult'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['batch', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'coalesced': { 'items': { 'type': 'string' }, 'type': 'array' }, 'executed': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['coalesced', 'executed'], 'type': 'object' });
const branch6Node = ScenarioBranchBuilders.branchNode('hooks-coalesce-follower', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'factoryResult': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'factoryResult'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'coalesced': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'executed': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['coalesced', 'executed'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-conflict-before-throw
const branch7Schema = ScenarioBranchBuilders.branchSchema('hooks-conflict-before-throw', { 'additionalProperties': false, 'properties': { 'conflictingPayload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['conflictingPayload', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'conflicted': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['conflicted'], 'type': 'object' });
const branch7Node = ScenarioBranchBuilders.branchNode('hooks-conflict-before-throw', SchemaNode.defineObject({ 'type': 'object' } as const, { 'conflictingPayload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['conflictingPayload', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'conflicted': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['conflicted'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-execute-before-factory
const branch8Schema = ScenarioBranchBuilders.branchSchema('hooks-execute-before-factory', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' });
const branch8Node = ScenarioBranchBuilders.branchNode('hooks-execute-before-factory', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-execute-new-key
const branch9Schema = ScenarioBranchBuilders.branchSchema('hooks-execute-new-key', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'conflicted': { 'items': {}, 'type': 'array' }, 'executed': { 'items': { 'type': 'string' }, 'type': 'array' }, 'replayed': { 'items': {}, 'type': 'array' } }, 'required': ['conflicted', 'executed', 'replayed'], 'type': 'object' });
const branch9Node = ScenarioBranchBuilders.branchNode('hooks-execute-new-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'conflicted': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({}), undefined), 'executed': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'replayed': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({}), undefined) }, ['conflicted', 'executed', 'replayed'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-isolated-instances
const branch10Schema = ScenarioBranchBuilders.branchSchema('hooks-isolated-instances', { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callsPerInstance': { 'type': 'number' }, 'factoryResults': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['callsPerInstance', 'factoryResults'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['batch', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'firstEvents': { 'items': { 'type': 'string' }, 'type': 'array' }, 'firstFactoryCalls': { 'type': 'number' }, 'results': { 'items': { 'type': 'string' }, 'type': 'array' }, 'secondEvents': { 'items': { 'type': 'string' }, 'type': 'array' }, 'secondFactoryCalls': { 'type': 'number' } }, 'required': ['firstEvents', 'firstFactoryCalls', 'results', 'secondEvents', 'secondFactoryCalls'], 'type': 'object' });
const branch10Node = ScenarioBranchBuilders.branchNode('hooks-isolated-instances', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callsPerInstance': SchemaNode.defineNumber({ 'type': 'number' } as const), 'factoryResults': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['callsPerInstance', 'factoryResults'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'firstEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'firstFactoryCalls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'secondEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'secondFactoryCalls': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['firstEvents', 'firstFactoryCalls', 'results', 'secondEvents', 'secondFactoryCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-replay-match
const branch11Schema = ScenarioBranchBuilders.branchSchema('hooks-replay-match', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'executed': { 'items': { 'type': 'string' }, 'type': 'array' }, 'replayed': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['executed', 'replayed'], 'type': 'object' });
const branch11Node = ScenarioBranchBuilders.branchNode('hooks-replay-match', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'executed': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'replayed': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['executed', 'replayed'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-sync-replay-swallowed
const branch12Schema = ScenarioBranchBuilders.branchSchema('hooks-sync-replay-swallowed', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'string' } }, 'required': ['result'], 'type': 'object' });
const branch12Node = ScenarioBranchBuilders.branchNode('hooks-sync-replay-swallowed', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-throwing-coalesce
const branch13Schema = ScenarioBranchBuilders.branchSchema('hooks-throwing-coalesce', { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'factoryResult': { 'type': 'string' } }, 'required': ['calls', 'factoryResult'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['batch', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'followerResult': { 'type': 'string' }, 'leaderResult': { 'type': 'string' } }, 'required': ['followerResult', 'leaderResult'], 'type': 'object' });
const branch13Node = ScenarioBranchBuilders.branchNode('hooks-throwing-coalesce', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'factoryResult': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'factoryResult'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'followerResult': SchemaNode.defineString({ 'type': 'string' } as const), 'leaderResult': SchemaNode.defineString({ 'type': 'string' } as const) }, ['followerResult', 'leaderResult'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-throwing-conflict
const branch14Schema = ScenarioBranchBuilders.branchSchema('hooks-throwing-conflict', { 'additionalProperties': false, 'properties': { 'conflictingPayload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['conflictingPayload', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'string' } }, 'required': ['result'], 'type': 'object' });
const branch14Node = ScenarioBranchBuilders.branchNode('hooks-throwing-conflict', SchemaNode.defineObject({ 'type': 'object' } as const, { 'conflictingPayload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['conflictingPayload', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-throwing-execute
const branch15Schema = ScenarioBranchBuilders.branchSchema('hooks-throwing-execute', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'string' } }, 'required': ['result'], 'type': 'object' });
const branch15Node = ScenarioBranchBuilders.branchNode('hooks-throwing-execute', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// hooks-throwing-replay
const branch16Schema = ScenarioBranchBuilders.branchSchema('hooks-throwing-replay', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'string' } }, 'required': ['result'], 'type': 'object' });
const branch16Node = ScenarioBranchBuilders.branchNode('hooks-throwing-replay', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// metadata-accepts-string-fingerprint
const branch17Schema = ScenarioBranchBuilders.branchSchema('metadata-accepts-string-fingerprint', { 'additionalProperties': false, 'properties': { 'fingerprint': { 'type': 'string' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' } }, 'required': ['fingerprint', 'idempotencyGuard'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'valid': { 'type': 'boolean' } }, 'required': ['valid'], 'type': 'object' });
const branch17Node = ScenarioBranchBuilders.branchNode('metadata-accepts-string-fingerprint', SchemaNode.defineObject({ 'type': 'object' } as const, { 'fingerprint': SchemaNode.defineString({ 'type': 'string' } as const), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['fingerprint', 'idempotencyGuard'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// metadata-rejects-invalid-fingerprint
const branch18Schema = ScenarioBranchBuilders.branchSchema('metadata-rejects-invalid-fingerprint', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'missingFingerprint': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' }, 'numericFingerprint': { 'additionalProperties': false, 'properties': { 'fingerprint': { 'type': 'number' } }, 'required': ['fingerprint'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'missingFingerprint', 'numericFingerprint'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'missingValid': { 'type': 'boolean' }, 'numericValid': { 'type': 'boolean' } }, 'required': ['missingValid', 'numericValid'], 'type': 'object' });
const branch18Node = ScenarioBranchBuilders.branchNode('metadata-rejects-invalid-fingerprint', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'missingFingerprint': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }), 'numericFingerprint': SchemaNode.defineObject({ 'type': 'object' } as const, { 'fingerprint': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['fingerprint'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'missingFingerprint', 'numericFingerprint'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'missingValid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'numericValid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['missingValid', 'numericValid'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// race-concurrent-different-payload
const branch19Schema = ScenarioBranchBuilders.branchSchema('race-concurrent-different-payload', { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'followerResult': { 'type': 'string' }, 'leaderResult': { 'type': 'string' }, 'replayResult': { 'type': 'string' } }, 'required': ['followerResult', 'leaderResult', 'replayResult'], 'type': 'object' }, 'followerPayload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'leaderPayload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['batch', 'followerPayload', 'idempotencyGuard', 'key', 'leaderPayload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'followerCalls': { 'type': 'number' }, 'leaderCalls': { 'type': 'number' }, 'leaderResult': { 'type': 'string' }, 'replayed': { 'type': 'string' }, 'replayFactoryCalls': { 'type': 'number' } }, 'required': ['followerCalls', 'leaderCalls', 'leaderResult', 'replayed', 'replayFactoryCalls'], 'type': 'object' });
const branch19Node = ScenarioBranchBuilders.branchNode('race-concurrent-different-payload', SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'followerResult': SchemaNode.defineString({ 'type': 'string' } as const), 'leaderResult': SchemaNode.defineString({ 'type': 'string' } as const), 'replayResult': SchemaNode.defineString({ 'type': 'string' } as const) }, ['followerResult', 'leaderResult', 'replayResult'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'followerPayload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'leaderPayload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'followerPayload', 'idempotencyGuard', 'key', 'leaderPayload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'followerCalls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'leaderCalls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'leaderResult': SchemaNode.defineString({ 'type': 'string' } as const), 'replayed': SchemaNode.defineString({ 'type': 'string' } as const), 'replayFactoryCalls': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['followerCalls', 'leaderCalls', 'leaderResult', 'replayed', 'replayFactoryCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// replay-accepts-sync-factory
const branch20Schema = ScenarioBranchBuilders.branchSchema('replay-accepts-sync-factory', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'additionalProperties': false, 'properties': { 'chargeId': { 'type': 'string' } }, 'required': ['chargeId'], 'type': 'object' } }, 'required': ['result'], 'type': 'object' });
const branch20Node = ScenarioBranchBuilders.branchNode('replay-accepts-sync-factory', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineObject({ 'type': 'object' } as const, { 'chargeId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['chargeId'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// replay-cached-result
const branch21Schema = ScenarioBranchBuilders.branchSchema('replay-cached-result', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'firstResult': { 'additionalProperties': false, 'properties': { 'chargeId': { 'type': 'string' } }, 'required': ['chargeId'], 'type': 'object' }, 'secondResult': { 'additionalProperties': false, 'properties': { 'chargeId': { 'type': 'string' } }, 'required': ['chargeId'], 'type': 'object' } }, 'required': ['calls', 'firstResult', 'secondResult'], 'type': 'object' });
const branch21Node = ScenarioBranchBuilders.branchNode('replay-cached-result', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'firstResult': SchemaNode.defineObject({ 'type': 'object' } as const, { 'chargeId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['chargeId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'secondResult': SchemaNode.defineObject({ 'type': 'object' } as const, { 'chargeId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['chargeId'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['calls', 'firstResult', 'secondResult'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// replay-expired-entry-reruns
const branch22Schema = ScenarioBranchBuilders.branchSchema('replay-expired-entry-reruns', { 'additionalProperties': false, 'properties': { 'expirationWaitMs': { 'type': 'number' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'amount': { 'type': 'number' } }, 'required': ['amount'], 'type': 'object' } }, 'required': ['expirationWaitMs', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'second': { 'type': 'string' } }, 'required': ['calls', 'second'], 'type': 'object' });
const branch22Node = ScenarioBranchBuilders.branchNode('replay-expired-entry-reruns', SchemaNode.defineObject({ 'type': 'object' } as const, { 'expirationWaitMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'amount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['amount'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['expirationWaitMs', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// result-contract-owned
const branch23Schema = ScenarioBranchBuilders.branchSchema('result-contract-owned', { 'additionalProperties': false, 'properties': { 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': false, 'properties': { 'operand': { 'type': 'number' } }, 'required': ['operand'], 'type': 'object' } }, 'required': ['idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'initial': { 'type': 'number' }, 'replayed': { 'type': 'number' }, 'type': { 'type': 'string' } }, 'required': ['initial', 'replayed', 'type'], 'type': 'object' });
const branch23Node = ScenarioBranchBuilders.branchNode('result-contract-owned', SchemaNode.defineObject({ 'type': 'object' } as const, { 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'operand': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['operand'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineNumber({ 'type': 'number' } as const), 'replayed': SchemaNode.defineNumber({ 'type': 'number' } as const), 'type': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'replayed', 'type'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// result-contract-rejects-invalid-factory
const branch24Schema = ScenarioBranchBuilders.branchSchema('result-contract-rejects-invalid-factory', { 'additionalProperties': false, 'properties': { 'fixture': { 'type': 'string' }, 'idempotencyGuard': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'ttlMs'], 'type': 'object' }, 'key': { 'type': 'string' }, 'payload': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['fixture', 'idempotencyGuard', 'key', 'payload'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'diagnosticsCount': { 'type': 'number' }, 'messagePattern': { 'type': 'string' } }, 'required': ['diagnosticsCount', 'messagePattern'], 'type': 'object' });
const branch24Node = ScenarioBranchBuilders.branchNode('result-contract-rejects-invalid-factory', SchemaNode.defineObject({ 'type': 'object' } as const, { 'fixture': SchemaNode.defineString({ 'type': 'string' } as const), 'idempotencyGuard': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['fixture', 'idempotencyGuard', 'key', 'payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'diagnosticsCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'messagePattern': SchemaNode.defineString({ 'type': 'string' } as const) }, ['diagnosticsCount', 'messagePattern'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

/** Every `shape` value the scenario file exercises, discriminated by the `shape` const field. */
export namespace IdempotencyGuardScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      branch1Schema,
      branch2Schema,
      branch3Schema,
      branch4Schema,
      branch5Schema,
      branch6Schema,
      branch7Schema,
      branch8Schema,
      branch9Schema,
      branch10Schema,
      branch11Schema,
      branch12Schema,
      branch13Schema,
      branch14Schema,
      branch15Schema,
      branch16Schema,
      branch17Schema,
      branch18Schema,
      branch19Schema,
      branch20Schema,
      branch21Schema,
      branch22Schema,
      branch23Schema,
      branch24Schema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    branch1Node,
    branch2Node,
    branch3Node,
    branch4Node,
    branch5Node,
    branch6Node,
    branch7Node,
    branch8Node,
    branch9Node,
    branch10Node,
    branch11Node,
    branch12Node,
    branch13Node,
    branch14Node,
    branch15Node,
    branch16Node,
    branch17Node,
    branch18Node,
    branch19Node,
    branch20Node,
    branch21Node,
    branch22Node,
    branch23Node,
    branch24Node
  ] as const);
  export type Type = NodeStaticType<typeof Node>;
  export type InputType = NodeInputType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type, InputType> = EntityCompiler.compileCreate<Type, InputType>(Schema);
}
