import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface, SchemaNodeInterface } from '@studnicky/entity/interfaces';
import type { NodeInputType, NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/node';
import { SchemaNode } from '@studnicky/entity/types';

const descriptionSchema = { 'minLength': 1, 'type': 'string' } as const;
const descriptionNode = SchemaNode.defineString(descriptionSchema);

/** Builds the `{ description, expected, input, name, shape }` envelope every branch shares, varying only the discriminant and the two payloads. */
class ScenarioBranchBuilders {
  static branchSchema<
    const TShape extends string,
    const TInputSchema extends Record<string, unknown>,
    const TExpectedSchema extends Record<string, unknown>
  >(shape: TShape, inputSchema: TInputSchema, expectedSchema: TExpectedSchema) {
    const result = {
      'additionalProperties': false,
      'properties': {
        'description': descriptionSchema,
        'expected': expectedSchema,
        'input': inputSchema,
        'name': descriptionSchema,
        'shape': { 'const': shape }
      },
      'required': ['description', 'expected', 'input', 'name', 'shape'],
      'type': 'object'
    } as const;
    return result;
  }

  static branchNode<
    const TShape extends string,
    TInputNode extends SchemaNodeInterface<unknown, unknown>,
    TExpectedNode extends SchemaNodeInterface<unknown, unknown>
  >(shape: TShape, inputNode: TInputNode, expectedNode: TExpectedNode) {
    const result = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': descriptionNode,
      'expected': expectedNode,
      'input': inputNode,
      'name': descriptionNode,
      'shape': SchemaNode.defineConst({}, shape)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
    return result;
  }
}

// active-on-construction
const branch1Schema = ScenarioBranchBuilders.branchSchema('active-on-construction', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'string' } }, 'required': ['result'], 'type': 'object' });
const branch1Node = ScenarioBranchBuilders.branchNode('active-on-construction', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineString({ 'type': 'string' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// async-accumulates-state
const branch2Schema = ScenarioBranchBuilders.branchSchema('async-accumulates-state', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'step': { 'type': 'number' } }, 'required': ['step'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': false, 'properties': { 'async1': { 'type': 'string' }, 'async2': { 'type': 'string' }, 'step': { 'type': 'number' } }, 'required': ['async1', 'async2', 'step'], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' });
const branch2Node = ScenarioBranchBuilders.branchNode('async-accumulates-state', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'step': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['step'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, { 'async1': SchemaNode.defineString({ 'type': 'string' } as const), 'async2': SchemaNode.defineString({ 'type': 'string' } as const), 'step': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['async1', 'async2', 'step'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// async-execute-errors-propagate
const branch3Schema = ScenarioBranchBuilders.branchSchema('async-execute-errors-propagate', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch3Node = ScenarioBranchBuilders.branchNode('async-execute-errors-propagate', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// complex-object-values
const branch4Schema = ScenarioBranchBuilders.branchSchema('complex-object-values', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'complex': { 'additionalProperties': false, 'properties': { 'array': { 'items': { 'type': 'number' }, 'type': 'array' }, 'date': { 'type': 'string' }, 'map': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' }, 'nested': { 'additionalProperties': false, 'properties': { 'deep': { 'additionalProperties': false, 'properties': { 'value': { 'type': 'boolean' } }, 'required': ['value'], 'type': 'object' } }, 'required': ['deep'], 'type': 'object' } }, 'required': ['array', 'date', 'map', 'nested'], 'type': 'object' } }, 'required': ['complex'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'sameReference': { 'type': 'boolean' } }, 'required': ['sameReference'], 'type': 'object' });
const branch4Node = ScenarioBranchBuilders.branchNode('complex-object-values', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'complex': SchemaNode.defineObject({ 'type': 'object' } as const, { 'array': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'date': SchemaNode.defineString({ 'type': 'string' } as const), 'map': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }), 'nested': SchemaNode.defineObject({ 'type': 'object' } as const, { 'deep': SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['deep'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['array', 'date', 'map', 'nested'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['complex'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'sameReference': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['sameReference'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// delete-affects-later-executes
const branch5Schema = ScenarioBranchBuilders.branchSchema('delete-affects-later-executes', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'keep': { 'type': 'string' }, 'remove': { 'type': 'string' } }, 'required': ['keep', 'remove'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': false, 'properties': { 'keep': { 'type': 'string' } }, 'required': ['keep'], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' });
const branch5Node = ScenarioBranchBuilders.branchNode('delete-affects-later-executes', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'keep': SchemaNode.defineString({ 'type': 'string' } as const), 'remove': SchemaNode.defineString({ 'type': 'string' } as const) }, ['keep', 'remove'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, { 'keep': SchemaNode.defineString({ 'type': 'string' } as const) }, ['keep'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// empty-string-key
const branch6Schema = ScenarioBranchBuilders.branchSchema('empty-string-key', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { '': { 'type': 'string' } }, 'required': [''], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'value': { 'type': 'string' } }, 'required': ['value'], 'type': 'object' });
const branch6Node = ScenarioBranchBuilders.branchNode('empty-string-key', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { '': SchemaNode.defineString({ 'type': 'string' } as const) }, [''] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// execute-errors-propagate
const branch7Schema = ScenarioBranchBuilders.branchSchema('execute-errors-propagate', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch7Node = ScenarioBranchBuilders.branchNode('execute-errors-propagate', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// function-values
const branch8Schema = ScenarioBranchBuilders.branchSchema('function-values', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'callable': { 'type': 'string' } }, 'required': ['callable'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'number' } }, 'required': ['result'], 'type': 'object' });
const branch8Node = ScenarioBranchBuilders.branchNode('function-values', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callable': SchemaNode.defineString({ 'type': 'string' } as const) }, ['callable'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// immediate-terminate-empty
const branch9Schema = ScenarioBranchBuilders.branchSchema('immediate-terminate-empty', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' });
const branch9Node = ScenarioBranchBuilders.branchNode('immediate-terminate-empty', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// immediate-terminate-with-values
const branch10Schema = ScenarioBranchBuilders.branchSchema('immediate-terminate-with-values', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'a': { 'type': 'number' }, 'b': { 'type': 'number' } }, 'required': ['a', 'b'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': false, 'properties': { 'a': { 'type': 'number' }, 'b': { 'type': 'number' } }, 'required': ['a', 'b'], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' });
const branch10Node = ScenarioBranchBuilders.branchNode('immediate-terminate-with-values', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'a': SchemaNode.defineNumber({ 'type': 'number' } as const), 'b': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['a', 'b'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, { 'a': SchemaNode.defineNumber({ 'type': 'number' } as const), 'b': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['a', 'b'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// independent-key-sets
const branch11Schema = ScenarioBranchBuilders.branchSchema('independent-key-sets', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'shared': { 'type': 'boolean' } }, 'required': ['shared'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'only1': { 'items': { 'type': 'string' }, 'type': 'array' }, 'only2': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['only1', 'only2'], 'type': 'object' });
const branch11Node = ScenarioBranchBuilders.branchNode('independent-key-sets', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'shared': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['shared'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'only1': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'only2': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['only1', 'only2'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// long-key-name
const branch12Schema = ScenarioBranchBuilders.branchSchema('long-key-name', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'keyLength': { 'type': 'number' } }, 'required': ['keyLength'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'length': { 'type': 'number' }, 'value': { 'type': 'string' } }, 'required': ['length', 'value'], 'type': 'object' });
const branch12Node = ScenarioBranchBuilders.branchNode('long-key-name', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyLength': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['keyLength'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'length': SchemaNode.defineNumber({ 'type': 'number' } as const), 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['length', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// many-keys
const branch13Schema = ScenarioBranchBuilders.branchSchema('many-keys', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'count': { 'type': 'number' } }, 'required': ['count'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'key500': { 'type': 'number' }, 'size': { 'type': 'number' } }, 'required': ['key500', 'size'], 'type': 'object' });
const branch13Node = ScenarioBranchBuilders.branchNode('many-keys', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'count': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['count'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'key500': SchemaNode.defineNumber({ 'type': 'number' } as const), 'size': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['key500', 'size'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// middleware-chain-pattern
const branch14Schema = ScenarioBranchBuilders.branchSchema('middleware-chain-pattern', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' } }, 'required': ['requestId'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'authenticated': { 'type': 'boolean' }, 'logged': { 'type': 'boolean' }, 'requestId': { 'type': 'string' }, 'user': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'validated': { 'type': 'boolean' } }, 'required': ['authenticated', 'logged', 'requestId', 'user', 'validated'], 'type': 'object' });
const branch14Node = ScenarioBranchBuilders.branchNode('middleware-chain-pattern', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['requestId'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'authenticated': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'logged': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'requestId': SchemaNode.defineString({ 'type': 'string' } as const), 'user': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'validated': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['authenticated', 'logged', 'requestId', 'user', 'validated'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// multi-execute-before-terminate
const branch15Schema = ScenarioBranchBuilders.branchSchema('multi-execute-before-terminate', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'executions': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['executions'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'executions': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['executions'], 'type': 'object' });
const branch15Node = ScenarioBranchBuilders.branchNode('multi-execute-before-terminate', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'executions': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['executions'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'executions': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['executions'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// mutations-in-one-scope-not-others
const branch16Schema = ScenarioBranchBuilders.branchSchema('mutations-in-one-scope-not-others', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'value': { 'type': 'string' } }, 'required': ['value'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'scope1': { 'type': 'string' }, 'scope2': { 'type': 'string' } }, 'required': ['scope1', 'scope2'], 'type': 'object' });
const branch16Node = ScenarioBranchBuilders.branchNode('mutations-in-one-scope-not-others', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'scope1': SchemaNode.defineString({ 'type': 'string' } as const), 'scope2': SchemaNode.defineString({ 'type': 'string' } as const) }, ['scope1', 'scope2'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// mutations-visible-after-await
const branch17Schema = ScenarioBranchBuilders.branchSchema('mutations-visible-after-await', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'after': { 'type': 'boolean' }, 'before': { 'type': 'boolean' } }, 'required': ['after', 'before'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': false, 'properties': { 'after': { 'type': 'boolean' }, 'before': { 'type': 'boolean' } }, 'required': ['after', 'before'], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' });
const branch17Node = ScenarioBranchBuilders.branchNode('mutations-visible-after-await', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'after': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'before': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['after', 'before'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, { 'after': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'before': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['after', 'before'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// nested-async-functions
const branch18Schema = ScenarioBranchBuilders.branchSchema('nested-async-functions', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'depth': { 'type': 'number' } }, 'required': ['depth'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'finalDepth': { 'type': 'number' } }, 'required': ['finalDepth'], 'type': 'object' });
const branch18Node = ScenarioBranchBuilders.branchNode('nested-async-functions', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'depth': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['depth'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalDepth': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['finalDepth'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// null-values
const branch19Schema = ScenarioBranchBuilders.branchSchema('null-values', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'nul': { 'type': 'null' } }, 'required': ['nul'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': false, 'properties': { 'nul': { 'type': 'null' } }, 'required': ['nul'], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' });
const branch19Node = ScenarioBranchBuilders.branchNode('null-values', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nul': SchemaNode.defineNull({ 'type': 'null' } as const) }, ['nul'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nul': SchemaNode.defineNull({ 'type': 'null' } as const) }, ['nul'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// overwrite-later-values
const branch20Schema = ScenarioBranchBuilders.branchSchema('overwrite-later-values', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'counter': { 'type': 'number' } }, 'required': ['counter'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'counter': { 'type': 'number' } }, 'required': ['counter'], 'type': 'object' });
const branch20Node = ScenarioBranchBuilders.branchNode('overwrite-later-values', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counter': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['counter'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'counter': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['counter'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// parallel-operations-pattern
const branch21Schema = ScenarioBranchBuilders.branchSchema('parallel-operations-pattern', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'delays': { 'items': { 'type': 'number' }, 'type': 'array' }, 'initial': { 'additionalProperties': false, 'properties': { 'results': { 'items': {}, 'type': 'array' } }, 'required': ['results'], 'type': 'object' } }, 'required': ['delays', 'initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['results'], 'type': 'object' });
const branch21Node = ScenarioBranchBuilders.branchNode('parallel-operations-pattern', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delays': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({}), undefined) }, ['results'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['delays', 'initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['results'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// persist-values-across-executes
const branch22Schema = ScenarioBranchBuilders.branchSchema('persist-values-across-executes', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'fromFirst': { 'type': 'string' }, 'fromSecond': { 'type': 'string' } }, 'required': ['fromFirst', 'fromSecond'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': false, 'properties': { 'fromFirst': { 'type': 'string' }, 'fromSecond': { 'type': 'string' } }, 'required': ['fromFirst', 'fromSecond'], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' });
const branch22Node = ScenarioBranchBuilders.branchNode('persist-values-across-executes', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'fromFirst': SchemaNode.defineString({ 'type': 'string' } as const), 'fromSecond': SchemaNode.defineString({ 'type': 'string' } as const) }, ['fromFirst', 'fromSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, { 'fromFirst': SchemaNode.defineString({ 'type': 'string' } as const), 'fromSecond': SchemaNode.defineString({ 'type': 'string' } as const) }, ['fromFirst', 'fromSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// prevent-execute-after-terminate
const branch23Schema = ScenarioBranchBuilders.branchSchema('prevent-execute-after-terminate', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch23Node = ScenarioBranchBuilders.branchNode('prevent-execute-after-terminate', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// promise-all-propagation
const branch24Schema = ScenarioBranchBuilders.branchSchema('promise-all-propagation', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['results'], 'type': 'object' });
const branch24Node = ScenarioBranchBuilders.branchNode('promise-all-propagation', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['results'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// promise-resolve-propagation
const branch25Schema = ScenarioBranchBuilders.branchSchema('promise-resolve-propagation', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' });
const branch25Node = ScenarioBranchBuilders.branchNode('promise-resolve-propagation', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// request-handling-pattern
const branch26Schema = ScenarioBranchBuilders.branchSchema('request-handling-pattern', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' } }, 'required': ['requestId'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'finalState': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' }, 'userId': { 'type': 'string' } }, 'required': ['requestId', 'userId'], 'type': 'object' }, 'response': { 'additionalProperties': false, 'properties': { 'body': { 'type': 'string' }, 'status': { 'type': 'number' } }, 'required': ['body', 'status'], 'type': 'object' } }, 'required': ['finalState', 'response'], 'type': 'object' });
const branch26Node = ScenarioBranchBuilders.branchNode('request-handling-pattern', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['requestId'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const), 'userId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['requestId', 'userId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'response': SchemaNode.defineObject({ 'type': 'object' } as const, { 'body': SchemaNode.defineString({ 'type': 'string' } as const), 'status': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['body', 'status'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['finalState', 'response'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// scope-reusable-after-error
const branch27Schema = ScenarioBranchBuilders.branchSchema('scope-reusable-after-error', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'initial': { 'type': 'string' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'afterError': { 'type': 'boolean' } }, 'required': ['afterError'], 'type': 'object' });
const branch27Node = ScenarioBranchBuilders.branchNode('scope-reusable-after-error', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'afterError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['afterError'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// separate-scopes-isolated
const branch28Schema = ScenarioBranchBuilders.branchSchema('separate-scopes-isolated', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'items': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'type': 'array' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'contains': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['contains'], 'type': 'object' });
const branch28Node = ScenarioBranchBuilders.branchNode('separate-scopes-isolated', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'contains': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['contains'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// snapshot-clears-store
const branch29Schema = ScenarioBranchBuilders.branchSchema('snapshot-clears-store', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'first': { 'type': 'string' }, 'secondThrows': { 'type': 'boolean' } }, 'required': ['first', 'secondThrows'], 'type': 'object' });
const branch29Node = ScenarioBranchBuilders.branchNode('snapshot-clears-store', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'secondThrows': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['first', 'secondThrows'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// snapshot-complete
const branch30Schema = ScenarioBranchBuilders.branchSchema('snapshot-complete', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'initial1': { 'type': 'string' }, 'initial2': { 'type': 'string' } }, 'required': ['initial1', 'initial2'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'snapshot': { 'additionalProperties': false, 'properties': { 'added1': { 'type': 'string' }, 'added2': { 'type': 'string' }, 'initial1': { 'type': 'string' }, 'initial2': { 'type': 'string' } }, 'required': ['added1', 'added2', 'initial1', 'initial2'], 'type': 'object' } }, 'required': ['snapshot'], 'type': 'object' });
const branch30Node = ScenarioBranchBuilders.branchNode('snapshot-complete', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial1': SchemaNode.defineString({ 'type': 'string' } as const), 'initial2': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial1', 'initial2'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'snapshot': SchemaNode.defineObject({ 'type': 'object' } as const, { 'added1': SchemaNode.defineString({ 'type': 'string' } as const), 'added2': SchemaNode.defineString({ 'type': 'string' } as const), 'initial1': SchemaNode.defineString({ 'type': 'string' } as const), 'initial2': SchemaNode.defineString({ 'type': 'string' } as const) }, ['added1', 'added2', 'initial1', 'initial2'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['snapshot'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// snapshot-independent-copy
const branch31Schema = ScenarioBranchBuilders.branchSchema('snapshot-independent-copy', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'payload': { 'additionalProperties': false, 'properties': { 'nested': { 'type': 'string' } }, 'required': ['nested'], 'type': 'object' } }, 'required': ['payload'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'nested': { 'type': 'string' } }, 'required': ['nested'], 'type': 'object' });
const branch31Node = ScenarioBranchBuilders.branchNode('snapshot-independent-copy', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'payload': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nested': SchemaNode.defineString({ 'type': 'string' } as const) }, ['nested'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['payload'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'nested': SchemaNode.defineString({ 'type': 'string' } as const) }, ['nested'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// symbol-key-string
const branch32Schema = ScenarioBranchBuilders.branchSchema('symbol-key-string', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'Symbol(test)': { 'type': 'string' } }, 'required': ['Symbol(test)'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'value': { 'type': 'string' } }, 'required': ['value'], 'type': 'object' });
const branch32Node = ScenarioBranchBuilders.branchNode('symbol-key-string', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'Symbol(test)': SchemaNode.defineString({ 'type': 'string' } as const) }, ['Symbol(test)'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// terminate-after-error
const branch33Schema = ScenarioBranchBuilders.branchSchema('terminate-after-error', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'terminate': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['terminate'], 'type': 'object' });
const branch33Node = ScenarioBranchBuilders.branchNode('terminate-after-error', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'terminate': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['terminate'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// terminate-once
const branch34Schema = ScenarioBranchBuilders.branchSchema('terminate-once', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch34Node = ScenarioBranchBuilders.branchNode('terminate-once', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// terminated-scope-throws
const branch35Schema = ScenarioBranchBuilders.branchSchema('terminated-scope-throws', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch35Node = ScenarioBranchBuilders.branchNode('terminated-scope-throws', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// timeout-propagation
const branch36Schema = ScenarioBranchBuilders.branchSchema('timeout-propagation', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' });
const branch36Node = ScenarioBranchBuilders.branchNode('timeout-propagation', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// undefined-values
const branch37Schema = ScenarioBranchBuilders.branchSchema('undefined-values', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'undef': { 'type': 'null' } }, 'required': ['undef'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'finalHas': { 'type': 'boolean' }, 'has': { 'type': 'boolean' } }, 'required': ['finalHas', 'has'], 'type': 'object' });
const branch37Node = ScenarioBranchBuilders.branchNode('undefined-values', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'undef': SchemaNode.defineNull({ 'type': 'null' } as const) }, ['undef'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalHas': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'has': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['finalHas', 'has'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

/** Every `shape` value the scenario file exercises, discriminated by the `shape` const field. */
export namespace ContextScopeScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      branch1Schema,
      branch2Schema,
      branch3Schema,
      branch4Schema,
      branch5Schema,
      branch6Schema,
      branch7Schema,
      branch8Schema,
      branch9Schema,
      branch10Schema,
      branch11Schema,
      branch12Schema,
      branch13Schema,
      branch14Schema,
      branch15Schema,
      branch16Schema,
      branch17Schema,
      branch18Schema,
      branch19Schema,
      branch20Schema,
      branch21Schema,
      branch22Schema,
      branch23Schema,
      branch24Schema,
      branch25Schema,
      branch26Schema,
      branch27Schema,
      branch28Schema,
      branch29Schema,
      branch30Schema,
      branch31Schema,
      branch32Schema,
      branch33Schema,
      branch34Schema,
      branch35Schema,
      branch36Schema,
      branch37Schema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    branch1Node,
    branch2Node,
    branch3Node,
    branch4Node,
    branch5Node,
    branch6Node,
    branch7Node,
    branch8Node,
    branch9Node,
    branch10Node,
    branch11Node,
    branch12Node,
    branch13Node,
    branch14Node,
    branch15Node,
    branch16Node,
    branch17Node,
    branch18Node,
    branch19Node,
    branch20Node,
    branch21Node,
    branch22Node,
    branch23Node,
    branch24Node,
    branch25Node,
    branch26Node,
    branch27Node,
    branch28Node,
    branch29Node,
    branch30Node,
    branch31Node,
    branch32Node,
    branch33Node,
    branch34Node,
    branch35Node,
    branch36Node,
    branch37Node
  ] as const);
  export type Type = NodeStaticType<typeof Node>;
  export type InputType = NodeInputType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type, InputType> = EntityCompiler.compileCreate<Type, InputType>(Schema);
}
