import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface, SchemaNodeInterface } from '@studnicky/entity/interfaces';
import type { NodeInputType, NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/node';
import { SchemaNode } from '@studnicky/entity/types';

const descriptionSchema = { 'minLength': 1, 'type': 'string' } as const;
const descriptionNode = SchemaNode.defineString(descriptionSchema);

/** Builds the `{ description, expected, input, name, shape }` envelope every branch shares, varying only the discriminant and the two payloads. */
class ScenarioBranchBuilders {
  static branchSchema<
    const TShape extends string,
    const TInputSchema extends Record<string, unknown>,
    const TExpectedSchema extends Record<string, unknown>
  >(shape: TShape, inputSchema: TInputSchema, expectedSchema: TExpectedSchema) {
    const result = {
      'additionalProperties': false,
      'properties': {
        'description': descriptionSchema,
        'expected': expectedSchema,
        'input': inputSchema,
        'name': descriptionSchema,
        'shape': { 'const': shape }
      },
      'required': ['description', 'expected', 'input', 'name', 'shape'],
      'type': 'object'
    } as const;
    return result;
  }

  static branchNode<
    const TShape extends string,
    TInputNode extends SchemaNodeInterface<unknown, unknown>,
    TExpectedNode extends SchemaNodeInterface<unknown, unknown>
  >(shape: TShape, inputNode: TInputNode, expectedNode: TExpectedNode) {
    const result = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': descriptionNode,
      'expected': expectedNode,
      'input': inputNode,
      'name': descriptionNode,
      'shape': SchemaNode.defineConst({}, shape)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
    return result;
  }
}

// async-on-set-safe
const branch1Schema = ScenarioBranchBuilders.branchSchema('async-on-set-safe', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' }, 'key': { 'type': 'string' }, 'value': { 'type': 'string' } }, 'required': ['initial', 'key', 'value'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'unhandledRejections': { 'type': 'number' } }, 'required': ['unhandledRejections'], 'type': 'object' });
const branch1Node = ScenarioBranchBuilders.branchNode('async-on-set-safe', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'unhandledRejections': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['unhandledRejections'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// async-propagation
const branch2Schema = ScenarioBranchBuilders.branchSchema('async-propagation', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' } }, 'required': ['requestId'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' } }, 'required': ['requestId'], 'type': 'object' });
const branch2Node = ScenarioBranchBuilders.branchNode('async-propagation', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['requestId'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['requestId'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// concurrent-isolation
const branch3Schema = ScenarioBranchBuilders.branchSchema('concurrent-isolation', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial1': { 'additionalProperties': false, 'properties': { 'taskId': { 'type': 'string' } }, 'required': ['taskId'], 'type': 'object' }, 'initial2': { 'additionalProperties': false, 'properties': { 'taskId': { 'type': 'string' } }, 'required': ['taskId'], 'type': 'object' } }, 'required': ['initial1', 'initial2'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['results'], 'type': 'object' });
const branch3Node = ScenarioBranchBuilders.branchNode('concurrent-isolation', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial1': SchemaNode.defineObject({ 'type': 'object' } as const, { 'taskId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['taskId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'initial2': SchemaNode.defineObject({ 'type': 'object' } as const, { 'taskId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['taskId'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial1', 'initial2'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['results'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// concurrent-key-sets
const branch4Schema = ScenarioBranchBuilders.branchSchema('concurrent-key-sets', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial1': { 'additionalProperties': false, 'properties': { 'shared': { 'type': 'boolean' } }, 'required': ['shared'], 'type': 'object' }, 'initial2': { 'additionalProperties': false, 'properties': { 'shared': { 'type': 'boolean' } }, 'required': ['shared'], 'type': 'object' } }, 'required': ['initial1', 'initial2'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'only1': { 'items': { 'type': 'string' }, 'type': 'array' }, 'only2': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['only1', 'only2'], 'type': 'object' });
const branch4Node = ScenarioBranchBuilders.branchNode('concurrent-key-sets', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial1': SchemaNode.defineObject({ 'type': 'object' } as const, { 'shared': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['shared'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'initial2': SchemaNode.defineObject({ 'type': 'object' } as const, { 'shared': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['shared'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial1', 'initial2'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'only1': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'only2': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['only1', 'only2'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// concurrent-mutation-isolation
const branch5Schema = ScenarioBranchBuilders.branchSchema('concurrent-mutation-isolation', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial1': { 'additionalProperties': false, 'properties': { 'value': { 'type': 'number' } }, 'required': ['value'], 'type': 'object' }, 'initial2': { 'additionalProperties': false, 'properties': { 'value': { 'type': 'number' } }, 'required': ['value'], 'type': 'object' } }, 'required': ['initial1', 'initial2'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'scope1': { 'type': 'number' }, 'scope2': { 'type': 'number' } }, 'required': ['scope1', 'scope2'], 'type': 'object' });
const branch5Node = ScenarioBranchBuilders.branchNode('concurrent-mutation-isolation', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial1': SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'initial2': SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial1', 'initial2'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'scope1': SchemaNode.defineNumber({ 'type': 'number' } as const), 'scope2': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['scope1', 'scope2'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// config-validation
const branch6Schema = ScenarioBranchBuilders.branchSchema('config-validation', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'extra': { 'type': 'number' }, 'name': { 'type': 'string' } }, 'required': ['extra', 'name'], 'type': 'object' } }, 'required': ['context'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch6Node = ScenarioBranchBuilders.branchNode('config-validation', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'extra': SchemaNode.defineNumber({ 'type': 'number' } as const), 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['extra', 'name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// create-static
const branch7Schema = ScenarioBranchBuilders.branchSchema('create-static', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' } }, 'required': ['context'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' });
const branch7Node = ScenarioBranchBuilders.branchNode('create-static', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// delete-missing
const branch8Schema = ScenarioBranchBuilders.branchSchema('delete-missing', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' }, 'key': { 'type': 'string' } }, 'required': ['initial', 'key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'removed': { 'type': 'boolean' } }, 'required': ['removed'], 'type': 'object' });
const branch8Node = ScenarioBranchBuilders.branchNode('delete-missing', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'removed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['removed'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// delete-removes
const branch9Schema = ScenarioBranchBuilders.branchSchema('delete-removes', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' }, 'key': { 'type': 'string' } }, 'required': ['initial', 'key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'removed': { 'type': 'boolean' } }, 'required': ['removed'], 'type': 'object' });
const branch9Node = ScenarioBranchBuilders.branchNode('delete-removes', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'removed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['removed'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// execute-after-terminated
const branch10Schema = ScenarioBranchBuilders.branchSchema('execute-after-terminated', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch10Node = ScenarioBranchBuilders.branchNode('execute-after-terminated', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// execute-async
const branch11Schema = ScenarioBranchBuilders.branchSchema('execute-async', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'value': { 'type': 'number' } }, 'required': ['value'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'number' } }, 'required': ['result'], 'type': 'object' });
const branch11Node = ScenarioBranchBuilders.branchNode('execute-async', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// execute-callback
const branch12Schema = ScenarioBranchBuilders.branchSchema('execute-callback', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'value': { 'type': 'string' } }, 'required': ['value'], 'type': 'object' });
const branch12Node = ScenarioBranchBuilders.branchNode('execute-callback', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// execute-multiple
const branch13Schema = ScenarioBranchBuilders.branchSchema('execute-multiple', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'count': { 'type': 'number' } }, 'required': ['count'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'count': { 'type': 'number' } }, 'required': ['count'], 'type': 'object' });
const branch13Node = ScenarioBranchBuilders.branchNode('execute-multiple', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'count': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['count'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'count': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['count'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// execute-return-result
const branch14Schema = ScenarioBranchBuilders.branchSchema('execute-return-result', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'value': { 'type': 'number' } }, 'required': ['value'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'number' } }, 'required': ['result'], 'type': 'object' });
const branch14Node = ScenarioBranchBuilders.branchNode('execute-return-result', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// full-lifecycle
const branch15Schema = ScenarioBranchBuilders.branchSchema('full-lifecycle', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'logger': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'requestId': { 'type': 'string' } }, 'required': ['logger', 'requestId'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'finalState': { 'additionalProperties': false, 'properties': { 'logger': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'requestId': { 'type': 'string' }, 'result': { 'type': 'string' }, 'statusCode': { 'type': 'number' } }, 'required': ['logger', 'requestId', 'result', 'statusCode'], 'type': 'object' }, 'result': { 'type': 'string' }, 'terminated': { 'type': 'boolean' } }, 'required': ['finalState', 'result', 'terminated'], 'type': 'object' });
const branch15Node = ScenarioBranchBuilders.branchNode('full-lifecycle', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'logger': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'requestId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['logger', 'requestId'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineObject({ 'type': 'object' } as const, { 'logger': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'requestId': SchemaNode.defineString({ 'type': 'string' } as const), 'result': SchemaNode.defineString({ 'type': 'string' } as const), 'statusCode': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['logger', 'requestId', 'result', 'statusCode'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'result': SchemaNode.defineString({ 'type': 'string' } as const), 'terminated': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['finalState', 'result', 'terminated'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// get-throws
const branch16Schema = ScenarioBranchBuilders.branchSchema('get-throws', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' }, 'key': { 'type': 'string' } }, 'required': ['initial', 'key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch16Node = ScenarioBranchBuilders.branchNode('get-throws', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// has-check
const branch17Schema = ScenarioBranchBuilders.branchSchema('has-check', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'exists': { 'type': 'boolean' } }, 'required': [], 'type': 'object' }, 'key': { 'type': 'string' } }, 'required': ['initial', 'key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'result': { 'type': 'boolean' } }, 'required': ['result'], 'type': 'object' });
const branch17Node = ScenarioBranchBuilders.branchNode('has-check', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'exists': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// initialize-scope
const branch18Schema = ScenarioBranchBuilders.branchSchema('initialize-scope', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' }, 'value': { 'type': 'number' } }, 'required': ['requestId', 'value'], 'type': 'object' } }, 'required': [], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'keys': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['keys'], 'type': 'object' });
const branch18Node = ScenarioBranchBuilders.branchNode('initialize-scope', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['requestId', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'keys': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// inner-context-no-inherit
const branch19Schema = ScenarioBranchBuilders.branchSchema('inner-context-no-inherit', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'outer': { 'additionalProperties': false, 'properties': { 'outerOnly': { 'type': 'boolean' } }, 'required': ['outerOnly'], 'type': 'object' } }, 'required': ['outer'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'hasOuterOnly': { 'type': 'boolean' } }, 'required': ['hasOuterOnly'], 'type': 'object' });
const branch19Node = ScenarioBranchBuilders.branchNode('inner-context-no-inherit', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'outer': SchemaNode.defineObject({ 'type': 'object' } as const, { 'outerOnly': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['outerOnly'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['outer'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'hasOuterOnly': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hasOuterOnly'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// invalid-name
const branch20Schema = ScenarioBranchBuilders.branchSchema('invalid-name', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'oneOf': [{ 'type': 'number' }, { 'type': 'string' }] } }, 'required': ['name'], 'type': 'object' } }, 'required': ['context'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch20Node = ScenarioBranchBuilders.branchNode('invalid-name', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineString({ 'type': 'string' } as const)] as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// is-active-inside
const branch21Schema = ScenarioBranchBuilders.branchSchema('is-active-inside', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' } }, 'required': ['context'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'active': { 'type': 'boolean' } }, 'required': ['active'], 'type': 'object' });
const branch21Node = ScenarioBranchBuilders.branchNode('is-active-inside', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'active': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['active'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// is-active-outside
const branch22Schema = ScenarioBranchBuilders.branchSchema('is-active-outside', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' } }, 'required': ['context'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'active': { 'type': 'boolean' } }, 'required': ['active'], 'type': 'object' });
const branch22Node = ScenarioBranchBuilders.branchNode('is-active-outside', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'active': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['active'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// keys-returns
const branch23Schema = ScenarioBranchBuilders.branchSchema('keys-returns', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'a': { 'type': 'number' }, 'b': { 'type': 'number' }, 'c': { 'type': 'number' } }, 'required': ['a', 'b', 'c'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'keys': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['keys'], 'type': 'object' });
const branch23Node = ScenarioBranchBuilders.branchNode('keys-returns', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'a': SchemaNode.defineNumber({ 'type': 'number' } as const), 'b': SchemaNode.defineNumber({ 'type': 'number' } as const), 'c': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['a', 'b', 'c'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'keys': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['keys'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// lenient-delete-no-corruption
const branch24Schema = ScenarioBranchBuilders.branchSchema('lenient-delete-no-corruption', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'has': { 'type': 'boolean' }, 'keys': { 'items': {}, 'type': 'array' }, 'removed': { 'type': 'boolean' } }, 'required': ['has', 'keys', 'removed'], 'type': 'object' });
const branch24Node = ScenarioBranchBuilders.branchNode('lenient-delete-no-corruption', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'has': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'keys': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({}), undefined), 'removed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['has', 'keys', 'removed'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// lenient-read-accessors
const branch25Schema = ScenarioBranchBuilders.branchSchema('lenient-read-accessors', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' } }, 'required': ['context'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'has': { 'type': 'boolean' }, 'keys': { 'items': {}, 'type': 'array' }, 'snapshot': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['has', 'keys', 'snapshot'], 'type': 'object' });
const branch25Node = ScenarioBranchBuilders.branchNode('lenient-read-accessors', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'has': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'keys': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({}), undefined), 'snapshot': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['has', 'keys', 'snapshot'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// lenient-set-no-leak
const branch26Schema = ScenarioBranchBuilders.branchSchema('lenient-set-no-leak', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'value': { 'type': 'string' } }, 'required': ['key', 'value'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'has': { 'type': 'boolean' } }, 'required': ['has'], 'type': 'object' });
const branch26Node = ScenarioBranchBuilders.branchNode('lenient-set-no-leak', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'has': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['has'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// multiple-contexts
const branch27Schema = ScenarioBranchBuilders.branchSchema('multiple-contexts', { 'additionalProperties': false, 'properties': { 'contexts': { 'additionalProperties': false, 'properties': { 'first': { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, 'second': { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'count': { 'type': 'number' } }, 'required': ['count'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' } }, 'required': ['first', 'second'], 'type': 'object' } }, 'required': ['contexts'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'context1': { 'type': 'string' }, 'context2': { 'type': 'number' } }, 'required': ['context1', 'context2'], 'type': 'object' });
const branch27Node = ScenarioBranchBuilders.branchNode('multiple-contexts', SchemaNode.defineObject({ 'type': 'object' } as const, { 'contexts': SchemaNode.defineObject({ 'type': 'object' } as const, { 'first': SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'second': SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'count': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['count'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['first', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['contexts'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'context1': SchemaNode.defineString({ 'type': 'string' } as const), 'context2': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['context1', 'context2'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// mutations-persist-async-chain
const branch28Schema = ScenarioBranchBuilders.branchSchema('mutations-persist-async-chain', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'step': { 'type': 'number' } }, 'required': ['step'], 'type': 'object' });
const branch28Node = ScenarioBranchBuilders.branchNode('mutations-persist-async-chain', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'step': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['step'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// nested-scope-isolation
const branch29Schema = ScenarioBranchBuilders.branchSchema('nested-scope-isolation', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'inner': { 'additionalProperties': false, 'properties': { 'level': { 'type': 'string' } }, 'required': ['level'], 'type': 'object' }, 'outer': { 'additionalProperties': false, 'properties': { 'level': { 'type': 'string' } }, 'required': ['level'], 'type': 'object' } }, 'required': ['inner', 'outer'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'inner': { 'type': 'string' }, 'outer': { 'type': 'string' } }, 'required': ['inner', 'outer'], 'type': 'object' });
const branch29Node = ScenarioBranchBuilders.branchNode('nested-scope-isolation', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'inner': SchemaNode.defineObject({ 'type': 'object' } as const, { 'level': SchemaNode.defineString({ 'type': 'string' } as const) }, ['level'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'outer': SchemaNode.defineObject({ 'type': 'object' } as const, { 'level': SchemaNode.defineString({ 'type': 'string' } as const) }, ['level'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['inner', 'outer'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'inner': SchemaNode.defineString({ 'type': 'string' } as const), 'outer': SchemaNode.defineString({ 'type': 'string' } as const) }, ['inner', 'outer'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// outside-get-throws
const branch30Schema = ScenarioBranchBuilders.branchSchema('outside-get-throws', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch30Node = ScenarioBranchBuilders.branchNode('outside-get-throws', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// outside-set-throws
const branch31Schema = ScenarioBranchBuilders.branchSchema('outside-set-throws', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'value': { 'type': 'string' } }, 'required': ['key', 'value'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch31Node = ScenarioBranchBuilders.branchNode('outside-set-throws', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// outside-tryget
const branch32Schema = ScenarioBranchBuilders.branchSchema('outside-tryget', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'found': { 'type': 'boolean' } }, 'required': ['found'], 'type': 'object' });
const branch32Node = ScenarioBranchBuilders.branchNode('outside-tryget', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'found': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['found'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// set-get
const branch33Schema = ScenarioBranchBuilders.branchSchema('set-get', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'value': { 'type': 'string' } }, 'required': ['value'], 'type': 'object' });
const branch33Node = ScenarioBranchBuilders.branchNode('set-get', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// snapshot-copy
const branch34Schema = ScenarioBranchBuilders.branchSchema('snapshot-copy', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' }, 'value': { 'type': 'number' } }, 'required': ['requestId', 'value'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'snapshot': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' }, 'value': { 'type': 'number' } }, 'required': ['requestId', 'value'], 'type': 'object' } }, 'required': ['snapshot'], 'type': 'object' });
const branch34Node = ScenarioBranchBuilders.branchNode('snapshot-copy', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['requestId', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'snapshot': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['requestId', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['snapshot'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// snapshot-independent
const branch35Schema = ScenarioBranchBuilders.branchSchema('snapshot-independent', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'current': { 'type': 'string' }, 'snapshot': { 'type': 'string' } }, 'required': ['current', 'snapshot'], 'type': 'object' });
const branch35Node = ScenarioBranchBuilders.branchNode('snapshot-independent', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'current': SchemaNode.defineString({ 'type': 'string' } as const), 'snapshot': SchemaNode.defineString({ 'type': 'string' } as const) }, ['current', 'snapshot'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// subclass-on-delete
const branch36Schema = ScenarioBranchBuilders.branchSchema('subclass-on-delete', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'toRemove': { 'type': 'string' } }, 'required': ['toRemove'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'additionalProperties': false, 'properties': { 'existed': { 'type': 'boolean' }, 'key': { 'type': 'string' } }, 'required': ['existed', 'key'], 'type': 'object' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' });
const branch36Node = ScenarioBranchBuilders.branchNode('subclass-on-delete', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'toRemove': SchemaNode.defineString({ 'type': 'string' } as const) }, ['toRemove'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'existed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['existed', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// subclass-on-get
const branch37Schema = ScenarioBranchBuilders.branchSchema('subclass-on-get', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'x': { 'type': 'number' } }, 'required': ['x'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'value': { 'type': 'number' } }, 'required': ['key', 'value'], 'type': 'object' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' });
const branch37Node = ScenarioBranchBuilders.branchNode('subclass-on-get', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'x': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['x'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['key', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// subclass-on-get-tryget
const branch38Schema = ScenarioBranchBuilders.branchSchema('subclass-on-get-tryget', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'k': { 'type': 'number' } }, 'required': ['k'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'events': { 'items': {}, 'type': 'array' } }, 'required': ['events'], 'type': 'object' });
const branch38Node = ScenarioBranchBuilders.branchNode('subclass-on-get-tryget', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'k': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['k'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({}), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// subclass-on-initialize
const branch39Schema = ScenarioBranchBuilders.branchSchema('subclass-on-initialize', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'seeded': { 'type': 'string' } }, 'required': ['seeded'], 'type': 'object' });
const branch39Node = ScenarioBranchBuilders.branchNode('subclass-on-initialize', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'seeded': SchemaNode.defineString({ 'type': 'string' } as const) }, ['seeded'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// subclass-on-initialize-with-caller
const branch40Schema = ScenarioBranchBuilders.branchSchema('subclass-on-initialize-with-caller', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'caller': { 'type': 'string' } }, 'required': ['caller'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'caller': { 'type': 'string' }, 'seeded': { 'type': 'string' } }, 'required': ['caller', 'seeded'], 'type': 'object' });
const branch40Node = ScenarioBranchBuilders.branchNode('subclass-on-initialize-with-caller', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'caller': SchemaNode.defineString({ 'type': 'string' } as const) }, ['caller'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'caller': SchemaNode.defineString({ 'type': 'string' } as const), 'seeded': SchemaNode.defineString({ 'type': 'string' } as const) }, ['caller', 'seeded'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// subclass-on-set
const branch41Schema = ScenarioBranchBuilders.branchSchema('subclass-on-set', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'value': { 'oneOf': [{ 'type': 'number' }, { 'type': 'string' }] } }, 'required': ['key', 'value'], 'type': 'object' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' });
const branch41Node = ScenarioBranchBuilders.branchNode('subclass-on-set', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineString({ 'type': 'string' } as const)] as const) }, ['key', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// terminate-clears
const branch42Schema = ScenarioBranchBuilders.branchSchema('terminate-clears', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'firstValue': { 'type': 'string' }, 'secondThrows': { 'type': 'boolean' } }, 'required': ['firstValue', 'secondThrows'], 'type': 'object' });
const branch42Node = ScenarioBranchBuilders.branchNode('terminate-clears', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'firstValue': SchemaNode.defineString({ 'type': 'string' } as const), 'secondThrows': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['firstValue', 'secondThrows'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// terminate-snapshot
const branch43Schema = ScenarioBranchBuilders.branchSchema('terminate-snapshot', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' } }, 'required': ['requestId'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'snapshot': { 'additionalProperties': false, 'properties': { 'requestId': { 'type': 'string' }, 'result': { 'type': 'string' }, 'statusCode': { 'type': 'number' } }, 'required': ['requestId', 'result', 'statusCode'], 'type': 'object' } }, 'required': ['snapshot'], 'type': 'object' });
const branch43Node = ScenarioBranchBuilders.branchNode('terminate-snapshot', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const) }, ['requestId'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'snapshot': SchemaNode.defineObject({ 'type': 'object' } as const, { 'requestId': SchemaNode.defineString({ 'type': 'string' } as const), 'result': SchemaNode.defineString({ 'type': 'string' } as const), 'statusCode': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['requestId', 'result', 'statusCode'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['snapshot'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// terminate-twice
const branch44Schema = ScenarioBranchBuilders.branchSchema('terminate-twice', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' });
const branch44Node = ScenarioBranchBuilders.branchNode('terminate-twice', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// throwing-on-delete
const branch45Schema = ScenarioBranchBuilders.branchSchema('throwing-on-delete', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' }, 'key': { 'type': 'string' } }, 'required': ['initial', 'key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'hookName': { 'type': 'string' }, 'message': { 'type': 'string' } }, 'required': ['hookName', 'message'], 'type': 'object' });
const branch45Node = ScenarioBranchBuilders.branchNode('throwing-on-delete', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookName': SchemaNode.defineString({ 'type': 'string' } as const), 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['hookName', 'message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// throwing-on-get
const branch46Schema = ScenarioBranchBuilders.branchSchema('throwing-on-get', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' }, 'key': { 'type': 'string' } }, 'required': ['initial', 'key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'hookName': { 'type': 'string' }, 'message': { 'type': 'string' } }, 'required': ['hookName', 'message'], 'type': 'object' });
const branch46Node = ScenarioBranchBuilders.branchNode('throwing-on-get', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookName': SchemaNode.defineString({ 'type': 'string' } as const), 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['hookName', 'message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// throwing-on-initialize
const branch47Schema = ScenarioBranchBuilders.branchSchema('throwing-on-initialize', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'seed': { 'type': 'number' } }, 'required': ['seed'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'hookName': { 'type': 'string' }, 'message': { 'type': 'string' } }, 'required': ['hookName', 'message'], 'type': 'object' });
const branch47Node = ScenarioBranchBuilders.branchNode('throwing-on-initialize', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'seed': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['seed'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookName': SchemaNode.defineString({ 'type': 'string' } as const), 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['hookName', 'message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// throwing-on-set
const branch48Schema = ScenarioBranchBuilders.branchSchema('throwing-on-set', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' }, 'key': { 'type': 'string' }, 'value': { 'type': 'string' } }, 'required': ['initial', 'key', 'value'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'hookName': { 'type': 'string' }, 'message': { 'type': 'string' } }, 'required': ['hookName', 'message'], 'type': 'object' });
const branch48Node = ScenarioBranchBuilders.branchNode('throwing-on-set', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookName': SchemaNode.defineString({ 'type': 'string' } as const), 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['hookName', 'message'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// tryget-missing
const branch49Schema = ScenarioBranchBuilders.branchSchema('tryget-missing', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' }, 'key': { 'type': 'string' } }, 'required': ['initial', 'key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'found': { 'type': 'boolean' } }, 'required': ['found'], 'type': 'object' });
const branch49Node = ScenarioBranchBuilders.branchNode('tryget-missing', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'found': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['found'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// tryget-present
const branch50Schema = ScenarioBranchBuilders.branchSchema('tryget-present', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' } }, 'required': ['key'], 'type': 'object' } }, 'required': ['initial'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'found': { 'type': 'boolean' }, 'value': { 'type': 'string' } }, 'required': ['found', 'value'], 'type': 'object' });
const branch50Node = ScenarioBranchBuilders.branchNode('tryget-present', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['initial'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'found': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['found', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

// tryget-undefined
const branch51Schema = ScenarioBranchBuilders.branchSchema('tryget-undefined', { 'additionalProperties': false, 'properties': { 'context': { 'additionalProperties': false, 'properties': { 'name': { 'type': 'string' } }, 'required': ['name'], 'type': 'object' }, 'scope': { 'additionalProperties': false, 'properties': { 'initial': { 'additionalProperties': true, 'properties': {}, 'required': [], 'type': 'object' }, 'key': { 'type': 'string' } }, 'required': ['initial', 'key'], 'type': 'object' } }, 'required': ['context', 'scope'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'found': { 'type': 'boolean' }, 'valueType': { 'type': 'string' } }, 'required': ['found', 'valueType'], 'type': 'object' });
const branch51Node = ScenarioBranchBuilders.branchNode('tryget-undefined', SchemaNode.defineObject({ 'type': 'object' } as const, { 'context': SchemaNode.defineObject({ 'type': 'object' } as const, { 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scope': SchemaNode.defineObject({ 'type': 'object' } as const, { 'initial': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': true, 'patternProperties': {} }), 'key': SchemaNode.defineString({ 'type': 'string' } as const) }, ['initial', 'key'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['context', 'scope'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'found': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'valueType': SchemaNode.defineString({ 'type': 'string' } as const) }, ['found', 'valueType'] as const, { 'additionalProperties': false, 'patternProperties': {} }));

/** Every `shape` value the scenario file exercises, discriminated by the `shape` const field. */
export namespace ContextScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      branch1Schema,
      branch2Schema,
      branch3Schema,
      branch4Schema,
      branch5Schema,
      branch6Schema,
      branch7Schema,
      branch8Schema,
      branch9Schema,
      branch10Schema,
      branch11Schema,
      branch12Schema,
      branch13Schema,
      branch14Schema,
      branch15Schema,
      branch16Schema,
      branch17Schema,
      branch18Schema,
      branch19Schema,
      branch20Schema,
      branch21Schema,
      branch22Schema,
      branch23Schema,
      branch24Schema,
      branch25Schema,
      branch26Schema,
      branch27Schema,
      branch28Schema,
      branch29Schema,
      branch30Schema,
      branch31Schema,
      branch32Schema,
      branch33Schema,
      branch34Schema,
      branch35Schema,
      branch36Schema,
      branch37Schema,
      branch38Schema,
      branch39Schema,
      branch40Schema,
      branch41Schema,
      branch42Schema,
      branch43Schema,
      branch44Schema,
      branch45Schema,
      branch46Schema,
      branch47Schema,
      branch48Schema,
      branch49Schema,
      branch50Schema,
      branch51Schema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    branch1Node,
    branch2Node,
    branch3Node,
    branch4Node,
    branch5Node,
    branch6Node,
    branch7Node,
    branch8Node,
    branch9Node,
    branch10Node,
    branch11Node,
    branch12Node,
    branch13Node,
    branch14Node,
    branch15Node,
    branch16Node,
    branch17Node,
    branch18Node,
    branch19Node,
    branch20Node,
    branch21Node,
    branch22Node,
    branch23Node,
    branch24Node,
    branch25Node,
    branch26Node,
    branch27Node,
    branch28Node,
    branch29Node,
    branch30Node,
    branch31Node,
    branch32Node,
    branch33Node,
    branch34Node,
    branch35Node,
    branch36Node,
    branch37Node,
    branch38Node,
    branch39Node,
    branch40Node,
    branch41Node,
    branch42Node,
    branch43Node,
    branch44Node,
    branch45Node,
    branch46Node,
    branch47Node,
    branch48Node,
    branch49Node,
    branch50Node,
    branch51Node
  ] as const);
  export type Type = NodeStaticType<typeof Node>;
  export type InputType = NodeInputType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type, InputType> = EntityCompiler.compileCreate<Type, InputType>(Schema);
}
