import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

// async-onFire-rejection-guarded
const asyncOnFireRejectionGuardedSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'unhandledRejections': { 'type': 'number' } }, 'required': ['unhandledRejections'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'pastMsOffset': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['pastMsOffset', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'async-onFire-rejection-guarded' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const asyncOnFireRejectionGuardedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'unhandledRejections': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['unhandledRejections'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'pastMsOffset': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['pastMsOffset', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'async-onFire-rejection-guarded' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// backend-overrides
const backendOverridesSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'cancelAllCount': { 'type': 'number' }, 'scheduleCount': { 'type': 'number' } }, 'required': ['cancelAllCount', 'scheduleCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'taskCount': { 'type': 'number' } }, 'required': ['taskCount'], 'type': 'object' }, 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' }, 'intervalMs': { 'type': 'number' } }, 'required': ['delayMs', 'intervalMs'], 'type': 'object' } }, 'required': ['batch', 'scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'backend-overrides' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const backendOverridesNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'cancelAllCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'scheduleCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['cancelAllCount', 'scheduleCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'taskCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['taskCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'intervalMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs', 'intervalMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'backend-overrides' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// cancel-after-fire
const cancelAfterFireSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'callbackCount': { 'type': 'number' }, 'cancelCount': { 'type': 'number' }, 'fireCount': { 'type': 'number' } }, 'required': ['callbackCount', 'cancelCount', 'fireCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['delayMs', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'cancel-after-fire' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const cancelAfterFireNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callbackCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'cancelCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'fireCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callbackCount', 'cancelCount', 'fireCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'cancel-after-fire' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// cancel-before-fire
const cancelBeforeFireSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'cancelCount': { 'type': 'number' } }, 'required': ['cancelCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'cancel-before-fire' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const cancelBeforeFireNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'cancelCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['cancelCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'cancel-before-fire' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// cancelAll-clears-multiple
const cancelAllClearsMultipleSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'cancelAllCount': { 'type': 'number' }, 'scheduleCount': { 'type': 'number' } }, 'required': ['cancelAllCount', 'scheduleCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'taskCount': { 'type': 'number' } }, 'required': ['taskCount'], 'type': 'object' }, 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['batch', 'scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'cancelAll-clears-multiple' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const cancelAllClearsMultipleNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'cancelAllCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'scheduleCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['cancelAllCount', 'scheduleCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'taskCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['taskCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'cancelAll-clears-multiple' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// cancelAll-empty
const cancelAllEmptySchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'cancelAllCount': { 'type': 'number' }, 'scheduleCount': { 'type': 'number' } }, 'required': ['cancelAllCount', 'scheduleCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'taskCount': { 'type': 'number' } }, 'required': ['taskCount'], 'type': 'object' }, 'scheduler': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } }, 'required': ['batch', 'scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'cancelAll-empty' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const cancelAllEmptyNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'cancelAllCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'scheduleCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['cancelAllCount', 'scheduleCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'taskCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['taskCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'cancelAll-empty' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// cancelAll-interval-task
const cancelAllIntervalTaskSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'cancelAllCount': { 'type': 'number' }, 'scheduleCount': { 'type': 'number' } }, 'required': ['cancelAllCount', 'scheduleCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'intervalMs': { 'type': 'number' } }, 'required': ['intervalMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'cancelAll-interval-task' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const cancelAllIntervalTaskNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'cancelAllCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'scheduleCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['cancelAllCount', 'scheduleCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'intervalMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['intervalMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'cancelAll-interval-task' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// chained-timeout-cancel
const chainedTimeoutCancelSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'completed': { 'type': 'boolean' } }, 'required': ['completed'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'chainStageCount': { 'type': 'number' } }, 'required': ['chainStageCount'], 'type': 'object' }, 'scheduler': { 'additionalProperties': false, 'properties': { 'maximumDelayMs': { 'type': 'number' } }, 'required': ['maximumDelayMs'], 'type': 'object' } }, 'required': ['batch', 'scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'chained-timeout-cancel' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const chainedTimeoutCancelNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'completed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['completed'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'chainStageCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['chainStageCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumDelayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['maximumDelayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'chained-timeout-cancel' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// chained-timeout-fire
const chainedTimeoutFireSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'completed': { 'type': 'boolean' } }, 'required': ['completed'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'chainStageCount': { 'type': 'number' } }, 'required': ['chainStageCount'], 'type': 'object' }, 'scheduler': { 'additionalProperties': false, 'properties': { 'maximumDelayMs': { 'type': 'number' } }, 'required': ['maximumDelayMs'], 'type': 'object' } }, 'required': ['batch', 'scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'chained-timeout-fire' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const chainedTimeoutFireNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'completed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['completed'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'chainStageCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['chainStageCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumDelayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['maximumDelayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'chained-timeout-fire' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// custom-id
const customIdSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'id': { 'type': 'string' } }, 'required': ['id'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'custom-id' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const customIdNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'id': SchemaNode.defineString({ 'type': 'string' } as const) }, ['id'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'custom-id' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onCancel-called
const onCancelCalledSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'cancelCount': { 'type': 'number' } }, 'required': ['cancelCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onCancel-called' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onCancelCalledNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'cancelCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['cancelCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onCancel-called' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onCancelAll-called
const onCancelAllCalledSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'cancelAllCount': { 'type': 'number' } }, 'required': ['cancelAllCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onCancelAll-called' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onCancelAllCalledNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'cancelAllCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['cancelAllCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onCancelAll-called' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onDrift-captured
const onDriftCapturedSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'completed': { 'type': 'boolean' } }, 'required': ['completed'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'atMs': { 'type': 'number' }, 'clockStepMs': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['atMs', 'clockStepMs', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onDrift-captured' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onDriftCapturedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'completed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['completed'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'atMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clockStepMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['atMs', 'clockStepMs', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onDrift-captured' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onFireError-async
const onFireErrorAsyncSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'fireErrorCount': { 'type': 'number' } }, 'required': ['fireErrorCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'pastMsOffset': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['pastMsOffset', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onFireError-async' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onFireErrorAsyncNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'fireErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['fireErrorCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'pastMsOffset': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['pastMsOffset', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onFireError-async' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onFireError-sync
const onFireErrorSyncSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'fireErrorCount': { 'type': 'number' } }, 'required': ['fireErrorCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'pastMsOffset': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['pastMsOffset', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onFireError-sync' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onFireErrorSyncNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'fireErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['fireErrorCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'pastMsOffset': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['pastMsOffset', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onFireError-sync' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onIdle-after-cancelAll
const onIdleAfterCancelAllSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'idleCount': { 'type': 'number' } }, 'required': ['idleCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onIdle-after-cancelAll' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onIdleAfterCancelAllNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'idleCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['idleCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onIdle-after-cancelAll' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onIdle-empty-cancelAll
const onIdleEmptyCancelAllSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'idleCount': { 'type': 'number' } }, 'required': ['idleCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'idleCount': { 'type': 'number' } }, 'required': ['idleCount'], 'type': 'object' }, 'scheduler': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } }, 'required': ['batch', 'scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onIdle-empty-cancelAll' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onIdleEmptyCancelAllNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'idleCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['idleCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'idleCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['idleCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onIdle-empty-cancelAll' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onMiss-future-scheduleAt
const onMissFutureScheduleAtSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'missCount': { 'type': 'number' } }, 'required': ['missCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'futureMsOffset': { 'type': 'number' } }, 'required': ['futureMsOffset'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onMiss-future-scheduleAt' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onMissFutureScheduleAtNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'missCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['missCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'futureMsOffset': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['futureMsOffset'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onMiss-future-scheduleAt' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onMiss-past-scheduleAt
const onMissPastScheduleAtSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'missCount': { 'type': 'number' } }, 'required': ['missCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'pastMsOffset': { 'type': 'number' } }, 'required': ['pastMsOffset'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onMiss-past-scheduleAt' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onMissPastScheduleAtNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'missCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['missCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'pastMsOffset': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['pastMsOffset'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onMiss-past-scheduleAt' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// onSchedule-called
const onScheduleCalledSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'scheduleCount': { 'type': 'number' } }, 'required': ['scheduleCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'onSchedule-called' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const onScheduleCalledNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduleCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['scheduleCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'onSchedule-called' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// rejecting-scheduleAt
const rejectingScheduleAtSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'unhandledRejectionCount': { 'type': 'number' } }, 'required': ['unhandledRejectionCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'pastMsOffset': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['pastMsOffset', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'rejecting-scheduleAt' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const rejectingScheduleAtNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'unhandledRejectionCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['unhandledRejectionCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'pastMsOffset': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['pastMsOffset', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'rejecting-scheduleAt' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// rejecting-scheduleEvery
const rejectingScheduleEverySchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'unhandledRejectionCount': { 'type': 'number' } }, 'required': ['unhandledRejectionCount'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'intervalMs': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['intervalMs', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'rejecting-scheduleEvery' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const rejectingScheduleEveryNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'unhandledRejectionCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['unhandledRejectionCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'intervalMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['intervalMs', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'rejecting-scheduleEvery' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// scheduleAt-returns-task
const scheduleAtReturnsTaskSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'atMsMatches': { 'type': 'boolean' }, 'hasId': { 'type': 'boolean' } }, 'required': ['atMsMatches', 'hasId'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'scheduleAt-returns-task' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const scheduleAtReturnsTaskNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'atMsMatches': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'hasId': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['atMsMatches', 'hasId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'scheduleAt-returns-task' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// scheduleEvery-async-reject
const scheduleEveryAsyncRejectSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'completed': { 'type': 'boolean' } }, 'required': ['completed'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'intervalMs': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['intervalMs', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'scheduleEvery-async-reject' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const scheduleEveryAsyncRejectNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'completed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['completed'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'intervalMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['intervalMs', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'scheduleEvery-async-reject' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// scheduleEvery-returns-task
const scheduleEveryReturnsTaskSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'atMsPositive': { 'type': 'boolean' }, 'hasId': { 'type': 'boolean' } }, 'required': ['atMsPositive', 'hasId'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'intervalMs': { 'type': 'number' } }, 'required': ['intervalMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'scheduleEvery-returns-task' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const scheduleEveryReturnsTaskNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'atMsPositive': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'hasId': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['atMsPositive', 'hasId'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'intervalMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['intervalMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'scheduleEvery-returns-task' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// scheduleEvery-sync-throw
const scheduleEverySyncThrowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'completed': { 'type': 'boolean' } }, 'required': ['completed'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'scheduler': { 'additionalProperties': false, 'properties': { 'intervalMs': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['intervalMs', 'waitMs'], 'type': 'object' } }, 'required': ['scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'scheduleEvery-sync-throw' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const scheduleEverySyncThrowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'completed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['completed'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'intervalMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['intervalMs', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'scheduleEvery-sync-throw' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// unique-task-ids
const uniqueTaskIdsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'uniqueIds': { 'type': 'boolean' } }, 'required': ['uniqueIds'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'taskCount': { 'type': 'number' } }, 'required': ['taskCount'], 'type': 'object' }, 'scheduler': { 'additionalProperties': false, 'properties': { 'delayMs': { 'type': 'number' } }, 'required': ['delayMs'], 'type': 'object' } }, 'required': ['batch', 'scheduler'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'unique-task-ids' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const uniqueTaskIdsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'uniqueIds': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['uniqueIds'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'taskCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['taskCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'scheduler': SchemaNode.defineObject({ 'type': 'object' } as const, { 'delayMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['delayMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'scheduler'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'unique-task-ids' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** Every distinct `shape` value the spec exercises, discriminated by the `shape` const field. */
export namespace RealTimeSchedulerScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      asyncOnFireRejectionGuardedSchema,
      backendOverridesSchema,
      cancelAfterFireSchema,
      cancelBeforeFireSchema,
      cancelAllClearsMultipleSchema,
      cancelAllEmptySchema,
      cancelAllIntervalTaskSchema,
      chainedTimeoutCancelSchema,
      chainedTimeoutFireSchema,
      customIdSchema,
      onCancelCalledSchema,
      onCancelAllCalledSchema,
      onDriftCapturedSchema,
      onFireErrorAsyncSchema,
      onFireErrorSyncSchema,
      onIdleAfterCancelAllSchema,
      onIdleEmptyCancelAllSchema,
      onMissFutureScheduleAtSchema,
      onMissPastScheduleAtSchema,
      onScheduleCalledSchema,
      rejectingScheduleAtSchema,
      rejectingScheduleEverySchema,
      scheduleAtReturnsTaskSchema,
      scheduleEveryAsyncRejectSchema,
      scheduleEveryReturnsTaskSchema,
      scheduleEverySyncThrowSchema,
      uniqueTaskIdsSchema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    asyncOnFireRejectionGuardedNode,
    backendOverridesNode,
    cancelAfterFireNode,
    cancelBeforeFireNode,
    cancelAllClearsMultipleNode,
    cancelAllEmptyNode,
    cancelAllIntervalTaskNode,
    chainedTimeoutCancelNode,
    chainedTimeoutFireNode,
    customIdNode,
    onCancelCalledNode,
    onCancelAllCalledNode,
    onDriftCapturedNode,
    onFireErrorAsyncNode,
    onFireErrorSyncNode,
    onIdleAfterCancelAllNode,
    onIdleEmptyCancelAllNode,
    onMissFutureScheduleAtNode,
    onMissPastScheduleAtNode,
    onScheduleCalledNode,
    rejectingScheduleAtNode,
    rejectingScheduleEveryNode,
    scheduleAtReturnsTaskNode,
    scheduleEveryAsyncRejectNode,
    scheduleEveryReturnsTaskNode,
    scheduleEverySyncThrowNode,
    uniqueTaskIdsNode
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
