import { ESLint } from 'eslint';
import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourcePathsPath = path.join(repositoryRoot, 'docs/.vitepress/theme/utils/ExampleSourcePaths.json');
const generatedDirectory = path.join(repositoryRoot, 'docs/.vitepress/theme/utils/generated');

interface PackageManifestInterface {
  readonly 'exports'?: Record<string, { readonly 'import'?: string }>;
  readonly 'name': string;
}

function resolveExistingCanonical(canonical: string): string | undefined {
  if (existsSync(path.join(repositoryRoot, `${canonical  }.ts`))) {
    return canonical;
  }
  const indexCanonical = `${canonical  }/index`;
  if (existsSync(path.join(repositoryRoot, `${indexCanonical  }.ts`))) {
    return indexCanonical;
  }
  const browserNodeCanonical = canonical.replace(/\/node\/index$/u, '/browser/index');
  return existsSync(path.join(repositoryRoot, `${browserNodeCanonical  }.ts`)) ? browserNodeCanonical : undefined;
}

function resolveRelative(specifier: string, fromCanonical: string): string {
  const segments = fromCanonical.split('/').slice(0, -1);
  for (const segment of specifier.replace(/\.(?:js|ts)$/u, '').split('/')) {
    if (segment === '' || segment === '.') {
      continue;
    }
    if (segment === '..') {
      segments.pop();
    } else {
      segments.push(segment);
    }
  }
  return segments.join('/');
}

async function exportTargets(): Promise<Map<string, string>> {
  const entries = await readdir(path.join(repositoryRoot, 'packages'), { 'withFileTypes': true });
  const manifests = await Promise.all(entries.filter((entry) => { return entry.isDirectory(); }).map(async (entry) => {
    const manifestPath = path.join(repositoryRoot, 'packages', entry.name, 'package.json');
    return existsSync(manifestPath) ? JSON.parse(await readFile(manifestPath, 'utf8')) as PackageManifestInterface : undefined;
  }));
  const targets = new Map<string, string>();
  for (const manifest of manifests) {
    if (manifest === undefined) {
      continue;
    }
    for (const [subpath, target] of Object.entries(manifest.exports ?? {})) {
      if (target.import !== undefined) {
        const packageDirectory = manifest.name.replace('@studnicky/', '');
        const canonical = target.import.replace(/^\.\/dist\//u, `packages/${  packageDirectory  }/src/`).replace(/\.js$/u, '');
        targets.set(manifest.name + subpath.slice(1), canonical);
      }
    }
  }
  for (const specifier of targets.keys()) {
    const browserTarget = targets.get(specifier.replace(/\/node$/u, '/browser'));
    if (specifier.endsWith('/node') && browserTarget !== undefined) {
      targets.set(specifier, browserTarget);
    }
  }
  return targets;
}

function requireSpecifiers(code: string): string[] {
  const specifiers = new Set<string>();
  for (const match of code.matchAll(/require\(["']([^"']+)["']\)/gu)) {
    if (match[1] !== undefined) {
      specifiers.add(match[1]);
    }
  }
  return [...specifiers];
}

const importMetaTransformer: ts.TransformerFactory<ts.SourceFile> = (context) => {
  const visit = (node: ts.Node): ts.Node => {
    return ts.isMetaProperty(node) && node.keywordToken === ts.SyntaxKind.ImportKeyword
      ? ts.factory.createIdentifier('__importMeta')
      : ts.visitEachChild(node, visit, context);
  };
  return (sourceFile) => { return ts.visitNode(sourceFile, visit, ts.isSourceFile) ?? sourceFile; };
};

function transpile(source: string, canonical: string): string {
  return ts.transpileModule(source, {
    'compilerOptions': { 'esModuleInterop': true, 'module': ts.ModuleKind.CommonJS, 'target': ts.ScriptTarget.ES2022 },
    'fileName': `${canonical  }.ts`,
    'transformers': { 'before': [importMetaTransformer] }
  }).outputText;
}

function printStringLiteral(value: string): string {
  const interpolation = String.fromCharCode(36, 123);
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll('\b', '\\b')
    .replaceAll('\f', '\\f')
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '\\r')
    .replaceAll('\t', '\\t')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
  if (!escaped.includes(interpolation)) { return `'${  escaped.replaceAll("'", "\\'")  }'`; }
  const template = escaped.replaceAll('`', '\\`').split(interpolation).join(`${  interpolation  }String.fromCharCode(36, 123)}`);
  return `\`${  template  }\``;
}

function printModule(canonical: string, code: string): string {
  return `// Generated by scripts/generate-docs-playgrounds.ts. Do not edit.\nexport const playgroundModule = Object.freeze({ 'canonical': ${  printStringLiteral(canonical)  }, 'code': ${  printStringLiteral(code)  } });\n`;
}

const modulesPerChunk = 32;

function splitIntoChunks(canonicals: readonly string[]): readonly (readonly string[])[] {
  const chunks: string[][] = [];
  for (let index = 0; index < canonicals.length; index += modulesPerChunk) {
    chunks.push(canonicals.slice(index, index + modulesPerChunk));
  }
  return chunks;
}

function printChunk(canonicals: readonly string[], indexes: ReadonlyMap<string, number>): string {
  const imports = canonicals.map((canonical, chunkIndex) => {
    const index = indexes.get(canonical);
    if (index === undefined) { throw new Error(`Missing module index: ${  canonical}`); }
    const separator = chunkIndex === canonicals.length - 1 ? '' : ',';
    return `    import('../../modules/${  String(index)  }').then(({ playgroundModule }) => { return playgroundModule; })${  separator}`;
  });
  if (canonicals.length === 1) {
    const index = indexes.get(canonicals[0] ?? '');
    if (index === undefined) { throw new Error('Missing single-module chunk index.'); }
    return `// Generated by scripts/generate-docs-playgrounds.ts. Do not edit.\nexport function loadPlaygroundModulesChunk() {\n  return import('../../modules/${  String(index)  }').then(({ playgroundModule }) => { return [playgroundModule]; });\n}\n`;
  }
  return `// Generated by scripts/generate-docs-playgrounds.ts. Do not edit.\nexport async function loadPlaygroundModulesChunk() {\n  return await Promise.all([\n${  imports.join('\n')  }\n  ]);\n}\n`;
}

function printEntry(source: string, chunkCount: number, entryIndex: number): string {
  const chunkIndexes = Array.from({ 'length': chunkCount }, (_, chunkIndex) => { return chunkIndex; });
  const imports = chunkIndexes.toSorted((left, right) => { return String(left).localeCompare(String(right)); }).map((chunkIndex) => {
    return `import { loadPlaygroundModulesChunk as loadChunk${  String(chunkIndex)  } } from '../chunks/${  String(entryIndex)  }/${  String(chunkIndex)  }';`;
  });
  const loaders = Array.from({ 'length': chunkCount }, (_, chunkIndex) => {
    const separator = chunkIndex === chunkCount - 1 ? '' : ',';
    return `      loadChunk${  String(chunkIndex)  }()${  separator}`;
  });
  const moduleLoading = chunkCount === 1
    ? '    const modules = await loadChunk0();\n    return Object.fromEntries(modules.map(({ canonical, code }) => { return [canonical, code]; }));'
    : `    const chunks = await Promise.all([\n${  loaders.join('\n')  }\n    ]);\n    return Object.fromEntries(chunks.flat().map(({ canonical, code }) => { return [canonical, code]; }));`;
  return `// Generated by scripts/generate-docs-playgrounds.ts. Do not edit.\n${  imports.join('\n')  }\n\nexport const playgroundPayload = Object.freeze({\n  'loadModules': async function() {\n${  moduleLoading  }\n  },\n  'source': ${  printStringLiteral(source)  }\n});\n`;
}

function printManifest(entries: readonly string[], aliases: ReadonlyMap<string, string>): string {
  const loaders = entries.map((entry, index) => { return `  ${  JSON.stringify(entry)  }: () => import('./entries/${  String(index)  }').then(({ playgroundPayload }) => { return playgroundPayload; }),`; });
  return `// Generated by scripts/generate-docs-playgrounds.ts. Do not edit.\nexport interface PlaygroundPayloadInterface { readonly aliases: Readonly<Record<string, string>>; readonly modules: Readonly<Record<string, string>>; readonly source: string; }\nconst loaders: Readonly<Record<string, () => Promise<{ readonly source: string; readonly loadModules: () => Promise<Record<string, string>> }>>> = {\n${  loaders.join('\n')  }\n};\nconst aliases: Readonly<Record<string, string>> = ${  JSON.stringify(Object.fromEntries(aliases))  };\nexport async function loadPlaygroundSource(path: string): Promise<string> { const loader = loaders[path]; if (loader === undefined) { throw new Error('Unknown playground example: ' + path); } return (await loader()).source; }\nexport async function loadPlaygroundPayload(path: string): Promise<PlaygroundPayloadInterface> { const loader = loaders[path]; if (loader === undefined) { throw new Error('Unknown playground example: ' + path); } const payload = await loader(); return { aliases, modules: await payload.loadModules(), source: payload.source }; }\n`;
}

function intakePaths(raw: unknown): string[] {
  if (!Array.isArray(raw)) { throw new Error('ExampleSourcePaths.json must contain only source-path strings.'); }
  const paths: string[] = [];
  for (const value of raw) {
    if (typeof value !== 'string') { throw new Error('ExampleSourcePaths.json must contain only source-path strings.'); }
    paths.push(value);
  }
  return paths.toSorted();
}

function resolveSpecifier(specifier: string, canonical: string, aliases: ReadonlyMap<string, string>): string {
  if (specifier.startsWith('@studnicky/')) { return aliases.get(specifier) ?? specifier; }
  return specifier.startsWith('.') ? resolveRelative(specifier, canonical) : specifier;
}

async function collectModules(paths: readonly string[], aliases: ReadonlyMap<string, string>): Promise<{ readonly 'codes': Map<string, string>; readonly 'dependencies': Map<string, string[]>; readonly 'sources': Map<string, string> }> {
  const registered = new Set(paths); const codes = new Map<string, string>(); const dependencies = new Map<string, string[]>(); const sources = new Map<string, string>(); const pending = [...paths];
  while (pending.length > 0) {
    const requested = pending.pop(); if (requested === undefined) { continue; }
    const canonical = resolveExistingCanonical(requested); if (canonical === undefined) { throw new Error(`Playground source does not exist: ${canonical}`); }
    if (codes.has(canonical)) { continue; }
    const source = await readFile(path.join(repositoryRoot, `${canonical}.ts`), 'utf8'); if (registered.has(canonical)) { sources.set(canonical, source); }
    const code = transpile(source, canonical); codes.set(canonical, code);
    const direct = new Set<string>();
    for (const specifier of requireSpecifiers(code)) { const dependency = resolveExistingCanonical(resolveSpecifier(specifier, canonical, aliases)); if (dependency !== undefined) { direct.add(dependency); pending.push(dependency); } }
    dependencies.set(canonical, [...direct].toSorted());
  }
  return { 'codes': codes, 'dependencies': dependencies, 'sources': sources };
}

function closureFor(pathname: string, dependencies: ReadonlyMap<string, readonly string[]>): string[] {
  const closure = new Set<string>(); const queue = [pathname];
  while (queue.length > 0) { const canonical = queue.pop(); if (canonical === undefined || closure.has(canonical)) { continue; } closure.add(canonical); queue.push(...(dependencies.get(canonical) ?? [])); }
  return [...closure].toSorted();
}

async function writeModules(codes: ReadonlyMap<string, string>, moduleDirectory: string): Promise<Map<string, number>> {
  const canonicals = [...codes.keys()].toSorted(); const indexes = new Map(canonicals.map((canonical, index): [string, number] => { return [canonical, index]; }));
  await Promise.all(canonicals.map(async (canonical, index): Promise<void> => { const code = codes.get(canonical); if (code === undefined) { throw new Error(`Missing code: ${canonical}`); } await writeFile(path.join(moduleDirectory, `${String(index)}.ts`), printModule(canonical, code)); }));
  return indexes;
}

async function writeEntryChunks(canonicals: readonly string[], indexes: ReadonlyMap<string, number>, chunksDirectory: string, entryIndex: number): Promise<number> {
  const chunks = splitIntoChunks(canonicals);
  const entryChunksDirectory = path.join(chunksDirectory, String(entryIndex));
  await mkdir(entryChunksDirectory, { 'recursive': true });
  await Promise.all(chunks.map(async (chunk, chunkIndex): Promise<void> => {
    await writeFile(path.join(entryChunksDirectory, `${String(chunkIndex)}.ts`), printChunk(chunk, indexes));
  }));
  return chunks.length;
}

async function writeEntries(paths: readonly string[], sources: ReadonlyMap<string, string>, dependencies: ReadonlyMap<string, readonly string[]>, indexes: ReadonlyMap<string, number>, entryDirectory: string): Promise<void> {
  const chunksDirectory = path.join(path.dirname(entryDirectory), 'chunks');
  await Promise.all(paths.map(async (pathname, index): Promise<void> => {
    const source = sources.get(pathname);
    if (source === undefined) { throw new Error(`Missing example source: ${pathname}`); }
    const chunkCount = await writeEntryChunks(closureFor(pathname, dependencies), indexes, chunksDirectory, index);
    await writeFile(path.join(entryDirectory, `${String(index)}.ts`), printEntry(source, chunkCount, index));
  }));
}

async function generate(): Promise<void> {
  const paths = intakePaths(JSON.parse(await readFile(sourcePathsPath, 'utf8')) as unknown);
  const aliases = await exportTargets(); const collected = await collectModules(paths, aliases);
  const moduleDirectory = path.join(generatedDirectory, 'modules'); const entryDirectory = path.join(generatedDirectory, 'entries'); const chunksDirectory = path.join(generatedDirectory, 'chunks');
  await Promise.all([mkdir(moduleDirectory, { 'recursive': true }), mkdir(entryDirectory, { 'recursive': true }), mkdir(chunksDirectory, { 'recursive': true })]);
  const indexes = await writeModules(collected.codes, moduleDirectory);
  await writeEntries(paths, collected.sources, collected.dependencies, indexes, entryDirectory);
  await writeFile(path.join(generatedDirectory, 'playgroundPayloads.ts'), printManifest(paths, aliases));
}

async function lintGeneratedArtifacts(): Promise<void> {
  const artifactPattern = path.join(generatedDirectory, '**/*.ts');
  const fixer = new ESLint({ 'fix': true, 'ignore': false });
  await ESLint.outputFixes(await fixer.lintFiles([artifactPattern]));
  const verifier = new ESLint({ 'ignore': false });
  const results = await verifier.lintFiles([artifactPattern]);
  if (results.some((result) => { return result.errorCount > 0 || result.warningCount > 0; })) {
    const formatter = await verifier.loadFormatter('stylish');
    throw new Error(await formatter.format(results));
  }
}

await generate();
await lintGeneratedArtifacts();
