#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${CI:-}" || -n "${GITHUB_ACTIONS:-}" ]]; then
  exit 0
fi

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  exit 0
fi

source_dir=".githooks"
if [[ ! -d "$source_dir" ]]; then
  echo "install-hooks: missing $source_dir" >&2
  exit 1
fi

local_hooks_path="$(git config --local --get core.hooksPath || true)"
if [[ -n "$local_hooks_path" ]]; then
  git config --local --unset core.hooksPath
fi

effective_hooks_path="$(git config --get core.hooksPath || true)"
if [[ -n "$effective_hooks_path" ]]; then
  cat >&2 <<EOF
install-hooks: core.hooksPath='${effective_hooks_path}' is set outside local repo config.
Git reads hooks from that path instead of .git/hooks, so project forwarders would not run.
Clear the global/system override, then run: pnpm setup-hooks
EOF
  exit 0
fi

git_common_dir="$(git rev-parse --git-common-dir)"
hooks_dir="$git_common_dir/hooks"

resolved_hooks_dir="$(cd "$(dirname "$hooks_dir")" && pwd -P)/$(basename "$hooks_dir")"
resolved_source_dir="$(cd "$source_dir" && pwd -P)"
case "$resolved_hooks_dir" in
  "$resolved_source_dir"|"$resolved_source_dir"/*)
    echo "install-hooks: refusing to write forwarders inside tracked hook source: $resolved_hooks_dir" >&2
    exit 1
    ;;
esac

mkdir -p "$hooks_dir"

changed=()
for hook_src in "$source_dir"/*; do
  [[ -f "$hook_src" && -x "$hook_src" ]] || continue
  hook_name="$(basename "$hook_src")"
  hook_dst="$hooks_dir/$hook_name"

  expected=$(cat <<EOF
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh. Real hook lives in .githooks/${hook_name}.
hook_name="\${0##*/}"
hook="\$(git rev-parse --show-toplevel)/.githooks/\${hook_name}"

if [ ! -x "\$hook" ]; then
  if [ "\$hook_name" = post-checkout ] || [ "\$hook_name" = post-merge ] || [ "\$hook_name" = post-rewrite ]; then
    exit 0
  fi
  echo "git hook target missing or not executable: \$hook" >&2
  exit 1
fi

exec "\$hook" "\$@"
EOF
)

  if [[ -f "$hook_dst" ]] && [[ "$(cat "$hook_dst")" == "$expected" ]] && [[ -x "$hook_dst" ]]; then
    continue
  fi

  printf '%s\n' "$expected" >"$hook_dst"
  chmod +x "$hook_dst"
  changed+=("$hook_name")
done

if [[ ${#changed[@]} -gt 0 ]]; then
  echo "install-hooks: synced ${#changed[@]} forwarder(s): ${changed[*]}"
fi
