/** Data constants for the `descriptive-identifiers` rule: the banned shorthand tokens and the pattern used to recognize a quoted object key as a valid JavaScript identifier (as opposed to a foreign string key, e.g. a rule id or URL). */

export const BANNED_SHORTENINGS = new Set([
  'args',
  'arr',
  'buf',
  'cb',
  'cfg',
  'cnt',
  'conf',
  'ctx',
  'curr',
  'dlq',
  'doc',
  'dst',
  'env',
  'err',
  'fn',
  'idx',
  'kv',
  'len',
  'lst',
  'max',
  'mgr',
  'min',
  'mq',
  'msg',
  'num',
  'nxt',
  'obj',
  'opts',
  'params',
  'prev',
  'ptr',
  'rcv',
  'ref',
  'repo',
  'ret',
  'snd',
  'src',
  'str',
  'svc',
  'tmp',
  'util',
  'utils',
  'val'
]);

export const IDENTIFIER_NAME_PATTERN = /^[A-Za-z_$][\w$]*$/u;
