import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

// async-hooks-safe
const asyncHooksSafeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'cachedResult': { 'type': 'string' }, 'events': { 'items': { 'type': 'string' }, 'type': 'array' }, 'followerResult': { 'type': 'string' }, 'leaderResult': { 'type': 'string' }, 'rejectionEvents': { 'type': 'number' } }, 'required': ['cachedResult', 'events', 'followerResult', 'leaderResult', 'rejectionEvents'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['batch', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'async-hooks-safe' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const asyncHooksSafeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'cachedResult': SchemaNode.defineString({ 'type': 'string' } as const), 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'followerResult': SchemaNode.defineString({ 'type': 'string' } as const), 'leaderResult': SchemaNode.defineString({ 'type': 'string' } as const), 'rejectionEvents': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['cachedResult', 'events', 'followerResult', 'leaderResult', 'rejectionEvents'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'async-hooks-safe' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// clear-recomputes-all
const clearRecomputesAllSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' } }, 'required': ['calls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'clear-recomputes-all' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const clearRecomputesAllNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['calls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'clear-recomputes-all' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// coalesce-shared-call
const coalesceSharedCallSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['calls', 'results'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['batch', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'coalesce-shared-call' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const coalesceSharedCallNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['calls', 'results'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'coalesce-shared-call' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// coalesced-failure-recomputes
const coalescedFailureRecomputesSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'events': { 'items': { 'type': 'string' }, 'type': 'array' }, 'firstErrorMessage': { 'type': 'string' }, 'followerErrorMessage': { 'type': 'string' }, 'second': { 'type': 'string' }, 'third': { 'type': 'string' } }, 'required': ['calls', 'events', 'firstErrorMessage', 'followerErrorMessage', 'second', 'third'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'failureMessage': { 'type': 'string' }, 'key': { 'type': 'string' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' }, 'successValue': { 'type': 'string' } }, 'required': ['batch', 'failureMessage', 'key', 'memoize', 'successValue'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'coalesced-failure-recomputes' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const coalescedFailureRecomputesNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'firstErrorMessage': SchemaNode.defineString({ 'type': 'string' } as const), 'followerErrorMessage': SchemaNode.defineString({ 'type': 'string' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const), 'third': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'events', 'firstErrorMessage', 'followerErrorMessage', 'second', 'third'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'failureMessage': SchemaNode.defineString({ 'type': 'string' } as const), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'successValue': SchemaNode.defineString({ 'type': 'string' } as const) }, ['batch', 'failureMessage', 'key', 'memoize', 'successValue'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'coalesced-failure-recomputes' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// coalesced-hooks
const coalescedHooksSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['batch', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'coalesced-hooks' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const coalescedHooksNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'coalesced-hooks' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// config-error
const configErrorSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'config-error' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const configErrorNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'config-error' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// create-rejects-foreign-construction
const createRejectsForeignConstructionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'create-rejects-foreign-construction' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const createRejectsForeignConstructionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'create-rejects-foreign-construction' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// different-keys
const differentKeysSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['calls', 'results'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'different-keys' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const differentKeysNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['calls', 'results'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'different-keys' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// entities
const entitiesSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'foundFalse': { 'type': 'boolean' }, 'foundTrue': { 'type': 'boolean' }, 'missingFalse': { 'type': 'boolean' } }, 'required': ['foundFalse', 'foundTrue', 'missingFalse'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'entities' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const entitiesNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'foundFalse': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'foundTrue': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'missingFalse': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['foundFalse', 'foundTrue', 'missingFalse'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'entities' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// failure-recomputes-after-rejection
const failureRecomputesAfterRejectionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'events': { 'items': { 'type': 'string' }, 'type': 'array' }, 'firstErrorMessage': { 'type': 'string' }, 'second': { 'type': 'string' }, 'third': { 'type': 'string' } }, 'required': ['calls', 'events', 'firstErrorMessage', 'second', 'third'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'failureMessage': { 'type': 'string' }, 'failuresBeforeSuccess': { 'type': 'number' }, 'key': { 'type': 'string' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' }, 'successValue': { 'type': 'string' } }, 'required': ['failureMessage', 'failuresBeforeSuccess', 'key', 'memoize', 'successValue'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'failure-recomputes-after-rejection' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const failureRecomputesAfterRejectionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'firstErrorMessage': SchemaNode.defineString({ 'type': 'string' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const), 'third': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'events', 'firstErrorMessage', 'second', 'third'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureMessage': SchemaNode.defineString({ 'type': 'string' } as const), 'failuresBeforeSuccess': SchemaNode.defineNumber({ 'type': 'number' } as const), 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'successValue': SchemaNode.defineString({ 'type': 'string' } as const) }, ['failureMessage', 'failuresBeforeSuccess', 'key', 'memoize', 'successValue'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'failure-recomputes-after-rejection' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// hit-and-miss-hooks
const hitAndMissHooksSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'hit-and-miss-hooks' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const hitAndMissHooksNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hit-and-miss-hooks' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// hit-cache
const hitCacheSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'first': { 'type': 'string' }, 'second': { 'type': 'string' } }, 'required': ['calls', 'first', 'second'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' }, 'staleMs': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'keyDeriverShape', 'staleMs', 'ttlMs'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'hit-cache' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const hitCacheNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'first', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const), 'staleMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'keyDeriverShape', 'staleMs', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hit-cache' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// invalidate-preserves-other-keys
const invalidatePreservesOtherKeysSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' } }, 'required': ['calls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'invalidate-preserves-other-keys' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const invalidatePreservesOtherKeysNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['calls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'invalidate-preserves-other-keys' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// invalidate-recomputes
const invalidateRecomputesSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'first': { 'type': 'string' }, 'second': { 'type': 'string' } }, 'required': ['calls', 'first', 'second'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'invalidate-recomputes' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const invalidateRecomputesNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'first', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'invalidate-recomputes' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// isolated-hook-ownership
const isolatedHookOwnershipSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'memoAEvents': { 'items': { 'type': 'string' }, 'type': 'array' }, 'memoBEvents': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['memoAEvents', 'memoBEvents'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['batch', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'isolated-hook-ownership' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const isolatedHookOwnershipNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoAEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'memoBEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['memoAEvents', 'memoBEvents'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'isolated-hook-ownership' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// miss-before-fn
const missBeforeFunctionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'miss-before-fn' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const missBeforeFunctionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'miss-before-fn' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// per-key-hook-args
const perKeyHookArgumentsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'coalescedArguments': { 'additionalProperties': false, 'properties': { 'x': { 'items': { 'oneOf': [{ 'type': 'number' }, { 'type': 'string' }] }, 'type': 'array' }, 'y': { 'items': { 'oneOf': [{ 'type': 'number' }, { 'type': 'string' }] }, 'type': 'array' } }, 'required': ['x', 'y'], 'type': 'object' }, 'missArguments': { 'additionalProperties': false, 'properties': { 'x': { 'items': { 'oneOf': [{ 'type': 'number' }, { 'type': 'string' }] }, 'type': 'array' }, 'y': { 'items': { 'oneOf': [{ 'type': 'number' }, { 'type': 'string' }] }, 'type': 'array' } }, 'required': ['x', 'y'], 'type': 'object' }, 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['coalescedArguments', 'missArguments', 'results'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['batch', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'per-key-hook-args' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const perKeyHookArgumentsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'coalescedArguments': SchemaNode.defineObject({ 'type': 'object' } as const, { 'x': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineString({ 'type': 'string' } as const)] as const), undefined), 'y': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineString({ 'type': 'string' } as const)] as const), undefined) }, ['x', 'y'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'missArguments': SchemaNode.defineObject({ 'type': 'object' } as const, { 'x': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineString({ 'type': 'string' } as const)] as const), undefined), 'y': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineOneOf({}, [SchemaNode.defineNumber({ 'type': 'number' } as const), SchemaNode.defineString({ 'type': 'string' } as const)] as const), undefined) }, ['x', 'y'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['coalescedArguments', 'missArguments', 'results'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'per-key-hook-args' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// rejecting-coalesced-hook
const rejectingCoalescedHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['results'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['batch', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'rejecting-coalesced-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const rejectingCoalescedHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['results'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'rejecting-coalesced-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// rejecting-miss-hook
const rejectingMissHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'first': { 'type': 'string' }, 'second': { 'type': 'string' } }, 'required': ['first', 'second'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'rejecting-miss-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const rejectingMissHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['first', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'rejecting-miss-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// sync-fn
const syncFunctionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'results': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['calls', 'results'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'sync-fn' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const syncFunctionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['calls', 'results'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'sync-fn' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-coalesced-hook
const throwingCoalescedHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['results'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['batch', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-coalesced-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingCoalescedHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['results'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-coalesced-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-hit-hook
const throwingHitHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'value': { 'type': 'string' } }, 'required': ['value'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-hit-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingHitHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'value': SchemaNode.defineString({ 'type': 'string' } as const) }, ['value'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-hit-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// throwing-miss-hook
const throwingMissHookSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'first': { 'type': 'string' }, 'second': { 'type': 'string' } }, 'required': ['first', 'second'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'batch': { 'additionalProperties': false, 'properties': { 'callCount': { 'type': 'number' } }, 'required': ['callCount'], 'type': 'object' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['batch', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'throwing-miss-hook' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const throwingMissHookNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['first', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'batch': SchemaNode.defineObject({ 'type': 'object' } as const, { 'callCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['callCount'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['batch', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'throwing-miss-hook' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// ttl-stale-options
const ttlStaleOptionsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'afterExpiry': { 'type': 'string' }, 'calls': { 'type': 'number' }, 'callsAfterExpiry': { 'type': 'number' }, 'first': { 'type': 'string' }, 'second': { 'type': 'string' } }, 'required': ['afterExpiry', 'calls', 'callsAfterExpiry', 'first', 'second'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' }, 'staleMs': { 'type': 'number' }, 'ttlMs': { 'type': 'number' } }, 'required': ['capacity', 'keyDeriverShape', 'staleMs', 'ttlMs'], 'type': 'object' } }, 'required': ['memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'ttl-stale-options' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const ttlStaleOptionsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'afterExpiry': SchemaNode.defineString({ 'type': 'string' } as const), 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'callsAfterExpiry': SchemaNode.defineNumber({ 'type': 'number' } as const), 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['afterExpiry', 'calls', 'callsAfterExpiry', 'first', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const), 'staleMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'ttlMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity', 'keyDeriverShape', 'staleMs', 'ttlMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'ttl-stale-options' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

// undefined-result-cache
const undefinedResultCacheSchema = { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'calls': { 'type': 'number' }, 'resultType': { 'type': 'string' } }, 'required': ['calls', 'resultType'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'memoize': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'keyDeriverShape': { 'type': 'string' } }, 'required': ['capacity', 'keyDeriverShape'], 'type': 'object' } }, 'required': ['key', 'memoize'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'undefined-result-cache' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
const undefinedResultCacheNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'calls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resultType': SchemaNode.defineString({ 'type': 'string' } as const) }, ['calls', 'resultType'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'memoize': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyDeriverShape': SchemaNode.defineString({ 'type': 'string' } as const) }, ['capacity', 'keyDeriverShape'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['key', 'memoize'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'undefined-result-cache' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** Every distinct `shape` value the spec exercises, discriminated by the `shape` const field. */
export namespace MemoizeScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      asyncHooksSafeSchema,
      clearRecomputesAllSchema,
      coalesceSharedCallSchema,
      coalescedFailureRecomputesSchema,
      coalescedHooksSchema,
      configErrorSchema,
      createRejectsForeignConstructionSchema,
      differentKeysSchema,
      entitiesSchema,
      failureRecomputesAfterRejectionSchema,
      hitAndMissHooksSchema,
      hitCacheSchema,
      invalidatePreservesOtherKeysSchema,
      invalidateRecomputesSchema,
      isolatedHookOwnershipSchema,
      missBeforeFunctionSchema,
      perKeyHookArgumentsSchema,
      rejectingCoalescedHookSchema,
      rejectingMissHookSchema,
      syncFunctionSchema,
      throwingCoalescedHookSchema,
      throwingHitHookSchema,
      throwingMissHookSchema,
      ttlStaleOptionsSchema,
      undefinedResultCacheSchema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    asyncHooksSafeNode,
    clearRecomputesAllNode,
    coalesceSharedCallNode,
    coalescedFailureRecomputesNode,
    coalescedHooksNode,
    configErrorNode,
    createRejectsForeignConstructionNode,
    differentKeysNode,
    entitiesNode,
    failureRecomputesAfterRejectionNode,
    hitAndMissHooksNode,
    hitCacheNode,
    invalidatePreservesOtherKeysNode,
    invalidateRecomputesNode,
    isolatedHookOwnershipNode,
    missBeforeFunctionNode,
    perKeyHookArgumentsNode,
    rejectingCoalescedHookNode,
    rejectingMissHookNode,
    syncFunctionNode,
    throwingCoalescedHookNode,
    throwingHitHookNode,
    throwingMissHookNode,
    ttlStaleOptionsNode,
    undefinedResultCacheNode
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
