import type { EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

import { BoundedJsonValueEntity } from '../../../helpers/entities/BoundedJsonValueEntity.js';

/** The `headers.errors.loop.spec.ts` scenario case shape: one branch per `shape`. */
export namespace HeadersErrorsScenarioCaseEntity {
  const clientConfigSchema = { 'additionalProperties': false, 'properties': { 'headers': BoundedJsonValueEntity.Schema }, 'required': [], 'type': 'object' } as const;
  const requestSchema = { 'additionalProperties': false, 'properties': { 'acceptValues': { 'items': { 'type': 'string' }, 'type': 'array' }, 'body': BoundedJsonValueEntity.Schema, 'headers': { 'additionalProperties': { 'type': 'string' }, 'properties': {}, 'required': [], 'type': 'object' }, 'method': { 'enum': ['GET', 'POST'] }, 'path': { 'minLength': 1, 'type': 'string' } }, 'required': ['method', 'path'], 'type': 'object' } as const;

  export const Schema = { 'oneOf': [{ 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'status': { 'maximum': 599, 'minimum': 100, 'type': 'integer' } }, 'required': ['status'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'clientConfig': clientConfigSchema, 'request': requestSchema }, 'required': ['request'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'ok' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'messageIncludes': { 'items': { 'minLength': 1, 'type': 'string' }, 'type': 'array' } }, 'required': [], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'clientConfig': clientConfigSchema }, 'required': ['clientConfig'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'rejects-construction' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'errorType': { 'const': 'TypeError' }, 'messageIncludes': { 'items': { 'minLength': 1, 'type': 'string' }, 'type': 'array' } }, 'required': [], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'clientConfig': clientConfigSchema, 'request': requestSchema }, 'required': ['request'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'shape': { 'const': 'rejects-request' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' }] } as const;

  const ClientConfigNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'headers': BoundedJsonValueEntity.Node }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });
  const RequestNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'acceptValues': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'body': BoundedJsonValueEntity.Node, 'headers': SchemaNode.defineObject({ 'type': 'object' } as const, {}, [] as const, { 'additionalProperties': SchemaNode.defineString({ 'type': 'string' } as const), 'patternProperties': {} }), 'method': SchemaNode.defineEnum({}, ['GET', 'POST'] as const), 'path': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const) }, ['method', 'path'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  export const Node = SchemaNode.defineOneOf({}, [SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'status': SchemaNode.defineNumber({ 'maximum': 599, 'minimum': 100, 'type': 'integer' } as const) }, ['status'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clientConfig': ClientConfigNode, 'request': RequestNode }, ['request'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'ok' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'messageIncludes': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), undefined) }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clientConfig': ClientConfigNode }, ['clientConfig'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'rejects-construction' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'errorType': SchemaNode.defineConst({}, 'TypeError' as const), 'messageIncludes': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), undefined) }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clientConfig': ClientConfigNode, 'request': RequestNode }, ['request'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'rejects-request' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} })] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
}
