import type { EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

import { ObjectFixtureEntity } from './ObjectFixtureEntity.js';
import { RealTimeClockProviderOptionsFixtureEntity } from './RealTimeClockProviderOptionsFixtureEntity.js';
import { VirtualTimeCounterOptionsFixtureEntity } from './VirtualTimeCounterOptionsFixtureEntity.js';

/** The 49 scenario shapes `Clock.loop.spec.ts` exercises. */
export namespace ClockScenarioCaseEntity {
  const clampBackwardsProviderValuesSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'clamped': { 'type': 'boolean' } }, 'required': ['clamped'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema, 'lowerCounterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions', 'lowerCounterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'clamp-backwards-provider-values' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const clampBackwardsProviderValuesNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clamped': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['clamped'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node, 'lowerCounterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions', 'lowerCounterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'clamp-backwards-provider-values' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const clockAsyncOnNowRejectionContainedSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'result': { 'type': 'number' }, 'unhandledRejections': { 'type': 'number' } }, 'required': ['result', 'unhandledRejections'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema, 'message': { 'type': 'string' } }, 'required': ['counterOptions', 'message'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'clock-async-on-now-rejection-contained' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const clockAsyncOnNowRejectionContainedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineNumber({ 'type': 'number' } as const), 'unhandledRejections': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['result', 'unhandledRejections'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node, 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['counterOptions', 'message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'clock-async-on-now-rejection-contained' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const clockErrorWithCauseSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'ok': { 'type': 'boolean' } }, 'required': ['ok'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'clock-error-with-cause' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const clockErrorWithCauseNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'ok': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['ok'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'clock-error-with-cause' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const clockInvalidProviderSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'providerFixture': ObjectFixtureEntity.Schema }, 'required': ['providerFixture'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'clock-invalid-provider' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const clockInvalidProviderNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'providerFixture': ObjectFixtureEntity.Node }, ['providerFixture'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'clock-invalid-provider' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const clockThrowsOnHrtimeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookError': { 'type': 'boolean' } }, 'required': ['hookError'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'clock-throws-on-hrtime' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const clockThrowsOnHrtimeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookError'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'clock-throws-on-hrtime' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const clockThrowsOnNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookError': { 'type': 'boolean' } }, 'required': ['hookError'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'clock-throws-on-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const clockThrowsOnNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookError'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'clock-throws-on-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const counterInvalidOptionsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'counter-invalid-options' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const counterInvalidOptionsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'counter-invalid-options' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const counterOnAdvanceSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookCalls': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['hookCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'counter-on-advance' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const counterOnAdvanceNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['hookCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'counter-on-advance' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const counterOnAdvanceSequenceSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookCalls': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['hookCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advances': { 'items': { 'type': 'number' }, 'type': 'array' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advances', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'counter-on-advance-sequence' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const counterOnAdvanceSequenceNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['hookCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advances': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advances', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'counter-on-advance-sequence' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const counterOnAdvanceSuppressedSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookCalls': { 'items': {}, 'type': 'array' } }, 'required': ['hookCalls'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advances': { 'items': { 'type': 'number' }, 'type': 'array' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advances', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'counter-on-advance-suppressed' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const counterOnAdvanceSuppressedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookCalls': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineUnknown({} as const), undefined) }, ['hookCalls'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advances': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advances', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'counter-on-advance-suppressed' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const counterOnNowMsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'values': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['values'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'counter-on-now-ms' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const counterOnNowMsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'values': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['values'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'counter-on-now-ms' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const counterOnNowMsRepeatSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'values': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['values'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'counter-on-now-ms-repeat' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const counterOnNowMsRepeatNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'values': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['values'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'counter-on-now-ms-repeat' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const counterThrowsOnAdvanceSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookError': { 'type': 'boolean' } }, 'required': ['hookError'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'counter-throws-on-advance' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const counterThrowsOnAdvanceNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookError'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'counter-throws-on-advance' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const counterThrowsOnNowMsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookError': { 'type': 'boolean' } }, 'required': ['hookError'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'counter-throws-on-now-ms' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const counterThrowsOnNowMsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookError'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'counter-throws-on-now-ms' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const hookedClockOnHrtimeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hrtimeEvents': { 'items': { 'type': 'number' }, 'type': 'array' }, 'result': { 'type': 'number' } }, 'required': ['hrtimeEvents', 'result'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'hooked-clock-on-hrtime' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const hookedClockOnHrtimeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hrtimeEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['hrtimeEvents', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hooked-clock-on-hrtime' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const hookedClockOnHrtimeRepeatSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hrtimeEvents': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['hrtimeEvents'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'hooked-clock-on-hrtime-repeat' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const hookedClockOnHrtimeRepeatNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hrtimeEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['hrtimeEvents'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hooked-clock-on-hrtime-repeat' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const hookedClockOnNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'nowEvents': { 'items': { 'type': 'number' }, 'type': 'array' }, 'result': { 'type': 'number' } }, 'required': ['nowEvents', 'result'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'hooked-clock-on-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const hookedClockOnNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nowEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['nowEvents', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hooked-clock-on-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const hookedClockOnNowAdvancedSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'nowEvents': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['nowEvents'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'hooked-clock-on-now-advanced' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const hookedClockOnNowAdvancedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nowEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['nowEvents'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hooked-clock-on-now-advanced' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const hookedClockOnNowClampedSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'nowEvents': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['nowEvents'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'hooked-clock-on-now-clamped' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const hookedClockOnNowClampedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nowEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['nowEvents'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hooked-clock-on-now-clamped' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const hrtimeMonotonicSameInstanceSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'monotonic': { 'type': 'boolean' } }, 'required': ['monotonic'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'hrtime-monotonic-same-instance' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const hrtimeMonotonicSameInstanceNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'monotonic': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['monotonic'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hrtime-monotonic-same-instance' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const hrtimeReturnsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'ns': { 'type': 'string' } }, 'required': ['ns'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'hrtime-returns' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const hrtimeReturnsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'ns': SchemaNode.defineString({ 'type': 'string' } as const) }, ['ns'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'hrtime-returns' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const longUptimePrecisionSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'precise': { 'type': 'boolean' } }, 'required': ['precise'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'rawMs': { 'type': 'number' }, 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['rawMs', 'realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'long-uptime-precision' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const longUptimePrecisionNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'precise': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['precise'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rawMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['rawMs', 'realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'long-uptime-precision' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const meteredClockHrtimeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hrtime': { 'type': 'string' } }, 'required': ['hrtime'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'metered-clock-hrtime' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const meteredClockHrtimeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hrtime': SchemaNode.defineString({ 'type': 'string' } as const) }, ['hrtime'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'metered-clock-hrtime' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const meteredClockNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'now': { 'type': 'number' } }, 'required': ['now'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'metered-clock-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const meteredClockNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'now': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['now'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'metered-clock-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const nowMonotonicSameInstanceSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'monotonic': { 'type': 'boolean' } }, 'required': ['monotonic'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'now-monotonic-same-instance' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const nowMonotonicSameInstanceNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'monotonic': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['monotonic'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'now-monotonic-same-instance' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const nowReturnsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'now': { 'type': 'number' } }, 'required': ['now'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'now-returns' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const nowReturnsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'now': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['now'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'now-returns' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const offsetInvalidSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'offset-invalid' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const offsetInvalidNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'offset-invalid' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const offsetProviderNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'now': { 'type': 'number' } }, 'required': ['now'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'rawMs': { 'type': 'number' }, 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['rawMs', 'realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'offset-provider-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const offsetProviderNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'now': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['now'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rawMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['rawMs', 'realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'offset-provider-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const offsetProviderOffsetSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'now': { 'type': 'number' } }, 'required': ['now'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'rawMs': { 'type': 'number' }, 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['rawMs', 'realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'offset-provider-offset' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const offsetProviderOffsetNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'now': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['now'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rawMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['rawMs', 'realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'offset-provider-offset' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realHrtimePositiveSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'positive': { 'type': 'boolean' } }, 'required': ['positive'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-hrtime-positive' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realHrtimePositiveNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'positive': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['positive'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-hrtime-positive' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realNowWithinRangeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'withinTolerance': { 'type': 'boolean' } }, 'required': ['withinTolerance'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-now-within-range' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realNowWithinRangeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'withinTolerance': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['withinTolerance'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-now-within-range' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realProviderDefaultOptionsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'now': { 'type': 'number' } }, 'required': ['now'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-provider-default-options' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realProviderDefaultOptionsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'now': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['now'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-provider-default-options' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realProviderInvalidOptionsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-provider-invalid-options' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realProviderInvalidOptionsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-provider-invalid-options' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realProviderOnHrtimeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hrtimeEvents': { 'items': { 'type': 'number' }, 'type': 'array' }, 'result': { 'type': 'number' } }, 'required': ['hrtimeEvents', 'result'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'rawMs': { 'type': 'number' }, 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['rawMs', 'realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-provider-on-hrtime' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realProviderOnHrtimeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hrtimeEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['hrtimeEvents', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rawMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['rawMs', 'realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-provider-on-hrtime' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realProviderOnNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'nowEvents': { 'items': { 'type': 'number' }, 'type': 'array' }, 'result': { 'type': 'number' } }, 'required': ['nowEvents', 'result'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'rawMs': { 'type': 'number' }, 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['rawMs', 'realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-provider-on-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realProviderOnNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nowEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['nowEvents', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rawMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['rawMs', 'realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-provider-on-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realProviderOnNowOffsetSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'nowEvents': { 'items': { 'type': 'number' }, 'type': 'array' }, 'result': { 'type': 'number' } }, 'required': ['nowEvents', 'result'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'rawMs': { 'type': 'number' }, 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['rawMs', 'realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-provider-on-now-offset' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realProviderOnNowOffsetNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nowEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['nowEvents', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rawMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['rawMs', 'realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-provider-on-now-offset' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realProviderThrowsOnHrtimeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookError': { 'type': 'boolean' } }, 'required': ['hookError'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'rawMs': { 'type': 'number' }, 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['rawMs', 'realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-provider-throws-on-hrtime' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realProviderThrowsOnHrtimeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookError'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rawMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['rawMs', 'realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-provider-throws-on-hrtime' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const realProviderThrowsOnNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookError': { 'type': 'boolean' } }, 'required': ['hookError'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'rawMs': { 'type': 'number' }, 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Schema }, 'required': ['rawMs', 'realProviderOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'real-provider-throws-on-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const realProviderThrowsOnNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookError'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'rawMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'realProviderOptions': RealTimeClockProviderOptionsFixtureEntity.Node }, ['rawMs', 'realProviderOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'real-provider-throws-on-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const tracedVirtualProviderHrtimeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hrtime': { 'type': 'string' } }, 'required': ['hrtime'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema, 'virtualMs': { 'type': 'number' } }, 'required': ['counterOptions', 'virtualMs'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'traced-virtual-provider-hrtime' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const tracedVirtualProviderHrtimeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hrtime': SchemaNode.defineString({ 'type': 'string' } as const) }, ['hrtime'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node, 'virtualMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['counterOptions', 'virtualMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'traced-virtual-provider-hrtime' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const tracedVirtualProviderNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'now': { 'type': 'number' } }, 'required': ['now'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema, 'virtualMs': { 'type': 'number' } }, 'required': ['counterOptions', 'virtualMs'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'traced-virtual-provider-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const tracedVirtualProviderNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'now': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['now'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node, 'virtualMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['counterOptions', 'virtualMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'traced-virtual-provider-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const twoInstancesIndependentSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'sameResults': { 'type': 'boolean' } }, 'required': ['sameResults'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'two-instances-independent' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const twoInstancesIndependentNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'sameResults': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['sameResults'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'two-instances-independent' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const virtualAdvanceReflectedSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'now': { 'type': 'number' } }, 'required': ['now'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'virtual-advance-reflected' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const virtualAdvanceReflectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'now': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['now'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'virtual-advance-reflected' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const virtualCounterDefaultOptionsSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'now': { 'type': 'number' } }, 'required': ['now'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'virtual-counter-default-options' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const virtualCounterDefaultOptionsNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'now': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['now'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'virtual-counter-default-options' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const virtualProviderInvalidCounterSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterFixture': ObjectFixtureEntity.Schema }, 'required': ['counterFixture'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'virtual-provider-invalid-counter' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const virtualProviderInvalidCounterNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterFixture': ObjectFixtureEntity.Node }, ['counterFixture'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'virtual-provider-invalid-counter' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const virtualProviderOnHrtimeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hrtimeEvents': { 'items': { 'type': 'number' }, 'type': 'array' }, 'result': { 'type': 'number' } }, 'required': ['hrtimeEvents', 'result'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'virtual-provider-on-hrtime' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const virtualProviderOnHrtimeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hrtimeEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['hrtimeEvents', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'virtual-provider-on-hrtime' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const virtualProviderOnNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'nowEvents': { 'items': { 'type': 'number' }, 'type': 'array' }, 'result': { 'type': 'number' } }, 'required': ['nowEvents', 'result'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'virtual-provider-on-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const virtualProviderOnNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nowEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'result': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['nowEvents', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'virtual-provider-on-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const virtualProviderOnNowAdvanceSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'nowEvents': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['nowEvents'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'advanceMs': { 'type': 'number' }, 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['advanceMs', 'counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'virtual-provider-on-now-advance' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const virtualProviderOnNowAdvanceNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'nowEvents': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['nowEvents'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['advanceMs', 'counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'virtual-provider-on-now-advance' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const virtualProviderThrowsOnHrtimeSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookError': { 'type': 'boolean' } }, 'required': ['hookError'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'virtual-provider-throws-on-hrtime' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const virtualProviderThrowsOnHrtimeNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookError'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'virtual-provider-throws-on-hrtime' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  const virtualProviderThrowsOnNowSchema = { 'additionalProperties': false, 'properties': { 'description': { 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'hookError': { 'type': 'boolean' } }, 'required': ['hookError'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Schema }, 'required': ['counterOptions'], 'type': 'object' }, 'name': { 'type': 'string' }, 'shape': { 'const': 'virtual-provider-throws-on-now' } }, 'required': ['description', 'expected', 'input', 'name', 'shape'], 'type': 'object' } as const;
  const virtualProviderThrowsOnNowNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['hookError'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'counterOptions': VirtualTimeCounterOptionsFixtureEntity.Node }, ['counterOptions'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'shape': SchemaNode.defineConst({}, 'virtual-provider-throws-on-now' as const) }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });

  export const Schema = {
    'oneOf': [
      clampBackwardsProviderValuesSchema, clockAsyncOnNowRejectionContainedSchema, clockErrorWithCauseSchema, clockInvalidProviderSchema,
      clockThrowsOnHrtimeSchema, clockThrowsOnNowSchema, counterInvalidOptionsSchema, counterOnAdvanceSchema,
      counterOnAdvanceSequenceSchema, counterOnAdvanceSuppressedSchema, counterOnNowMsSchema, counterOnNowMsRepeatSchema,
      counterThrowsOnAdvanceSchema, counterThrowsOnNowMsSchema, hookedClockOnHrtimeSchema, hookedClockOnHrtimeRepeatSchema,
      hookedClockOnNowSchema, hookedClockOnNowAdvancedSchema, hookedClockOnNowClampedSchema, hrtimeMonotonicSameInstanceSchema,
      hrtimeReturnsSchema, longUptimePrecisionSchema, meteredClockHrtimeSchema, meteredClockNowSchema,
      nowMonotonicSameInstanceSchema, nowReturnsSchema, offsetInvalidSchema, offsetProviderNowSchema,
      offsetProviderOffsetSchema, realHrtimePositiveSchema, realNowWithinRangeSchema, realProviderDefaultOptionsSchema,
      realProviderInvalidOptionsSchema, realProviderOnHrtimeSchema, realProviderOnNowSchema, realProviderOnNowOffsetSchema,
      realProviderThrowsOnHrtimeSchema, realProviderThrowsOnNowSchema, tracedVirtualProviderHrtimeSchema, tracedVirtualProviderNowSchema,
      twoInstancesIndependentSchema, virtualAdvanceReflectedSchema, virtualCounterDefaultOptionsSchema, virtualProviderInvalidCounterSchema,
      virtualProviderOnHrtimeSchema, virtualProviderOnNowSchema, virtualProviderOnNowAdvanceSchema, virtualProviderThrowsOnHrtimeSchema,
      virtualProviderThrowsOnNowSchema
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    clampBackwardsProviderValuesNode, clockAsyncOnNowRejectionContainedNode, clockErrorWithCauseNode, clockInvalidProviderNode,
    clockThrowsOnHrtimeNode, clockThrowsOnNowNode, counterInvalidOptionsNode, counterOnAdvanceNode,
    counterOnAdvanceSequenceNode, counterOnAdvanceSuppressedNode, counterOnNowMsNode, counterOnNowMsRepeatNode,
    counterThrowsOnAdvanceNode, counterThrowsOnNowMsNode, hookedClockOnHrtimeNode, hookedClockOnHrtimeRepeatNode,
    hookedClockOnNowNode, hookedClockOnNowAdvancedNode, hookedClockOnNowClampedNode, hrtimeMonotonicSameInstanceNode,
    hrtimeReturnsNode, longUptimePrecisionNode, meteredClockHrtimeNode, meteredClockNowNode,
    nowMonotonicSameInstanceNode, nowReturnsNode, offsetInvalidNode, offsetProviderNowNode,
    offsetProviderOffsetNode, realHrtimePositiveNode, realNowWithinRangeNode, realProviderDefaultOptionsNode,
    realProviderInvalidOptionsNode, realProviderOnHrtimeNode, realProviderOnNowNode, realProviderOnNowOffsetNode,
    realProviderThrowsOnHrtimeNode, realProviderThrowsOnNowNode, tracedVirtualProviderHrtimeNode, tracedVirtualProviderNowNode,
    twoInstancesIndependentNode, virtualAdvanceReflectedNode, virtualCounterDefaultOptionsNode, virtualProviderInvalidCounterNode,
    virtualProviderOnHrtimeNode, virtualProviderOnNowNode, virtualProviderOnNowAdvanceNode, virtualProviderThrowsOnHrtimeNode,
    virtualProviderThrowsOnNowNode
  ] as const);

  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
}
