import type { CauseNodeInterface } from './CauseNodeInterface.js';

/**
 * RFC 9457 Problem Details as produced by `BaseError.toJSON()`. Every member is optional
 * (§3.1) and the object is open to extension members (§3.2).
 */
export interface ProblemDetailsInterface {
  /** Extension: flattened cause chain, nearest first. */
  readonly 'causes'?: readonly CauseNodeInterface[];
  /** Extension: registered dotted error code. */
  readonly 'code'?: string;
  /** Extension: structured metadata captured at construction. */
  readonly 'context'?: Readonly<Record<string, unknown>>;
  /** Extension: correlation ID for distributed tracing. */
  readonly 'correlationId'?: string;
  /** Human-readable explanation specific to this occurrence. */
  readonly 'detail'?: string;
  /** URI reference identifying this specific occurrence. */
  readonly 'instance'?: string;
  readonly [extension: string]: unknown;
  /** Extension: whether the failed operation may succeed on retry. */
  readonly 'retryable'?: boolean;
  /** Extension: stack trace of the head error. */
  readonly 'stack'?: string;
  /** HTTP status code generated by the origin server for this occurrence. */
  readonly 'status'?: number;
  /** Extension: Unix millisecond timestamp at construction. */
  readonly 'timestamp'?: number;
  /** Short, human-readable summary of the problem type. */
  readonly 'title'?: string;
  /** URI reference identifying the problem type. */
  readonly 'type'?: string;
}
