import type { EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

/** The `browser/FetchTransport.loop.spec.ts` scenario case shape: one branch per `operation`. */
export namespace BrowserFetchTransportScenarioCaseEntity {
  export const Schema = { 'oneOf': [{ 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'init': { 'additionalProperties': false, 'properties': { 'method': { 'type': 'string' } }, 'required': ['method'], 'type': 'object' }, 'input': { 'type': 'string' } }, 'required': ['input', 'init'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'init': { 'additionalProperties': false, 'properties': { 'method': { 'type': 'string' } }, 'required': ['method'], 'type': 'object' }, 'input': { 'type': 'string' } }, 'required': ['input', 'init'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'operation': { 'const': 'uses-native-fetch' } }, 'required': ['description', 'expected', 'input', 'name', 'operation'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'message': { 'type': 'string' } }, 'required': ['message'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'operation': { 'const': 'rejects-node-dispatcher' } }, 'required': ['description', 'expected', 'input', 'name', 'operation'], 'type': 'object' }] } as const;

  export const Node = SchemaNode.defineOneOf({}, [SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'init': SchemaNode.defineObject({ 'type': 'object' } as const, { 'method': SchemaNode.defineString({ 'type': 'string' } as const) }, ['method'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineString({ 'type': 'string' } as const) }, ['input', 'init'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'init': SchemaNode.defineObject({ 'type': 'object' } as const, { 'method': SchemaNode.defineString({ 'type': 'string' } as const) }, ['method'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineString({ 'type': 'string' } as const) }, ['input', 'init'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'operation': SchemaNode.defineConst({}, 'uses-native-fetch' as const) }, ['description', 'expected', 'input', 'name', 'operation'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'message': SchemaNode.defineString({ 'type': 'string' } as const) }, ['message'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'operation': SchemaNode.defineConst({}, 'rejects-node-dispatcher' as const) }, ['description', 'expected', 'input', 'name', 'operation'] as const, { 'additionalProperties': false, 'patternProperties': {} })] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
}
