import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface, SchemaNodeInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

/** Builds the `{ description, expected, input, name, shape }` envelope one branch of the case union shares, varying only `shape` and the two payloads. */
class CircuitBreakerScenarioCaseBuilders {
  static scenarioSchema<const TShape extends string, TInputSchema extends object, TExpectedSchema extends object>(shape: TShape, inputSchema: TInputSchema, expectedSchema: TExpectedSchema) {
    const result = {
      'additionalProperties': false,
      'properties': {
        'description': { 'minLength': 1, 'type': 'string' },
        'expected': expectedSchema,
        'input': inputSchema,
        'name': { 'minLength': 1, 'type': 'string' },
        'shape': { 'const': shape }
      },
      'required': ['description', 'expected', 'input', 'name', 'shape'],
      'type': 'object'
    } as const;
    return result;
  }

  static scenarioNode<const TShape extends string, TInputNode extends SchemaNodeInterface<unknown, unknown>, TExpectedNode extends SchemaNodeInterface<unknown, unknown>>(shape: TShape, inputNode: TInputNode, expectedNode: TExpectedNode) {
    const result = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'expected': expectedNode,
      'input': inputNode,
      'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'shape': SchemaNode.defineConst({}, shape)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
    return result;
  }
}

const callbackAsyncHookIsolationInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'first': { 'type': 'string' }, 'resetTimeoutMs': { 'type': 'number' }, 'second': { 'type': 'string' } }, 'required': ['failureThreshold', 'first', 'resetTimeoutMs', 'second'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackAsyncHookIsolationInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['failureThreshold', 'first', 'resetTimeoutMs', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackAsyncHookIsolationExpectedSchema = { 'additionalProperties': false, 'properties': { 'recordedErrors': { 'type': 'number' }, 'rejections': { 'type': 'number' }, 'results': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['recordedErrors', 'rejections', 'results'], 'type': 'object' } as const;
const callbackAsyncHookIsolationExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'recordedErrors': SchemaNode.defineNumber({ 'type': 'number' } as const), 'rejections': SchemaNode.defineNumber({ 'type': 'number' } as const), 'results': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['recordedErrors', 'rejections', 'results'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackCloseOnSuccessThresholdInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' }, 'successThreshold': { 'type': 'number' } }, 'required': ['clock', 'failureThreshold', 'resetTimeoutMs', 'successThreshold'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackCloseOnSuccessThresholdInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'successThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['clock', 'failureThreshold', 'resetTimeoutMs', 'successThreshold'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackCloseOnSuccessThresholdExpectedSchema = { 'additionalProperties': false, 'properties': { 'states': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['states'], 'type': 'object' } as const;
const callbackCloseOnSuccessThresholdExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'states': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['states'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackConfigClassifierFailingInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackConfigClassifierFailingInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackConfigClassifierFailingExpectedSchema = { 'additionalProperties': false, 'properties': { 'states': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['states'], 'type': 'object' } as const;
const callbackConfigClassifierFailingExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'states': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['states'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackConfigClassifierRetryableInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackConfigClassifierRetryableInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackConfigClassifierRetryableExpectedSchema = { 'additionalProperties': false, 'properties': { 'finalState': { 'type': 'string' }, 'retryableFailures': { 'type': 'number' } }, 'required': ['finalState', 'retryableFailures'], 'type': 'object' } as const;
const callbackConfigClassifierRetryableExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineString({ 'type': 'string' } as const), 'retryableFailures': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['finalState', 'retryableFailures'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackConfigClassifierThrowsOriginalInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackConfigClassifierThrowsOriginalInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackConfigClassifierThrowsOriginalExpectedSchema = { 'additionalProperties': false, 'properties': { 'state': { 'type': 'string' }, 'thrown': { 'type': 'string' } }, 'required': ['state', 'thrown'], 'type': 'object' } as const;
const callbackConfigClassifierThrowsOriginalExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineString({ 'type': 'string' } as const), 'thrown': SchemaNode.defineString({ 'type': 'string' } as const) }, ['state', 'thrown'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackConfigOverridesSubclassInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackConfigOverridesSubclassInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackConfigOverridesSubclassExpectedSchema = { 'additionalProperties': false, 'properties': { 'finalState': { 'type': 'string' } }, 'required': ['finalState'], 'type': 'object' } as const;
const callbackConfigOverridesSubclassExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineString({ 'type': 'string' } as const) }, ['finalState'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackDefaultClassificationInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackDefaultClassificationInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackDefaultClassificationExpectedSchema = { 'additionalProperties': false, 'properties': { 'states': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['states'], 'type': 'object' } as const;
const callbackDefaultClassificationExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'states': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['states'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackForceOpenInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackForceOpenInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackForceOpenExpectedSchema = { 'additionalProperties': false, 'properties': { 'state': { 'type': 'string' } }, 'required': ['state'], 'type': 'object' } as const;
const callbackForceOpenExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineString({ 'type': 'string' } as const) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackHalfopenReopenInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['clock', 'failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackHalfopenReopenInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['clock', 'failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackHalfopenReopenExpectedSchema = { 'additionalProperties': false, 'properties': { 'finalState': { 'type': 'string' } }, 'required': ['finalState'], 'type': 'object' } as const;
const callbackHalfopenReopenExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineString({ 'type': 'string' } as const) }, ['finalState'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackHalfopenTransitionInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['clock', 'failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackHalfopenTransitionInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['clock', 'failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackHalfopenTransitionExpectedSchema = { 'additionalProperties': false, 'properties': { 'finalState': { 'type': 'string' } }, 'required': ['finalState'], 'type': 'object' } as const;
const callbackHalfopenTransitionExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineString({ 'type': 'string' } as const) }, ['finalState'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackHookFiresExactlyOnceInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' }, 'successThreshold': { 'type': 'number' } }, 'required': ['clock', 'failureThreshold', 'resetTimeoutMs', 'successThreshold'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackHookFiresExactlyOnceInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'successThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['clock', 'failureThreshold', 'resetTimeoutMs', 'successThreshold'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackHookFiresExactlyOnceExpectedSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const callbackHookFiresExactlyOnceExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackHookSwallowsInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'rejectFailureThreshold': { 'type': 'number' }, 'rejectResetTimeoutMs': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' }, 'tripFailureThreshold': { 'type': 'number' } }, 'required': ['failureThreshold', 'rejectFailureThreshold', 'rejectResetTimeoutMs', 'resetTimeoutMs', 'tripFailureThreshold'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackHookSwallowsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'rejectFailureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'rejectResetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'tripFailureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'rejectFailureThreshold', 'rejectResetTimeoutMs', 'resetTimeoutMs', 'tripFailureThreshold'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackHookSwallowsExpectedSchema = { 'additionalProperties': false, 'properties': { 'openState': { 'type': 'string' }, 'success': { 'type': 'string' } }, 'required': ['openState', 'success'], 'type': 'object' } as const;
const callbackHookSwallowsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'openState': SchemaNode.defineString({ 'type': 'string' } as const), 'success': SchemaNode.defineString({ 'type': 'string' } as const) }, ['openState', 'success'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackInvalidFailureThresholdInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackInvalidFailureThresholdInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackInvalidFailureThresholdExpectedSchema = { 'additionalProperties': false, 'properties': { 'throws': { 'type': 'string' } }, 'required': ['throws'], 'type': 'object' } as const;
const callbackInvalidFailureThresholdExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': SchemaNode.defineString({ 'type': 'string' } as const) }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackInvalidResetTimeoutInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackInvalidResetTimeoutInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackInvalidResetTimeoutExpectedSchema = { 'additionalProperties': false, 'properties': { 'throws': { 'type': 'string' } }, 'required': ['throws'], 'type': 'object' } as const;
const callbackInvalidResetTimeoutExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': SchemaNode.defineString({ 'type': 'string' } as const) }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackObservedCloseInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['clock', 'failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackObservedCloseInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['clock', 'failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackObservedCloseExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const callbackObservedCloseExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackObservedFailureInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackObservedFailureInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackObservedFailureExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const callbackObservedFailureExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackObservedHalfopenInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['clock', 'failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackObservedHalfopenInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['clock', 'failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackObservedHalfopenExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const callbackObservedHalfopenExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackObservedOpenInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'failureThreshold': { 'type': 'number' }, 'reopenFailureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['clock', 'failureThreshold', 'reopenFailureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackObservedOpenInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'reopenFailureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['clock', 'failureThreshold', 'reopenFailureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackObservedOpenExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const callbackObservedOpenExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackObservedRejectInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackObservedRejectInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackObservedRejectExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const callbackObservedRejectExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackObservedSuccessInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackObservedSuccessInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackObservedSuccessExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const callbackObservedSuccessExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackObservedTripOpenInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackObservedTripOpenInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackObservedTripOpenExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const callbackObservedTripOpenExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackOpenErrorInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackOpenErrorInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackOpenErrorExpectedSchema = { 'additionalProperties': false, 'properties': { 'finalState': { 'type': 'string' }, 'openError': { 'type': 'boolean' } }, 'required': ['finalState', 'openError'], 'type': 'object' } as const;
const callbackOpenErrorExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineString({ 'type': 'string' } as const), 'openError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['finalState', 'openError'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackOpenErrorNameInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'name': { 'type': 'string' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'name', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackOpenErrorNameInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'name': SchemaNode.defineString({ 'type': 'string' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'name', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackOpenErrorNameExpectedSchema = { 'additionalProperties': false, 'properties': { 'messageIncludes': { 'type': 'string' }, 'openError': { 'type': 'boolean' } }, 'required': ['messageIncludes', 'openError'], 'type': 'object' } as const;
const callbackOpenErrorNameExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'messageIncludes': SchemaNode.defineString({ 'type': 'string' } as const), 'openError': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['messageIncludes', 'openError'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackResetControlInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackResetControlInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackResetControlExpectedSchema = { 'additionalProperties': false, 'properties': { 'stateAfterReset': { 'type': 'string' } }, 'required': ['stateAfterReset'], 'type': 'object' } as const;
const callbackResetControlExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'stateAfterReset': SchemaNode.defineString({ 'type': 'string' } as const) }, ['stateAfterReset'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackResetSuccessInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackResetSuccessInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackResetSuccessExpectedSchema = { 'additionalProperties': false, 'properties': { 'result': { 'type': 'string' }, 'state': { 'type': 'string' } }, 'required': ['result', 'state'], 'type': 'object' } as const;
const callbackResetSuccessExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineString({ 'type': 'string' } as const), 'state': SchemaNode.defineString({ 'type': 'string' } as const) }, ['result', 'state'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackStartsClosedInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackStartsClosedInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackStartsClosedExpectedSchema = { 'additionalProperties': false, 'properties': { 'state': { 'type': 'string' } }, 'required': ['state'], 'type': 'object' } as const;
const callbackStartsClosedExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'state': SchemaNode.defineString({ 'type': 'string' } as const) }, ['state'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackStateEntityInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'states': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['states'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackStateEntityInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'states': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['states'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackStateEntityExpectedSchema = { 'additionalProperties': false, 'properties': { 'invalidState': { 'type': 'string' }, 'validStates': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['invalidState', 'validStates'], 'type': 'object' } as const;
const callbackStateEntityExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'invalidState': SchemaNode.defineString({ 'type': 'string' } as const), 'validStates': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['invalidState', 'validStates'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackStaysOpenInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['clock', 'failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackStaysOpenInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['clock', 'failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackStaysOpenExpectedSchema = { 'additionalProperties': false, 'properties': { 'finalState': { 'type': 'string' } }, 'required': ['finalState'], 'type': 'object' } as const;
const callbackStaysOpenExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineString({ 'type': 'string' } as const) }, ['finalState'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackSubclassClassifierInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackSubclassClassifierInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackSubclassClassifierExpectedSchema = { 'additionalProperties': false, 'properties': { 'finalState': { 'type': 'string' } }, 'required': ['finalState'], 'type': 'object' } as const;
const callbackSubclassClassifierExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineString({ 'type': 'string' } as const) }, ['finalState'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackSuccessResetsInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' }, 'sequence': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['failureThreshold', 'resetTimeoutMs', 'sequence'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackSuccessResetsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'sequence': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['failureThreshold', 'resetTimeoutMs', 'sequence'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackSuccessResetsExpectedSchema = { 'additionalProperties': false, 'properties': { 'finalState': { 'type': 'string' }, 'stateBeforeFinalFailure': { 'type': 'string' } }, 'required': ['finalState', 'stateBeforeFinalFailure'], 'type': 'object' } as const;
const callbackSuccessResetsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'finalState': SchemaNode.defineString({ 'type': 'string' } as const), 'stateBeforeFinalFailure': SchemaNode.defineString({ 'type': 'string' } as const) }, ['finalState', 'stateBeforeFinalFailure'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const callbackTripsOpenInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'failures': { 'type': 'number' }, 'failureThreshold': { 'type': 'number' }, 'resetTimeoutMs': { 'type': 'number' } }, 'required': ['failures', 'failureThreshold', 'resetTimeoutMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const callbackTripsOpenInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'failures': SchemaNode.defineNumber({ 'type': 'number' } as const), 'failureThreshold': SchemaNode.defineNumber({ 'type': 'number' } as const), 'resetTimeoutMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['failures', 'failureThreshold', 'resetTimeoutMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const callbackTripsOpenExpectedSchema = { 'additionalProperties': false, 'properties': { 'states': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['states'], 'type': 'object' } as const;
const callbackTripsOpenExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'states': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['states'] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** The scenario case shapes `circuit-breaker.loop.spec.ts` exercises. */
export namespace CircuitBreakerScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-async-hook-isolation', callbackAsyncHookIsolationInputSchema, callbackAsyncHookIsolationExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-close-on-success-threshold', callbackCloseOnSuccessThresholdInputSchema, callbackCloseOnSuccessThresholdExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-config-classifier-failing', callbackConfigClassifierFailingInputSchema, callbackConfigClassifierFailingExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-config-classifier-retryable', callbackConfigClassifierRetryableInputSchema, callbackConfigClassifierRetryableExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-config-classifier-throws-original', callbackConfigClassifierThrowsOriginalInputSchema, callbackConfigClassifierThrowsOriginalExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-config-overrides-subclass', callbackConfigOverridesSubclassInputSchema, callbackConfigOverridesSubclassExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-default-classification', callbackDefaultClassificationInputSchema, callbackDefaultClassificationExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-force-open', callbackForceOpenInputSchema, callbackForceOpenExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-halfopen-reopen', callbackHalfopenReopenInputSchema, callbackHalfopenReopenExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-halfopen-transition', callbackHalfopenTransitionInputSchema, callbackHalfopenTransitionExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-hook-fires-exactly-once', callbackHookFiresExactlyOnceInputSchema, callbackHookFiresExactlyOnceExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-hook-swallows', callbackHookSwallowsInputSchema, callbackHookSwallowsExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-invalid-failure-threshold', callbackInvalidFailureThresholdInputSchema, callbackInvalidFailureThresholdExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-invalid-reset-timeout', callbackInvalidResetTimeoutInputSchema, callbackInvalidResetTimeoutExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-observed-close', callbackObservedCloseInputSchema, callbackObservedCloseExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-observed-failure', callbackObservedFailureInputSchema, callbackObservedFailureExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-observed-halfopen', callbackObservedHalfopenInputSchema, callbackObservedHalfopenExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-observed-open', callbackObservedOpenInputSchema, callbackObservedOpenExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-observed-reject', callbackObservedRejectInputSchema, callbackObservedRejectExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-observed-success', callbackObservedSuccessInputSchema, callbackObservedSuccessExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-observed-trip-open', callbackObservedTripOpenInputSchema, callbackObservedTripOpenExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-open-error', callbackOpenErrorInputSchema, callbackOpenErrorExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-open-error-name', callbackOpenErrorNameInputSchema, callbackOpenErrorNameExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-reset-control', callbackResetControlInputSchema, callbackResetControlExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-reset-success', callbackResetSuccessInputSchema, callbackResetSuccessExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-starts-closed', callbackStartsClosedInputSchema, callbackStartsClosedExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-state-entity', callbackStateEntityInputSchema, callbackStateEntityExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-stays-open', callbackStaysOpenInputSchema, callbackStaysOpenExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-subclass-classifier', callbackSubclassClassifierInputSchema, callbackSubclassClassifierExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-success-resets', callbackSuccessResetsInputSchema, callbackSuccessResetsExpectedSchema),
      CircuitBreakerScenarioCaseBuilders.scenarioSchema('cb-trips-open', callbackTripsOpenInputSchema, callbackTripsOpenExpectedSchema)
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-async-hook-isolation', callbackAsyncHookIsolationInputNode, callbackAsyncHookIsolationExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-close-on-success-threshold', callbackCloseOnSuccessThresholdInputNode, callbackCloseOnSuccessThresholdExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-config-classifier-failing', callbackConfigClassifierFailingInputNode, callbackConfigClassifierFailingExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-config-classifier-retryable', callbackConfigClassifierRetryableInputNode, callbackConfigClassifierRetryableExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-config-classifier-throws-original', callbackConfigClassifierThrowsOriginalInputNode, callbackConfigClassifierThrowsOriginalExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-config-overrides-subclass', callbackConfigOverridesSubclassInputNode, callbackConfigOverridesSubclassExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-default-classification', callbackDefaultClassificationInputNode, callbackDefaultClassificationExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-force-open', callbackForceOpenInputNode, callbackForceOpenExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-halfopen-reopen', callbackHalfopenReopenInputNode, callbackHalfopenReopenExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-halfopen-transition', callbackHalfopenTransitionInputNode, callbackHalfopenTransitionExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-hook-fires-exactly-once', callbackHookFiresExactlyOnceInputNode, callbackHookFiresExactlyOnceExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-hook-swallows', callbackHookSwallowsInputNode, callbackHookSwallowsExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-invalid-failure-threshold', callbackInvalidFailureThresholdInputNode, callbackInvalidFailureThresholdExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-invalid-reset-timeout', callbackInvalidResetTimeoutInputNode, callbackInvalidResetTimeoutExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-observed-close', callbackObservedCloseInputNode, callbackObservedCloseExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-observed-failure', callbackObservedFailureInputNode, callbackObservedFailureExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-observed-halfopen', callbackObservedHalfopenInputNode, callbackObservedHalfopenExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-observed-open', callbackObservedOpenInputNode, callbackObservedOpenExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-observed-reject', callbackObservedRejectInputNode, callbackObservedRejectExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-observed-success', callbackObservedSuccessInputNode, callbackObservedSuccessExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-observed-trip-open', callbackObservedTripOpenInputNode, callbackObservedTripOpenExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-open-error', callbackOpenErrorInputNode, callbackOpenErrorExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-open-error-name', callbackOpenErrorNameInputNode, callbackOpenErrorNameExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-reset-control', callbackResetControlInputNode, callbackResetControlExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-reset-success', callbackResetSuccessInputNode, callbackResetSuccessExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-starts-closed', callbackStartsClosedInputNode, callbackStartsClosedExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-state-entity', callbackStateEntityInputNode, callbackStateEntityExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-stays-open', callbackStaysOpenInputNode, callbackStaysOpenExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-subclass-classifier', callbackSubclassClassifierInputNode, callbackSubclassClassifierExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-success-resets', callbackSuccessResetsInputNode, callbackSuccessResetsExpectedNode),
    CircuitBreakerScenarioCaseBuilders.scenarioNode('cb-trips-open', callbackTripsOpenInputNode, callbackTripsOpenExpectedNode)
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
