import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface, SchemaNodeInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

/** Builds the `{ description, expected, input, name, shape }` envelope one branch of the case union shares, varying only `shape` and the two payloads. */
class DeadLetterQueueScenarioCaseBuilders {
  static scenarioSchema<const TShape extends string, TInputSchema extends object, TExpectedSchema extends object>(shape: TShape, inputSchema: TInputSchema, expectedSchema: TExpectedSchema) {
    const result = {
      'additionalProperties': false,
      'properties': {
        'description': { 'minLength': 1, 'type': 'string' },
        'expected': expectedSchema,
        'input': inputSchema,
        'name': { 'minLength': 1, 'type': 'string' },
        'shape': { 'const': shape }
      },
      'required': ['description', 'expected', 'input', 'name', 'shape'],
      'type': 'object'
    } as const;
    return result;
  }

  static scenarioNode<const TShape extends string, TInputNode extends SchemaNodeInterface<unknown, unknown>, TExpectedNode extends SchemaNodeInterface<unknown, unknown>>(shape: TShape, inputNode: TInputNode, expectedNode: TExpectedNode) {
    const result = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'expected': expectedNode,
      'input': inputNode,
      'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'shape': SchemaNode.defineConst({}, shape)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
    return result;
  }
}

const deadLetterQueueAbortedSignalInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'aborted': { 'type': 'boolean' }, 'item': { 'type': 'string' }, 'reason': { 'type': 'string' } }, 'required': ['aborted', 'item', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueAbortedSignalInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'aborted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'item': SchemaNode.defineString({ 'type': 'string' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['aborted', 'item', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueAbortedSignalExpectedSchema = { 'additionalProperties': false, 'properties': { 'error': { 'type': 'string' } }, 'required': ['error'], 'type': 'object' } as const;
const deadLetterQueueAbortedSignalExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'error': SchemaNode.defineString({ 'type': 'string' } as const) }, ['error'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueAsyncHookIsolationInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'first': { 'type': 'string' }, 'second': { 'type': 'string' } }, 'required': ['first', 'second'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueAsyncHookIsolationInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['first', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueAsyncHookIsolationExpectedSchema = { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'hookName': { 'type': 'string' }, 'rejectionEvents': { 'type': 'number' } }, 'required': ['hookErrorCount', 'hookName', 'rejectionEvents'], 'type': 'object' } as const;
const deadLetterQueueAsyncHookIsolationExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'hookName': SchemaNode.defineString({ 'type': 'string' } as const), 'rejectionEvents': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['hookErrorCount', 'hookName', 'rejectionEvents'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueDrainAbortInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'abortAfterTick': { 'type': 'boolean' }, 'items': { 'items': { 'type': 'number' }, 'type': 'array' }, 'reason': { 'type': 'string' } }, 'required': ['abortAfterTick', 'items', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueDrainAbortInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'abortAfterTick': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['abortAfterTick', 'items', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueDrainAbortExpectedSchema = { 'additionalProperties': false, 'properties': { 'drainedCount': { 'type': 'number' } }, 'required': ['drainedCount'], 'type': 'object' } as const;
const deadLetterQueueDrainAbortExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'drainedCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['drainedCount'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueDrainAbortSignalInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'aborted': { 'type': 'boolean' }, 'items': { 'items': { 'type': 'string' }, 'type': 'array' }, 'reason': { 'type': 'string' } }, 'required': ['aborted', 'items', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueDrainAbortSignalInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'aborted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['aborted', 'items', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueDrainAbortSignalExpectedSchema = { 'additionalProperties': false, 'properties': { 'collected': { 'type': 'number' } }, 'required': ['collected'], 'type': 'object' } as const;
const deadLetterQueueDrainAbortSignalExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'collected': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['collected'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueDrainCloseInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'closeAfterEnqueue': { 'type': 'boolean' }, 'items': { 'items': { 'type': 'string' }, 'type': 'array' }, 'reason': { 'type': 'string' } }, 'required': ['closeAfterEnqueue', 'items', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueDrainCloseInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'closeAfterEnqueue': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['closeAfterEnqueue', 'items', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueDrainCloseExpectedSchema = { 'additionalProperties': false, 'properties': { 'drainedCount': { 'type': 'number' } }, 'required': ['drainedCount'], 'type': 'object' } as const;
const deadLetterQueueDrainCloseExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'drainedCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['drainedCount'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueDrainFifoInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'closeAfterEnqueue': { 'type': 'boolean' }, 'items': { 'items': { 'type': 'string' }, 'type': 'array' }, 'reason': { 'type': 'string' } }, 'required': ['closeAfterEnqueue', 'items', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueDrainFifoInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'closeAfterEnqueue': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['closeAfterEnqueue', 'items', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueDrainFifoExpectedSchema = { 'additionalProperties': false, 'properties': { 'drained': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['drained'], 'type': 'object' } as const;
const deadLetterQueueDrainFifoExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'drained': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['drained'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueDrainWakeInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'items': { 'items': { 'type': 'string' }, 'type': 'array' }, 'reason': { 'type': 'string' }, 'wakeAfterEnqueue': { 'type': 'boolean' } }, 'required': ['items', 'reason', 'wakeAfterEnqueue'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueDrainWakeInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'reason': SchemaNode.defineString({ 'type': 'string' } as const), 'wakeAfterEnqueue': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['items', 'reason', 'wakeAfterEnqueue'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueDrainWakeExpectedSchema = { 'additionalProperties': false, 'properties': { 'drained': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['drained'], 'type': 'object' } as const;
const deadLetterQueueDrainWakeExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'drained': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['drained'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueEnqueueInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'defaultItem': { 'type': 'string' }, 'defaultReason': { 'type': 'string' }, 'secondErrorMessage': { 'type': 'string' }, 'secondItem': { 'type': 'string' }, 'secondReason': { 'type': 'string' }, 'withClockMs': { 'type': 'number' } }, 'required': ['defaultItem', 'defaultReason', 'secondErrorMessage', 'secondItem', 'secondReason', 'withClockMs'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueEnqueueInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'defaultItem': SchemaNode.defineString({ 'type': 'string' } as const), 'defaultReason': SchemaNode.defineString({ 'type': 'string' } as const), 'secondErrorMessage': SchemaNode.defineString({ 'type': 'string' } as const), 'secondItem': SchemaNode.defineString({ 'type': 'string' } as const), 'secondReason': SchemaNode.defineString({ 'type': 'string' } as const), 'withClockMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['defaultItem', 'defaultReason', 'secondErrorMessage', 'secondItem', 'secondReason', 'withClockMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueEnqueueExpectedSchema = { 'additionalProperties': false, 'properties': { 'size': { 'type': 'number' }, 'sizeWithError': { 'type': 'number' } }, 'required': ['size', 'sizeWithError'], 'type': 'object' } as const;
const deadLetterQueueEnqueueExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'size': SchemaNode.defineNumber({ 'type': 'number' } as const), 'sizeWithError': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['size', 'sizeWithError'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueEnqueueErrorsInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'scenarios': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['capacity', 'scenarios'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueEnqueueErrorsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'scenarios': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['capacity', 'scenarios'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueEnqueueErrorsExpectedSchema = { 'additionalProperties': false, 'properties': { 'errors': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['errors'], 'type': 'object' } as const;
const deadLetterQueueEnqueueErrorsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'errors': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['errors'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueEntryFieldsInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'clockMs': { 'type': 'number' }, 'errorMessage': { 'type': 'string' }, 'item': { 'type': 'string' }, 'reason': { 'type': 'string' } }, 'required': ['clockMs', 'errorMessage', 'item', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueEntryFieldsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'clockMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'errorMessage': SchemaNode.defineString({ 'type': 'string' } as const), 'item': SchemaNode.defineString({ 'type': 'string' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['clockMs', 'errorMessage', 'item', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueEntryFieldsExpectedSchema = { 'additionalProperties': false, 'properties': { 'enqueuedAtMs': { 'type': 'number' }, 'hasId': { 'type': 'boolean' }, 'item': { 'type': 'string' }, 'reason': { 'type': 'string' } }, 'required': ['enqueuedAtMs', 'hasId', 'item', 'reason'], 'type': 'object' } as const;
const deadLetterQueueEntryFieldsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'enqueuedAtMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'hasId': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'item': SchemaNode.defineString({ 'type': 'string' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['enqueuedAtMs', 'hasId', 'item', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueFanoutInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'fanout': { 'type': 'boolean' }, 'items': { 'items': { 'type': 'string' }, 'type': 'array' }, 'reason': { 'type': 'string' } }, 'required': ['fanout', 'items', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueFanoutInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'fanout': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['fanout', 'items', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueFanoutExpectedSchema = { 'additionalProperties': false, 'properties': { 'combined': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['combined'], 'type': 'object' } as const;
const deadLetterQueueFanoutExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'combined': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['combined'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueHookSwallowsInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'items': { 'items': { 'type': 'string' }, 'type': 'array' }, 'overflowCapacity': { 'type': 'number' }, 'reason': { 'type': 'string' } }, 'required': ['items', 'overflowCapacity', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueHookSwallowsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'overflowCapacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['items', 'overflowCapacity', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueHookSwallowsExpectedSchema = { 'additionalProperties': false, 'properties': { 'abortedRejects': { 'type': 'boolean' }, 'closed': { 'type': 'boolean' }, 'size': { 'type': 'number' } }, 'required': ['abortedRejects', 'closed', 'size'], 'type': 'object' } as const;
const deadLetterQueueHookSwallowsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'abortedRejects': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'closed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'size': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['abortedRejects', 'closed', 'size'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueInvalidCapacityInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' } }, 'required': ['capacity'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueInvalidCapacityInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['capacity'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueInvalidCapacityExpectedSchema = { 'additionalProperties': false, 'properties': { 'throws': { 'type': 'string' } }, 'required': ['throws'], 'type': 'object' } as const;
const deadLetterQueueInvalidCapacityExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': SchemaNode.defineString({ 'type': 'string' } as const) }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueObservedAbortInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'aborted': { 'type': 'boolean' } }, 'required': ['aborted'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueObservedAbortInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'aborted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['aborted'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueObservedAbortExpectedSchema = { 'additionalProperties': false, 'properties': { 'eventsContain': { 'type': 'string' } }, 'required': ['eventsContain'], 'type': 'object' } as const;
const deadLetterQueueObservedAbortExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'eventsContain': SchemaNode.defineString({ 'type': 'string' } as const) }, ['eventsContain'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueObservedCloseInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'closed': { 'type': 'boolean' } }, 'required': ['closed'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueObservedCloseInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'closed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['closed'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueObservedCloseExpectedSchema = { 'additionalProperties': false, 'properties': { 'eventsContain': { 'type': 'string' } }, 'required': ['eventsContain'], 'type': 'object' } as const;
const deadLetterQueueObservedCloseExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'eventsContain': SchemaNode.defineString({ 'type': 'string' } as const) }, ['eventsContain'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueObservedDequeueInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'item': { 'type': 'string' }, 'reason': { 'type': 'string' } }, 'required': ['item', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueObservedDequeueInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'item': SchemaNode.defineString({ 'type': 'string' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['item', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueObservedDequeueExpectedSchema = { 'additionalProperties': false, 'properties': { 'eventsContain': { 'additionalProperties': false, 'properties': { 'item': { 'type': 'string' }, 'type': { 'type': 'string' } }, 'required': ['item', 'type'], 'type': 'object' } }, 'required': ['eventsContain'], 'type': 'object' } as const;
const deadLetterQueueObservedDequeueExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'eventsContain': SchemaNode.defineObject({ 'type': 'object' } as const, { 'item': SchemaNode.defineString({ 'type': 'string' } as const), 'type': SchemaNode.defineString({ 'type': 'string' } as const) }, ['item', 'type'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['eventsContain'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueObservedEnqueueInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'item': { 'type': 'string' }, 'reason': { 'type': 'string' } }, 'required': ['item', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueObservedEnqueueInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'item': SchemaNode.defineString({ 'type': 'string' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['item', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueObservedEnqueueExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'additionalProperties': false, 'properties': { 'item': { 'type': 'string' }, 'type': { 'type': 'string' } }, 'required': ['item', 'type'], 'type': 'object' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const deadLetterQueueObservedEnqueueExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'item': SchemaNode.defineString({ 'type': 'string' } as const), 'type': SchemaNode.defineString({ 'type': 'string' } as const) }, ['item', 'type'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueObservedOverflowInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'capacity': { 'type': 'number' }, 'items': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['capacity', 'items'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueObservedOverflowInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'capacity': SchemaNode.defineNumber({ 'type': 'number' } as const), 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['capacity', 'items'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueObservedOverflowExpectedSchema = { 'additionalProperties': false, 'properties': { 'eventsContain': { 'type': 'string' } }, 'required': ['eventsContain'], 'type': 'object' } as const;
const deadLetterQueueObservedOverflowExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'eventsContain': SchemaNode.defineString({ 'type': 'string' } as const) }, ['eventsContain'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueSingleConsumerInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'items': { 'items': { 'type': 'string' }, 'type': 'array' }, 'reason': { 'type': 'string' }, 'secondConsumer': { 'type': 'boolean' } }, 'required': ['items', 'reason', 'secondConsumer'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueSingleConsumerInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'items': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'reason': SchemaNode.defineString({ 'type': 'string' } as const), 'secondConsumer': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['items', 'reason', 'secondConsumer'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueSingleConsumerExpectedSchema = { 'additionalProperties': false, 'properties': { 'firstCollector': { 'items': { 'type': 'string' }, 'type': 'array' }, 'secondCollector': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['firstCollector', 'secondCollector'], 'type': 'object' } as const;
const deadLetterQueueSingleConsumerExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'firstCollector': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'secondCollector': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['firstCollector', 'secondCollector'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const deadLetterQueueSizeInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'drainOnce': { 'type': 'boolean' }, 'enqueue': { 'type': 'string' }, 'initial': { 'type': 'number' }, 'reason': { 'type': 'string' } }, 'required': ['drainOnce', 'enqueue', 'initial', 'reason'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const deadLetterQueueSizeInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'drainOnce': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'enqueue': SchemaNode.defineString({ 'type': 'string' } as const), 'initial': SchemaNode.defineNumber({ 'type': 'number' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['drainOnce', 'enqueue', 'initial', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const deadLetterQueueSizeExpectedSchema = { 'additionalProperties': false, 'properties': { 'sizeAfterDrain': { 'type': 'number' }, 'sizeBefore': { 'type': 'number' } }, 'required': ['sizeAfterDrain', 'sizeBefore'], 'type': 'object' } as const;
const deadLetterQueueSizeExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'sizeAfterDrain': SchemaNode.defineNumber({ 'type': 'number' } as const), 'sizeBefore': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['sizeAfterDrain', 'sizeBefore'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const entityDeadLetterQueueEntryInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'invalid': { 'additionalProperties': false, 'properties': { 'enqueuedAtMs': { 'type': 'number' }, 'id': { 'type': 'string' }, 'reason': { 'type': 'string' } }, 'required': ['enqueuedAtMs', 'id', 'reason'], 'type': 'object' }, 'valid': { 'additionalProperties': false, 'properties': { 'enqueuedAtMs': { 'type': 'number' }, 'id': { 'type': 'string' }, 'reason': { 'type': 'string' } }, 'required': ['enqueuedAtMs', 'id', 'reason'], 'type': 'object' } }, 'required': ['invalid', 'valid'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const entityDeadLetterQueueEntryInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'invalid': SchemaNode.defineObject({ 'type': 'object' } as const, { 'enqueuedAtMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'id': SchemaNode.defineString({ 'type': 'string' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['enqueuedAtMs', 'id', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'valid': SchemaNode.defineObject({ 'type': 'object' } as const, { 'enqueuedAtMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'id': SchemaNode.defineString({ 'type': 'string' } as const), 'reason': SchemaNode.defineString({ 'type': 'string' } as const) }, ['enqueuedAtMs', 'id', 'reason'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['invalid', 'valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const entityDeadLetterQueueEntryExpectedSchema = { 'additionalProperties': false, 'properties': { 'invalid': { 'type': 'boolean' }, 'valid': { 'type': 'boolean' } }, 'required': ['invalid', 'valid'], 'type': 'object' } as const;
const entityDeadLetterQueueEntryExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'invalid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['invalid', 'valid'] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** The scenario case shapes `dead-letter-queue.loop.spec.ts` exercises. */
export namespace DeadLetterQueueScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-aborted-signal', deadLetterQueueAbortedSignalInputSchema, deadLetterQueueAbortedSignalExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-async-hook-isolation', deadLetterQueueAsyncHookIsolationInputSchema, deadLetterQueueAsyncHookIsolationExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-drain-abort', deadLetterQueueDrainAbortInputSchema, deadLetterQueueDrainAbortExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-drain-abort-signal', deadLetterQueueDrainAbortSignalInputSchema, deadLetterQueueDrainAbortSignalExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-drain-close', deadLetterQueueDrainCloseInputSchema, deadLetterQueueDrainCloseExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-drain-fifo', deadLetterQueueDrainFifoInputSchema, deadLetterQueueDrainFifoExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-drain-wake', deadLetterQueueDrainWakeInputSchema, deadLetterQueueDrainWakeExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-enqueue', deadLetterQueueEnqueueInputSchema, deadLetterQueueEnqueueExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-enqueue-errors', deadLetterQueueEnqueueErrorsInputSchema, deadLetterQueueEnqueueErrorsExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-entry-fields', deadLetterQueueEntryFieldsInputSchema, deadLetterQueueEntryFieldsExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-fanout', deadLetterQueueFanoutInputSchema, deadLetterQueueFanoutExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-hook-swallows', deadLetterQueueHookSwallowsInputSchema, deadLetterQueueHookSwallowsExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-invalid-capacity', deadLetterQueueInvalidCapacityInputSchema, deadLetterQueueInvalidCapacityExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-observed-abort', deadLetterQueueObservedAbortInputSchema, deadLetterQueueObservedAbortExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-observed-close', deadLetterQueueObservedCloseInputSchema, deadLetterQueueObservedCloseExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-observed-dequeue', deadLetterQueueObservedDequeueInputSchema, deadLetterQueueObservedDequeueExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-observed-enqueue', deadLetterQueueObservedEnqueueInputSchema, deadLetterQueueObservedEnqueueExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-observed-overflow', deadLetterQueueObservedOverflowInputSchema, deadLetterQueueObservedOverflowExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-single-consumer', deadLetterQueueSingleConsumerInputSchema, deadLetterQueueSingleConsumerExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('dlq-size', deadLetterQueueSizeInputSchema, deadLetterQueueSizeExpectedSchema),
      DeadLetterQueueScenarioCaseBuilders.scenarioSchema('entity-dlq-entry', entityDeadLetterQueueEntryInputSchema, entityDeadLetterQueueEntryExpectedSchema)
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-aborted-signal', deadLetterQueueAbortedSignalInputNode, deadLetterQueueAbortedSignalExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-async-hook-isolation', deadLetterQueueAsyncHookIsolationInputNode, deadLetterQueueAsyncHookIsolationExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-drain-abort', deadLetterQueueDrainAbortInputNode, deadLetterQueueDrainAbortExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-drain-abort-signal', deadLetterQueueDrainAbortSignalInputNode, deadLetterQueueDrainAbortSignalExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-drain-close', deadLetterQueueDrainCloseInputNode, deadLetterQueueDrainCloseExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-drain-fifo', deadLetterQueueDrainFifoInputNode, deadLetterQueueDrainFifoExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-drain-wake', deadLetterQueueDrainWakeInputNode, deadLetterQueueDrainWakeExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-enqueue', deadLetterQueueEnqueueInputNode, deadLetterQueueEnqueueExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-enqueue-errors', deadLetterQueueEnqueueErrorsInputNode, deadLetterQueueEnqueueErrorsExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-entry-fields', deadLetterQueueEntryFieldsInputNode, deadLetterQueueEntryFieldsExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-fanout', deadLetterQueueFanoutInputNode, deadLetterQueueFanoutExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-hook-swallows', deadLetterQueueHookSwallowsInputNode, deadLetterQueueHookSwallowsExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-invalid-capacity', deadLetterQueueInvalidCapacityInputNode, deadLetterQueueInvalidCapacityExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-observed-abort', deadLetterQueueObservedAbortInputNode, deadLetterQueueObservedAbortExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-observed-close', deadLetterQueueObservedCloseInputNode, deadLetterQueueObservedCloseExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-observed-dequeue', deadLetterQueueObservedDequeueInputNode, deadLetterQueueObservedDequeueExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-observed-enqueue', deadLetterQueueObservedEnqueueInputNode, deadLetterQueueObservedEnqueueExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-observed-overflow', deadLetterQueueObservedOverflowInputNode, deadLetterQueueObservedOverflowExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-single-consumer', deadLetterQueueSingleConsumerInputNode, deadLetterQueueSingleConsumerExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('dlq-size', deadLetterQueueSizeInputNode, deadLetterQueueSizeExpectedNode),
    DeadLetterQueueScenarioCaseBuilders.scenarioNode('entity-dlq-entry', entityDeadLetterQueueEntryInputNode, entityDeadLetterQueueEntryExpectedNode)
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
