import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface, SchemaNodeInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

/** Builds the `{ description, expected, input, name, shape }` envelope one branch of the case union shares, varying only `shape` and the two payloads. */
class KeyedRateLimiterScenarioCaseBuilders {
  static scenarioSchema<const TShape extends string, TInputSchema extends object, TExpectedSchema extends object>(shape: TShape, inputSchema: TInputSchema, expectedSchema: TExpectedSchema) {
    const result = {
      'additionalProperties': false,
      'properties': {
        'description': { 'minLength': 1, 'type': 'string' },
        'expected': expectedSchema,
        'input': inputSchema,
        'name': { 'minLength': 1, 'type': 'string' },
        'shape': { 'const': shape }
      },
      'required': ['description', 'expected', 'input', 'name', 'shape'],
      'type': 'object'
    } as const;
    return result;
  }

  static scenarioNode<const TShape extends string, TInputNode extends SchemaNodeInterface<unknown, unknown>, TExpectedNode extends SchemaNodeInterface<unknown, unknown>>(shape: TShape, inputNode: TInputNode, expectedNode: TExpectedNode) {
    const result = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'expected': expectedNode,
      'input': inputNode,
      'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'shape': SchemaNode.defineConst({}, shape)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
    return result;
  }
}

const consumeDefaultResultInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' }, 'tokens': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond', 'tokens'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const consumeDefaultResultInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const), 'tokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond', 'tokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const consumeDefaultResultExpectedSchema = { 'additionalProperties': false, 'properties': { 'result': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['result'], 'type': 'object' } as const;
const consumeDefaultResultExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const consumeIndependentKeysInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const consumeIndependentKeysInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const consumeIndependentKeysExpectedSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const consumeIndependentKeysExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });

const consumeRequestedTokensInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const consumeRequestedTokensInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const consumeRequestedTokensExpectedSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const consumeRequestedTokensExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });

const consumeSameKeyExhaustsInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const consumeSameKeyExhaustsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const consumeSameKeyExhaustsExpectedSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const consumeSameKeyExhaustsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });

const consumeStrategyCreatedOnceInputSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const consumeStrategyCreatedOnceInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });
const consumeStrategyCreatedOnceExpectedSchema = { 'additionalProperties': false, 'properties': { 'factoryCalls': { 'type': 'number' }, 'result': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['factoryCalls', 'result'], 'type': 'object' } as const;
const consumeStrategyCreatedOnceExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'factoryCalls': SchemaNode.defineNumber({ 'type': 'number' } as const), 'result': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['factoryCalls', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const entitiesInvalidInputSchema = { 'additionalProperties': false, 'properties': { 'rateLimitRequest': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'tokens': { 'type': 'number' } }, 'required': ['key', 'tokens'], 'type': 'object' }, 'registry': { 'additionalProperties': false, 'properties': { 'maximumKeys': { 'type': 'number' } }, 'required': ['maximumKeys'], 'type': 'object' } }, 'required': ['rateLimitRequest', 'registry'], 'type': 'object' } as const;
const entitiesInvalidInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'rateLimitRequest': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'tokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['key', 'tokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'registry': SchemaNode.defineObject({ 'type': 'object' } as const, { 'maximumKeys': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['maximumKeys'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['rateLimitRequest', 'registry'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const entitiesInvalidExpectedSchema = { 'additionalProperties': false, 'properties': { 'accepted': { 'type': 'boolean' } }, 'required': ['accepted'], 'type': 'object' } as const;
const entitiesInvalidExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'accepted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['accepted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const entitiesValidInputSchema = { 'additionalProperties': false, 'properties': { 'rateLimitRequest': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'tokens': { 'type': 'number' } }, 'required': ['key', 'tokens'], 'type': 'object' }, 'registry': { 'additionalProperties': false, 'properties': { 'keyIdleTtlMs': { 'type': 'number' }, 'maximumKeys': { 'type': 'number' } }, 'required': ['keyIdleTtlMs', 'maximumKeys'], 'type': 'object' } }, 'required': ['rateLimitRequest', 'registry'], 'type': 'object' } as const;
const entitiesValidInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'rateLimitRequest': SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'tokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['key', 'tokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'registry': SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyIdleTtlMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'maximumKeys': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['keyIdleTtlMs', 'maximumKeys'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['rateLimitRequest', 'registry'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const entitiesValidExpectedSchema = { 'additionalProperties': false, 'properties': { 'accepted': { 'type': 'boolean' } }, 'required': ['accepted'], 'type': 'object' } as const;
const entitiesValidExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'accepted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['accepted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const evictsIdleKeyAtCapacityInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'maximumKeys': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'maximumKeys', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const evictsIdleKeyAtCapacityInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'maximumKeys': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'maximumKeys', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const evictsIdleKeyAtCapacityExpectedSchema = { 'additionalProperties': false, 'properties': { 'created': { 'items': { 'type': 'string' }, 'type': 'array' }, 'evicted': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['created', 'evicted'], 'type': 'object' } as const;
const evictsIdleKeyAtCapacityExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'created': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'evicted': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['created', 'evicted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const genericAcquisitionObservationInputSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const genericAcquisitionObservationInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });
const genericAcquisitionObservationExpectedSchema = { 'additionalProperties': false, 'properties': { 'acquired': { 'items': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'result': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['key', 'result'], 'type': 'object' }, 'type': 'array' } }, 'required': ['acquired'], 'type': 'object' } as const;
const genericAcquisitionObservationExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'acquired': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'result': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['key', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['acquired'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const genericCacheBoundaryInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'allowance': { 'type': 'number' }, 'maximumKeys': { 'type': 'number' } }, 'required': ['allowance', 'maximumKeys'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const genericCacheBoundaryInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'allowance': SchemaNode.defineNumber({ 'type': 'number' } as const), 'maximumKeys': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['allowance', 'maximumKeys'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const genericCacheBoundaryExpectedSchema = { 'additionalProperties': false, 'properties': { 'creations': { 'items': { 'items': { 'oneOf': [{ 'type': 'string' }, { 'type': 'number' }] }, 'type': 'array' }, 'type': 'array' } }, 'required': ['creations'], 'type': 'object' } as const;
const genericCacheBoundaryExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'creations': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineOneOf({}, [SchemaNode.defineString({ 'type': 'string' } as const), SchemaNode.defineNumber({ 'type': 'number' } as const)] as const), undefined), undefined) }, ['creations'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const genericFakeStrategyInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'allowance': { 'type': 'number' } }, 'required': ['allowance'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const genericFakeStrategyInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'allowance': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['allowance'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const genericFakeStrategyExpectedSchema = { 'additionalProperties': false, 'properties': { 'firstResult': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' }, 'secondResult': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['firstResult', 'secondResult'], 'type': 'object' } as const;
const genericFakeStrategyExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'firstResult': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'secondResult': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['firstResult', 'secondResult'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const genericFractionalConsumptionResultInputSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const genericFractionalConsumptionResultInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });
const genericFractionalConsumptionResultExpectedSchema = { 'additionalProperties': false, 'properties': { 'result': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['result'], 'type': 'object' } as const;
const genericFractionalConsumptionResultExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const genericWaitForTokenInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'allowance': { 'type': 'number' } }, 'required': ['allowance'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const genericWaitForTokenInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'allowance': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['allowance'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const genericWaitForTokenExpectedSchema = { 'additionalProperties': false, 'properties': { 'result': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['result'], 'type': 'object' } as const;
const genericWaitForTokenExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'result': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['result'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const gettersEvictionOnMaximumKeysInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'maximumKeys': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'maximumKeys', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const gettersEvictionOnMaximumKeysInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'maximumKeys': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'maximumKeys', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const gettersEvictionOnMaximumKeysExpectedSchema = { 'additionalProperties': false, 'properties': { 'evicted': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['evicted'], 'type': 'object' } as const;
const gettersEvictionOnMaximumKeysExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'evicted': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['evicted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const idleKeyExpiresAndRebuildsInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'keyIdleTtlMs': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' }, 'waitMs': { 'type': 'number' } }, 'required': ['burstSize', 'keyIdleTtlMs', 'requestsPerSecond', 'waitMs'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const idleKeyExpiresAndRebuildsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'keyIdleTtlMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitMs': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'keyIdleTtlMs', 'requestsPerSecond', 'waitMs'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const idleKeyExpiresAndRebuildsExpectedSchema = { 'additionalProperties': false, 'properties': { 'created': { 'items': { 'type': 'string' }, 'type': 'array' }, 'evicted': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['created', 'evicted'], 'type': 'object' } as const;
const idleKeyExpiresAndRebuildsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'created': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'evicted': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['created', 'evicted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const onTokenAcquiredInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const onTokenAcquiredInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const onTokenAcquiredExpectedSchema = { 'additionalProperties': false, 'properties': { 'acquired': { 'items': { 'additionalProperties': false, 'properties': { 'key': { 'type': 'string' }, 'result': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['key', 'result'], 'type': 'object' }, 'type': 'array' } }, 'required': ['acquired'], 'type': 'object' } as const;
const onTokenAcquiredExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'acquired': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'key': SchemaNode.defineString({ 'type': 'string' } as const), 'result': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['key', 'result'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['acquired'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const recreatesStrategyAfterEvictionInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'maximumKeys': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'maximumKeys', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const recreatesStrategyAfterEvictionInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'maximumKeys': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'maximumKeys', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const recreatesStrategyAfterEvictionExpectedSchema = { 'additionalProperties': false, 'properties': { 'created': { 'items': { 'type': 'string' }, 'type': 'array' }, 'evicted': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['created', 'evicted'], 'type': 'object' } as const;
const recreatesStrategyAfterEvictionExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'created': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'evicted': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['created', 'evicted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const throwingOnKeyEvictedInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'maximumKeys': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'maximumKeys', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const throwingOnKeyEvictedInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'maximumKeys': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'maximumKeys', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const throwingOnKeyEvictedExpectedSchema = { 'additionalProperties': false, 'properties': { 'created': { 'items': { 'type': 'string' }, 'type': 'array' }, 'evicted': { 'items': { 'type': 'string' }, 'type': 'array' } }, 'required': ['created', 'evicted'], 'type': 'object' } as const;
const throwingOnKeyEvictedExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'created': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'evicted': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined) }, ['created', 'evicted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const waitAbortSignalInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const waitAbortSignalInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const waitAbortSignalExpectedSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const waitAbortSignalExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });

const waitImmediateInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'consumeTokens': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'consumeTokens', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const waitImmediateInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'consumeTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'consumeTokens', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const waitImmediateExpectedSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const waitImmediateExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });

const waitRefillsAndIsolatesInputSchema = { 'additionalProperties': false, 'properties': { 'keyedRateLimiter': { 'additionalProperties': false, 'properties': { 'advanceTimeMs': { 'type': 'number' }, 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['advanceTimeMs', 'burstSize', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['keyedRateLimiter'], 'type': 'object' } as const;
const waitRefillsAndIsolatesInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'keyedRateLimiter': SchemaNode.defineObject({ 'type': 'object' } as const, { 'advanceTimeMs': SchemaNode.defineNumber({ 'type': 'number' } as const), 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['advanceTimeMs', 'burstSize', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['keyedRateLimiter'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const waitRefillsAndIsolatesExpectedSchema = { 'additionalProperties': false, 'properties': {  }, 'required': [], 'type': 'object' } as const;
const waitRefillsAndIsolatesExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, {  }, [] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** The scenario case shapes `keyed-rate-limiter.loop.spec.ts` exercises. */
export namespace KeyedRateLimiterScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('consume-default-result', consumeDefaultResultInputSchema, consumeDefaultResultExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('consume-independent-keys', consumeIndependentKeysInputSchema, consumeIndependentKeysExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('consume-requested-tokens', consumeRequestedTokensInputSchema, consumeRequestedTokensExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('consume-same-key-exhausts', consumeSameKeyExhaustsInputSchema, consumeSameKeyExhaustsExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('consume-strategy-created-once', consumeStrategyCreatedOnceInputSchema, consumeStrategyCreatedOnceExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('entities-invalid', entitiesInvalidInputSchema, entitiesInvalidExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('entities-valid', entitiesValidInputSchema, entitiesValidExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('evicts-idle-key-at-capacity', evictsIdleKeyAtCapacityInputSchema, evictsIdleKeyAtCapacityExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('generic-acquisition-observation', genericAcquisitionObservationInputSchema, genericAcquisitionObservationExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('generic-cache-boundary', genericCacheBoundaryInputSchema, genericCacheBoundaryExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('generic-fake-strategy', genericFakeStrategyInputSchema, genericFakeStrategyExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('generic-fractional-consumption-result', genericFractionalConsumptionResultInputSchema, genericFractionalConsumptionResultExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('generic-wait-for-token', genericWaitForTokenInputSchema, genericWaitForTokenExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('getters-eviction-on-max-keys', gettersEvictionOnMaximumKeysInputSchema, gettersEvictionOnMaximumKeysExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('idle-key-expires-and-rebuilds', idleKeyExpiresAndRebuildsInputSchema, idleKeyExpiresAndRebuildsExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('on-token-acquired', onTokenAcquiredInputSchema, onTokenAcquiredExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('recreates-strategy-after-eviction', recreatesStrategyAfterEvictionInputSchema, recreatesStrategyAfterEvictionExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('throwing-on-key-evicted', throwingOnKeyEvictedInputSchema, throwingOnKeyEvictedExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('wait-abort-signal', waitAbortSignalInputSchema, waitAbortSignalExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('wait-immediate', waitImmediateInputSchema, waitImmediateExpectedSchema),
      KeyedRateLimiterScenarioCaseBuilders.scenarioSchema('wait-refills-and-isolates', waitRefillsAndIsolatesInputSchema, waitRefillsAndIsolatesExpectedSchema)
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('consume-default-result', consumeDefaultResultInputNode, consumeDefaultResultExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('consume-independent-keys', consumeIndependentKeysInputNode, consumeIndependentKeysExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('consume-requested-tokens', consumeRequestedTokensInputNode, consumeRequestedTokensExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('consume-same-key-exhausts', consumeSameKeyExhaustsInputNode, consumeSameKeyExhaustsExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('consume-strategy-created-once', consumeStrategyCreatedOnceInputNode, consumeStrategyCreatedOnceExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('entities-invalid', entitiesInvalidInputNode, entitiesInvalidExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('entities-valid', entitiesValidInputNode, entitiesValidExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('evicts-idle-key-at-capacity', evictsIdleKeyAtCapacityInputNode, evictsIdleKeyAtCapacityExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('generic-acquisition-observation', genericAcquisitionObservationInputNode, genericAcquisitionObservationExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('generic-cache-boundary', genericCacheBoundaryInputNode, genericCacheBoundaryExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('generic-fake-strategy', genericFakeStrategyInputNode, genericFakeStrategyExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('generic-fractional-consumption-result', genericFractionalConsumptionResultInputNode, genericFractionalConsumptionResultExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('generic-wait-for-token', genericWaitForTokenInputNode, genericWaitForTokenExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('getters-eviction-on-max-keys', gettersEvictionOnMaximumKeysInputNode, gettersEvictionOnMaximumKeysExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('idle-key-expires-and-rebuilds', idleKeyExpiresAndRebuildsInputNode, idleKeyExpiresAndRebuildsExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('on-token-acquired', onTokenAcquiredInputNode, onTokenAcquiredExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('recreates-strategy-after-eviction', recreatesStrategyAfterEvictionInputNode, recreatesStrategyAfterEvictionExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('throwing-on-key-evicted', throwingOnKeyEvictedInputNode, throwingOnKeyEvictedExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('wait-abort-signal', waitAbortSignalInputNode, waitAbortSignalExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('wait-immediate', waitImmediateInputNode, waitImmediateExpectedNode),
    KeyedRateLimiterScenarioCaseBuilders.scenarioNode('wait-refills-and-isolates', waitRefillsAndIsolatesInputNode, waitRefillsAndIsolatesExpectedNode)
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
