import type { EntityCreateFunctionInterface, EntityIntakeFunctionInterface, EntityValidateFunctionInterface, SchemaNodeInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

/** Builds the `{ description, expected, input, name, shape }` envelope one branch of the case union shares, varying only `shape` and the two payloads. */
class TokenBucketScenarioCaseBuilders {
  static scenarioSchema<const TShape extends string, TInputSchema extends object, TExpectedSchema extends object>(shape: TShape, inputSchema: TInputSchema, expectedSchema: TExpectedSchema) {
    const result = {
      'additionalProperties': false,
      'properties': {
        'description': { 'minLength': 1, 'type': 'string' },
        'expected': expectedSchema,
        'input': inputSchema,
        'name': { 'minLength': 1, 'type': 'string' },
        'shape': { 'const': shape }
      },
      'required': ['description', 'expected', 'input', 'name', 'shape'],
      'type': 'object'
    } as const;
    return result;
  }

  static scenarioNode<const TShape extends string, TInputNode extends SchemaNodeInterface<unknown, unknown>, TExpectedNode extends SchemaNodeInterface<unknown, unknown>>(shape: TShape, inputNode: TInputNode, expectedNode: TExpectedNode) {
    const result = SchemaNode.defineObject({ 'type': 'object' } as const, {
      'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'expected': expectedNode,
      'input': inputNode,
      'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const),
      'shape': SchemaNode.defineConst({}, shape)
    }, ['description', 'expected', 'input', 'name', 'shape'] as const, { 'additionalProperties': false, 'patternProperties': {} });
    return result;
  }
}

const entityRateLimitConsumptionInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'invalid': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' }, 'valid': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['invalid', 'valid'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const entityRateLimitConsumptionInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'invalid': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'valid': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['invalid', 'valid'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const entityRateLimitConsumptionExpectedSchema = { 'additionalProperties': false, 'properties': { 'invalid': { 'type': 'boolean' }, 'valid': { 'type': 'boolean' } }, 'required': ['invalid', 'valid'], 'type': 'object' } as const;
const entityRateLimitConsumptionExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'invalid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'valid': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['invalid', 'valid'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbAsyncHookIsolationInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'type': 'number' }, 'first': { 'type': 'string' }, 'requestsPerSecond': { 'type': 'number' }, 'second': { 'type': 'string' } }, 'required': ['burstSize', 'clock', 'first', 'requestsPerSecond', 'second'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbAsyncHookIsolationInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineNumber({ 'type': 'number' } as const), 'first': SchemaNode.defineString({ 'type': 'string' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const), 'second': SchemaNode.defineString({ 'type': 'string' } as const) }, ['burstSize', 'clock', 'first', 'requestsPerSecond', 'second'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbAsyncHookIsolationExpectedSchema = { 'additionalProperties': false, 'properties': { 'hookErrorCount': { 'type': 'number' }, 'hookName': { 'type': 'string' }, 'rejectionEvents': { 'type': 'number' } }, 'required': ['hookErrorCount', 'hookName', 'rejectionEvents'], 'type': 'object' } as const;
const tbAsyncHookIsolationExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'hookErrorCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'hookName': SchemaNode.defineString({ 'type': 'string' } as const), 'rejectionEvents': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['hookErrorCount', 'hookName', 'rejectionEvents'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbAvailableInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'type': 'number' }, 'consume': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbAvailableInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineNumber({ 'type': 'number' } as const), 'consume': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbAvailableExpectedSchema = { 'additionalProperties': false, 'properties': { 'available': { 'items': { 'type': 'number' }, 'type': 'array' } }, 'required': ['available'], 'type': 'object' } as const;
const tbAvailableExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'available': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined) }, ['available'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbCapInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbCapInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbCapExpectedSchema = { 'additionalProperties': false, 'properties': { 'availableAtCap': { 'type': 'number' } }, 'required': ['availableAtCap'], 'type': 'object' } as const;
const tbCapExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'availableAtCap': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['availableAtCap'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbConsumeExhaustedInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'consume': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbConsumeExhaustedInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'consume': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbConsumeExhaustedExpectedSchema = { 'additionalProperties': false, 'properties': { 'exhausted': { 'type': 'boolean' } }, 'required': ['exhausted'], 'type': 'object' } as const;
const tbConsumeExhaustedExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'exhausted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['exhausted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbConsumeMultiInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'consume': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbConsumeMultiInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'consume': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbConsumeMultiExpectedSchema = { 'additionalProperties': false, 'properties': { 'exhaustedOnSecondConsume': { 'type': 'boolean' } }, 'required': ['exhaustedOnSecondConsume'], 'type': 'object' } as const;
const tbConsumeMultiExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'exhaustedOnSecondConsume': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['exhaustedOnSecondConsume'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbConsumeOkInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'type': 'number' }, 'consume': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbConsumeOkInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineNumber({ 'type': 'number' } as const), 'consume': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbConsumeOkExpectedSchema = { 'additionalProperties': false, 'properties': { 'available': { 'type': 'number' }, 'exhausted': { 'type': 'boolean' } }, 'required': ['available', 'exhausted'], 'type': 'object' } as const;
const tbConsumeOkExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'available': SchemaNode.defineNumber({ 'type': 'number' } as const), 'exhausted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['available', 'exhausted'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbConsumptionObservationInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'consume': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbConsumptionObservationInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'consume': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbConsumptionObservationExpectedSchema = { 'additionalProperties': false, 'properties': { 'observation': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['observation'], 'type': 'object' } as const;
const tbConsumptionObservationExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'observation': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['observation'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbHookSwallowsInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'type': 'number' }, 'consume': { 'type': 'number' }, 'depletedBurstSize': { 'type': 'number' }, 'refillBurstSize': { 'type': 'number' }, 'refillClock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' }, 'waitBurstSize': { 'type': 'number' }, 'waitTokens': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'consume', 'depletedBurstSize', 'refillBurstSize', 'refillClock', 'requestsPerSecond', 'waitBurstSize', 'waitTokens'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbHookSwallowsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineNumber({ 'type': 'number' } as const), 'consume': SchemaNode.defineNumber({ 'type': 'number' } as const), 'depletedBurstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'refillBurstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'refillClock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitBurstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'waitTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'consume', 'depletedBurstSize', 'refillBurstSize', 'refillClock', 'requestsPerSecond', 'waitBurstSize', 'waitTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbHookSwallowsExpectedSchema = { 'additionalProperties': false, 'properties': { 'available': { 'items': { 'type': 'number' }, 'type': 'array' }, 'errorsSwallowed': { 'type': 'boolean' } }, 'required': ['available', 'errorsSwallowed'], 'type': 'object' } as const;
const tbHookSwallowsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'available': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'errorsSwallowed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['available', 'errorsSwallowed'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbInvalidBurstInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbInvalidBurstInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbInvalidBurstExpectedSchema = { 'additionalProperties': false, 'properties': { 'throws': { 'type': 'string' } }, 'required': ['throws'], 'type': 'object' } as const;
const tbInvalidBurstExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': SchemaNode.defineString({ 'type': 'string' } as const) }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbInvalidRpsInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbInvalidRpsInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbInvalidRpsExpectedSchema = { 'additionalProperties': false, 'properties': { 'throws': { 'type': 'string' } }, 'required': ['throws'], 'type': 'object' } as const;
const tbInvalidRpsExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'throws': SchemaNode.defineString({ 'type': 'string' } as const) }, ['throws'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbListenerLeakInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'iterations': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'iterations', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbListenerLeakInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'iterations': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'iterations', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbListenerLeakExpectedSchema = { 'additionalProperties': false, 'properties': { 'addCount': { 'type': 'number' }, 'removeCount': { 'type': 'number' } }, 'required': ['addCount', 'removeCount'], 'type': 'object' } as const;
const tbListenerLeakExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'addCount': SchemaNode.defineNumber({ 'type': 'number' } as const), 'removeCount': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['addCount', 'removeCount'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbObservedAcquiredInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'type': 'number' }, 'consume': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbObservedAcquiredInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineNumber({ 'type': 'number' } as const), 'consume': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbObservedAcquiredExpectedSchema = { 'additionalProperties': false, 'properties': { 'events': { 'items': { 'additionalProperties': false, 'properties': { 'type': { 'type': 'string' }, 'value': { 'type': 'number' } }, 'required': ['type', 'value'], 'type': 'object' }, 'type': 'array' } }, 'required': ['events'], 'type': 'object' } as const;
const tbObservedAcquiredExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'events': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineObject({ 'type': 'object' } as const, { 'type': SchemaNode.defineString({ 'type': 'string' } as const), 'value': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['type', 'value'] as const, { 'additionalProperties': false, 'patternProperties': {} }), undefined) }, ['events'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbObservedDepletedInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'type': 'number' }, 'consume': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbObservedDepletedInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineNumber({ 'type': 'number' } as const), 'consume': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbObservedDepletedExpectedSchema = { 'additionalProperties': false, 'properties': { 'eventsContain': { 'type': 'string' } }, 'required': ['eventsContain'], 'type': 'object' } as const;
const tbObservedDepletedExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'eventsContain': SchemaNode.defineString({ 'type': 'string' } as const) }, ['eventsContain'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbObservedRefillInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'consume': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbObservedRefillInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'consume': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbObservedRefillExpectedSchema = { 'additionalProperties': false, 'properties': { 'eventsContain': { 'type': 'string' } }, 'required': ['eventsContain'], 'type': 'object' } as const;
const tbObservedRefillExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'eventsContain': SchemaNode.defineString({ 'type': 'string' } as const) }, ['eventsContain'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbObservedWaitInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbObservedWaitInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbObservedWaitExpectedSchema = { 'additionalProperties': false, 'properties': { 'eventsContain': { 'type': 'string' } }, 'required': ['eventsContain'], 'type': 'object' } as const;
const tbObservedWaitExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'eventsContain': SchemaNode.defineString({ 'type': 'string' } as const) }, ['eventsContain'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbRefillInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'consume': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'consume', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbRefillInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'consume': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'consume', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbRefillExpectedSchema = { 'additionalProperties': false, 'properties': { 'availableAfterConsume': { 'type': 'number' }, 'availableAfterRefillAt500Ms': { 'type': 'number' } }, 'required': ['availableAfterConsume', 'availableAfterRefillAt500Ms'], 'type': 'object' } as const;
const tbRefillExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'availableAfterConsume': SchemaNode.defineNumber({ 'type': 'number' } as const), 'availableAfterRefillAt500Ms': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['availableAfterConsume', 'availableAfterRefillAt500Ms'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbWaitAbortInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'aborted': { 'type': 'boolean' }, 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' }, 'tokens': { 'type': 'number' } }, 'required': ['aborted', 'burstSize', 'requestsPerSecond', 'tokens'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbWaitAbortInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'aborted': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const), 'tokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['aborted', 'burstSize', 'requestsPerSecond', 'tokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbWaitAbortExpectedSchema = { 'additionalProperties': false, 'properties': { 'rejects': { 'type': 'boolean' } }, 'required': ['rejects'], 'type': 'object' } as const;
const tbWaitAbortExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'rejects': SchemaNode.defineBoolean({ 'type': 'boolean' } as const) }, ['rejects'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbWaitImmediateInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbWaitImmediateInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbWaitImmediateExpectedSchema = { 'additionalProperties': false, 'properties': { 'availableAfterWait': { 'type': 'number' } }, 'required': ['availableAfterWait'], 'type': 'object' } as const;
const tbWaitImmediateExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'availableAfterWait': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['availableAfterWait'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbWaitRefillInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'clock': { 'items': { 'type': 'number' }, 'type': 'array' }, 'requestsPerSecond': { 'type': 'number' } }, 'required': ['burstSize', 'clock', 'requestsPerSecond'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbWaitRefillInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'clock': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineNumber({ 'type': 'number' } as const), undefined), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'clock', 'requestsPerSecond'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbWaitRefillExpectedSchema = { 'additionalProperties': false, 'properties': { 'availableAfterWait': { 'type': 'number' }, 'completed': { 'type': 'boolean' }, 'observation': { 'additionalProperties': false, 'properties': { 'consumedTokens': { 'type': 'number' }, 'remainingTokens': { 'type': 'number' } }, 'required': ['consumedTokens', 'remainingTokens'], 'type': 'object' } }, 'required': ['availableAfterWait', 'completed', 'observation'], 'type': 'object' } as const;
const tbWaitRefillExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'availableAfterWait': SchemaNode.defineNumber({ 'type': 'number' } as const), 'completed': SchemaNode.defineBoolean({ 'type': 'boolean' } as const), 'observation': SchemaNode.defineObject({ 'type': 'object' } as const, { 'consumedTokens': SchemaNode.defineNumber({ 'type': 'number' } as const), 'remainingTokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['consumedTokens', 'remainingTokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['availableAfterWait', 'completed', 'observation'] as const, { 'additionalProperties': false, 'patternProperties': {} });

const tbWaitTooManyInputSchema = { 'additionalProperties': false, 'properties': { 'resilience': { 'additionalProperties': false, 'properties': { 'burstSize': { 'type': 'number' }, 'requestsPerSecond': { 'type': 'number' }, 'tokens': { 'type': 'number' } }, 'required': ['burstSize', 'requestsPerSecond', 'tokens'], 'type': 'object' } }, 'required': ['resilience'], 'type': 'object' } as const;
const tbWaitTooManyInputNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'resilience': SchemaNode.defineObject({ 'type': 'object' } as const, { 'burstSize': SchemaNode.defineNumber({ 'type': 'number' } as const), 'requestsPerSecond': SchemaNode.defineNumber({ 'type': 'number' } as const), 'tokens': SchemaNode.defineNumber({ 'type': 'number' } as const) }, ['burstSize', 'requestsPerSecond', 'tokens'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['resilience'] as const, { 'additionalProperties': false, 'patternProperties': {} });
const tbWaitTooManyExpectedSchema = { 'additionalProperties': false, 'properties': { 'error': { 'type': 'string' } }, 'required': ['error'], 'type': 'object' } as const;
const tbWaitTooManyExpectedNode = SchemaNode.defineObject({ 'type': 'object' } as const, { 'error': SchemaNode.defineString({ 'type': 'string' } as const) }, ['error'] as const, { 'additionalProperties': false, 'patternProperties': {} });

/** The scenario case shapes `token-bucket.loop.spec.ts` exercises. */
export namespace TokenBucketScenarioCaseEntity {
  export const Schema = {
    'oneOf': [
      TokenBucketScenarioCaseBuilders.scenarioSchema('entity-rate-limit-consumption', entityRateLimitConsumptionInputSchema, entityRateLimitConsumptionExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-async-hook-isolation', tbAsyncHookIsolationInputSchema, tbAsyncHookIsolationExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-available', tbAvailableInputSchema, tbAvailableExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-cap', tbCapInputSchema, tbCapExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-consume-exhausted', tbConsumeExhaustedInputSchema, tbConsumeExhaustedExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-consume-multi', tbConsumeMultiInputSchema, tbConsumeMultiExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-consume-ok', tbConsumeOkInputSchema, tbConsumeOkExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-consumption-observation', tbConsumptionObservationInputSchema, tbConsumptionObservationExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-hook-swallows', tbHookSwallowsInputSchema, tbHookSwallowsExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-invalid-burst', tbInvalidBurstInputSchema, tbInvalidBurstExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-invalid-rps', tbInvalidRpsInputSchema, tbInvalidRpsExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-listener-leak', tbListenerLeakInputSchema, tbListenerLeakExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-observed-acquired', tbObservedAcquiredInputSchema, tbObservedAcquiredExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-observed-depleted', tbObservedDepletedInputSchema, tbObservedDepletedExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-observed-refill', tbObservedRefillInputSchema, tbObservedRefillExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-observed-wait', tbObservedWaitInputSchema, tbObservedWaitExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-refill', tbRefillInputSchema, tbRefillExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-wait-abort', tbWaitAbortInputSchema, tbWaitAbortExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-wait-immediate', tbWaitImmediateInputSchema, tbWaitImmediateExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-wait-refill', tbWaitRefillInputSchema, tbWaitRefillExpectedSchema),
      TokenBucketScenarioCaseBuilders.scenarioSchema('tb-wait-too-many', tbWaitTooManyInputSchema, tbWaitTooManyExpectedSchema)
    ]
  } as const;

  export const Node = SchemaNode.defineOneOf({}, [
    TokenBucketScenarioCaseBuilders.scenarioNode('entity-rate-limit-consumption', entityRateLimitConsumptionInputNode, entityRateLimitConsumptionExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-async-hook-isolation', tbAsyncHookIsolationInputNode, tbAsyncHookIsolationExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-available', tbAvailableInputNode, tbAvailableExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-cap', tbCapInputNode, tbCapExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-consume-exhausted', tbConsumeExhaustedInputNode, tbConsumeExhaustedExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-consume-multi', tbConsumeMultiInputNode, tbConsumeMultiExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-consume-ok', tbConsumeOkInputNode, tbConsumeOkExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-consumption-observation', tbConsumptionObservationInputNode, tbConsumptionObservationExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-hook-swallows', tbHookSwallowsInputNode, tbHookSwallowsExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-invalid-burst', tbInvalidBurstInputNode, tbInvalidBurstExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-invalid-rps', tbInvalidRpsInputNode, tbInvalidRpsExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-listener-leak', tbListenerLeakInputNode, tbListenerLeakExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-observed-acquired', tbObservedAcquiredInputNode, tbObservedAcquiredExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-observed-depleted', tbObservedDepletedInputNode, tbObservedDepletedExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-observed-refill', tbObservedRefillInputNode, tbObservedRefillExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-observed-wait', tbObservedWaitInputNode, tbObservedWaitExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-refill', tbRefillInputNode, tbRefillExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-wait-abort', tbWaitAbortInputNode, tbWaitAbortExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-wait-immediate', tbWaitImmediateInputNode, tbWaitImmediateExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-wait-refill', tbWaitRefillInputNode, tbWaitRefillExpectedNode),
    TokenBucketScenarioCaseBuilders.scenarioNode('tb-wait-too-many', tbWaitTooManyInputNode, tbWaitTooManyExpectedNode)
  ] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
  export const create: EntityCreateFunctionInterface<Type> = EntityCompiler.compileCreate<Type>(Schema);
}
