import type { EntityIntakeFunctionInterface, EntityValidateFunctionInterface } from '@studnicky/entity/interfaces';
import type { NodeStaticType } from '@studnicky/entity/types';

import { EntityCompiler } from '@studnicky/entity/browser';
import { SchemaNode } from '@studnicky/entity/types';

import { DeepJsonValueEntity } from '../../../helpers/entities/DeepJsonValueEntity.js';

/** The `body-serialization.loop.spec.ts` scenario case shape: one branch per `operation`. */
export namespace BodySerializationScenarioCaseEntity {
  export const Schema = { 'oneOf': [{ 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'json': DeepJsonValueEntity.Schema, 'status': { 'type': 'integer' } }, 'required': ['status', 'json'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'request': { 'additionalProperties': false, 'properties': { 'body': DeepJsonValueEntity.Schema, 'method': { 'enum': ['PATCH', 'POST', 'PUT'] }, 'path': { 'type': 'string' } }, 'required': ['method', 'path', 'body'], 'type': 'object' } }, 'required': ['request'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'operation': { 'const': 'succeeds' } }, 'required': ['description', 'expected', 'input', 'name', 'operation'], 'type': 'object' }, { 'additionalProperties': false, 'properties': { 'description': { 'minLength': 1, 'type': 'string' }, 'expected': { 'additionalProperties': false, 'properties': { 'messageIncludes': { 'items': { 'type': 'string' }, 'type': 'array' }, 'name': { 'type': 'string' } }, 'required': ['messageIncludes', 'name'], 'type': 'object' }, 'input': { 'additionalProperties': false, 'properties': { 'request': { 'additionalProperties': false, 'properties': { 'body': DeepJsonValueEntity.Schema, 'method': { 'enum': ['PATCH', 'POST', 'PUT'] }, 'path': { 'type': 'string' } }, 'required': ['method', 'path', 'body'], 'type': 'object' } }, 'required': ['request'], 'type': 'object' }, 'name': { 'minLength': 1, 'type': 'string' }, 'operation': { 'const': 'rejects' } }, 'required': ['description', 'expected', 'input', 'name', 'operation'], 'type': 'object' }] } as const;

  export const Node = SchemaNode.defineOneOf({}, [SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'json': DeepJsonValueEntity.Node, 'status': SchemaNode.defineNumber({ 'type': 'integer' } as const) }, ['status', 'json'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'request': SchemaNode.defineObject({ 'type': 'object' } as const, { 'body': DeepJsonValueEntity.Node, 'method': SchemaNode.defineEnum({}, ['PATCH', 'POST', 'PUT'] as const), 'path': SchemaNode.defineString({ 'type': 'string' } as const) }, ['method', 'path', 'body'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['request'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'operation': SchemaNode.defineConst({}, 'succeeds' as const) }, ['description', 'expected', 'input', 'name', 'operation'] as const, { 'additionalProperties': false, 'patternProperties': {} }), SchemaNode.defineObject({ 'type': 'object' } as const, { 'description': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'expected': SchemaNode.defineObject({ 'type': 'object' } as const, { 'messageIncludes': SchemaNode.defineArray({ 'type': 'array' } as const, SchemaNode.defineString({ 'type': 'string' } as const), undefined), 'name': SchemaNode.defineString({ 'type': 'string' } as const) }, ['messageIncludes', 'name'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'input': SchemaNode.defineObject({ 'type': 'object' } as const, { 'request': SchemaNode.defineObject({ 'type': 'object' } as const, { 'body': DeepJsonValueEntity.Node, 'method': SchemaNode.defineEnum({}, ['PATCH', 'POST', 'PUT'] as const), 'path': SchemaNode.defineString({ 'type': 'string' } as const) }, ['method', 'path', 'body'] as const, { 'additionalProperties': false, 'patternProperties': {} }) }, ['request'] as const, { 'additionalProperties': false, 'patternProperties': {} }), 'name': SchemaNode.defineString({ 'minLength': 1, 'type': 'string' } as const), 'operation': SchemaNode.defineConst({}, 'rejects' as const) }, ['description', 'expected', 'input', 'name', 'operation'] as const, { 'additionalProperties': false, 'patternProperties': {} })] as const);
  export type Type = NodeStaticType<typeof Node>;

  export const validate: EntityValidateFunctionInterface<Type> = EntityCompiler.compile<Type>(Schema);
  export const intake: EntityIntakeFunctionInterface<Type> = EntityCompiler.compileIntake<Type>(Schema);
}
