/** Typed keyword fields extracted from one schema node in a single traversal. */
export interface SchemaNodePlanInterface {
  readonly 'additionalProperties': unknown;
  readonly 'allOf': readonly unknown[] | undefined;
  readonly 'anyOf': readonly unknown[] | undefined;
  readonly 'const': { readonly 'value': unknown } | undefined;
  readonly 'contains': unknown;
  readonly 'contentEncoding': string | undefined;
  readonly 'contentMediaType': string | undefined;
  readonly 'default': { readonly 'value': unknown } | undefined;
  readonly 'defs': ReadonlyMap<string, unknown>;
  readonly 'dependentRequired': ReadonlyMap<string, readonly string[]>;
  readonly 'dependentSchemas': ReadonlyMap<string, unknown>;
  readonly 'dynamicAnchor': string | undefined;
  readonly 'dynamicReference': string | undefined;
  readonly 'else': unknown;
  readonly 'enum': readonly unknown[] | undefined;
  readonly 'exclusiveMaximum': number | undefined;
  readonly 'exclusiveMinimum': number | undefined;
  readonly 'format': string | undefined;
  readonly 'id': string | undefined;
  readonly 'if': unknown;
  readonly 'items': unknown;
  readonly 'maximum': number | undefined;
  readonly 'maximumContains': number | undefined;
  readonly 'maximumItems': number | undefined;
  readonly 'maximumLength': number | undefined;
  readonly 'maximumProperties': number | undefined;
  readonly 'minimum': number | undefined;
  readonly 'minimumContains': number | undefined;
  readonly 'minimumItems': number | undefined;
  readonly 'minimumLength': number | undefined;
  readonly 'minimumProperties': number | undefined;
  readonly 'multipleOf': number | undefined;
  readonly 'not': unknown;
  readonly 'oneOf': readonly unknown[] | undefined;
  readonly 'pattern': string | undefined;
  readonly 'patternProperties': ReadonlyMap<string, unknown>;
  readonly 'prefixItems': readonly unknown[] | undefined;
  readonly 'properties': ReadonlyMap<string, unknown>;
  readonly 'propertyNames': unknown;
  readonly 'reference': string | undefined;
  readonly 'required': readonly string[];
  readonly 'schemaPointer': string;
  readonly 'thenSchema': unknown;
  readonly 'type': readonly string[] | undefined;
  readonly 'unevaluatedItems': unknown;
  readonly 'unevaluatedProperties': unknown;
  readonly 'uniqueItems': boolean;
}
